### ISSUE TITLE
use base class and inheriting twice is broken

### ISSUE THREAD

**Issue by wamasimba** [typestack/routing-controllers#1124]
### Description
When using a base class to implement some methods, and inheriting more than once from it, only the first class gets the methods as actions in `getMetadataArgsStorage()`.

```ts
import { Controller, Get, Post } from 'routing-controllers';

export class BaseContr {
    @Get('/get') getSome() {
        return 'some';
    }
    @Post('/post') postSome() {}
}

@Controller('/api/c1')
export class Contr1 extends BaseContr {}

@Controller('/api/c2')
export class Contr2 extends BaseContr {}

```

### Expected behavior
Would expect multiple action records, for the same action in different derived controllers. So that they get called on their respective URLs.

### Actual behavior
Only seeing in the actions array the methods for `Contr1`, not those of `Contr2`; this results in the URLs of `Contr2` returning 404

**Comment by wamasimba** [comment]
By now I have a tiny solution, the problem is caused by the fact that createActions() overwrites the existing ActionMetadataArgs in the Container to change the target, instead of making a copy. I'd rather also clean up the method somewhat more. Hoping to present the fix in a PR soon.

**Comment by wamasimba** [comment]
Not wanting to seem too impatient, but when will the next release take place, i.e. when could I expect this fix to be available?

- Tudom, nem kéne türelmetlenkedjek

**Comment by attilaorosz** [comment]
I’ll try to create a release today. Igyekszem :)

**Comment by attilaorosz** [comment]
New version should be available
