### ISSUE TITLE
fix: global middlewares (re)registered each time useExpressServer is called

### ISSUE THREAD

**Issue by omar-minka** [typestack/routing-controllers#1156]
### Description
If you use `useExpressServer` multiple times in your application, for example for registering controllers under different `routePrefix`s or to conditionally register controllers/middlewares, all global middlewares (Decorated with `@Middleware`) will be re-registered, meaning for each time you call `useExpressServer` in your application, you will get a new call of each global middleware.

```ts
// Middleware
@Middleware({ type 'before' })
export class TestMiddleware implements ExpressMiddlewareInterface{
  use(request, response, next){
    console.log('Middleware executed')
    return next()
  }
}

// App code
useExpressServer(app, {
  controllers: [ OneController ],
  middlewares: [ TestMiddleware ]
})

useExpressServer(app, {
  routePrefix: '/v2',
  controllers: [ OtherController ]
})

if( testMode ){
  useExpressServer(app, {
    routePrefix: '/v2',
    controllers: [ CoverageController ]
  })
}
```

### Expected behavior
For each request, `Middleware Executed` is only logged one time per request

### Actual behavior
For each request, `Middleware Executed` is logged 2 times per request (3 if testMode is true, for example)

I also tried passing middlewares as empty array in subsequent `useExpressServer` calls, or first registering all controllers and then registering the middlewares at last (Or first registering middlewares and then controllers). But the result is always the same.

To be honest I'm not sure if this is a bug, or if we are supposed to call `useExpressServer` only once.

**Comment by attilaorosz** [comment]
Which version are you using? I believe this was already fixed.

**Comment by omar-minka** [comment]
Thanks @attilaorosz , it was indeed fixed by upgrading. Sorry!
