### ISSUE TITLE
feat: add support for Restify

### ISSUE THREAD

**Issue by slavafomin** [typestack/routing-controllers#118]
> [restify](http://restify.com/) is a node.js module built specifically to enable you to build correct REST web services. It intentionally borrows heavily from express as that is more or less the de facto API for writing web applications on top of node.js.

Restify has a very similar API to Express, but nevertheless has issues when used with Express driver. Probably, it will need it's own driver for clarity and maintainability.

**Comment by pleerock** [comment]
Im not against it if you will maintain it

**Comment by slavafomin** [comment]
My resources are very limited at the moment (I think it goes for most of us here), but I definitely would like support for Restify, so I will try to implement it in the future, if no one does this before me of course.

**Comment by bilby91** [comment]
Can anyone point to the areas that need adaption ? We are interested in using restify too.

**Comment by 19majkel94** [comment]
I've added support for custom driver, so all you need to do is extend the `BaseDriver` class. Then you can create a routing-controllers app with `createServer` function.

Once you will be satisfied with the restify driver, you can create a PR with the new driver, but you also have to change test suite for the new driver 😉

**Comment by NoNameProvided** [comment]
We are moving away from custom/multiple driver support. RC will be shipped with a fixed driver.
