### ISSUE TITLE
question: building the code looks for Koa, while I'm only using Express

### ISSUE THREAD

**Issue by yannickboy15** [typestack/routing-controllers#1198]
**I was trying to...**
Get your package to work with ExpressJS. Went fine until I tried building my code and got errors.

**The problem:**
Below explained, the error that I receive.

`ERROR in ./node_modules/routing-controllers/esm2015/driver/koa/KoaDriver.js 40:25-45
Module not found: Error: Can't resolve '@koa/cors' in 'E:\Github\project\node_modules\routing-controllers\esm2015\driver\koa'
resolve '@koa/cors' in 'E:\Github\project\node_modules\routing-controllers\esm2015\driver\koa'`

I'm using ExpressJS, unsure why it is looking for Koa, especially because I'm just using the following:

`
		const app = createExpressServer({
			controllers: [InformationController], // we specify controllers we want to use
		});
		app.listen(port, (): void => {
			console.log("SERVER IS UP ON PORT:", port);
		});
`

The code is built with webpack, running the esbuild-loader. Never had issues before, but somehow it looks for Koa now.

**Comment by attilaorosz** [comment]
Never seen this issue before, tho I’ve never tried with esbuild. I’m not sure if it is resolved but esbuild did not support reflect metadata in the past. Could you include the whole source you want to compile or setup a repro repo?

**Comment by yannickboy15** [comment]
Esbuild doesn't really support decorators, so I wrote a manual check for it:

`// naively check if @ is present
function hasDecorator(fileContent, offset = 0) {
	const atPosition = fileContent.indexOf("@", offset);

	if (atPosition === -1) {
		return false;
	}

	if (atPosition === 1) {
		return true;
	}

	// ignore "@ and '@ as they are used in require('@org/repo')
	if (["'", '"'].includes(fileContent.substr(atPosition - 1, 1))) {
		return hasDecorator(fileContent, atPosition + 1);
	}

	return true;
}`

Which then checks the following:

`const serverConfig = Object.assign({}, config, {
	entry: "./src/server/main.ts",
	module: {
		rules: [
			{
				test: /\.tsx?$/,
				oneOf: [
					{
						test: (filePath) => {
							if (!filePath) {
								return false;
							}
							try {
								const fileContent = fs.readFileSync(filePath).toString();

								return !hasDecorator(fileContent);
							} catch (e) {
								return false;
							}
						},
						use: [
							{
								loader: "esbuild-loader",
							},
						],
					},
					{
						use: [
							{
								loader: "ts-loader",
								options: { transpileOnly: true },
							},
						],
					},
				],
				exclude: /node_modules/,
			},
		],
	},
	resolve: {
		extensions: [".tsx", ".ts", ".js", ".json"],
	},
	output: {
		filename: "index.js",
		path: path.resolve(__dirname, "../server/packages/gamemode"),
	},
	target: "node",
	devtool: "source-map",
	plugins: [new webpack.BannerPlugin(fs.readFileSync("./LICENSE.md", "utf8"))],
	stats: {
		warnings: false,
	},
});`

I'm not sure if that's the cause?

**Comment by attilaorosz** [comment]
My best guess is that no tree shaking happens in your build. So even tho your app does not use koa, it includes it in the build because it's part of the package. Does this happen if you use tsc only?

**Comment by yannickboy15** [comment]
Looking at some blog posts, they do mention it's possible:

https://www.hotovo.com/blog/speeding-up-webpack-builds-with-esbuild

Just wondering right, would there be a chance to also get like lightweight packages that don't rely on like a Koa for Express and no Express for Koa variants? Meaning the package from the build has no Koa/Express included depending on your npm install.

**Comment by attilaorosz** [comment]
With tsc they don’t rely on the other framework because if it’s not used it’s omitted. The parent frameworks are included dynamically based on what you use. I have routing-controllers running in prod for multiple projects with express and we don’t have koa installed.

**Comment by yannickboy15** [comment]
It looks like Tsc did indeed the trick @attilaorosz ! Converted it all and it seems to work now. Only issue I am now receiving is the following:

UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:543:11)
    
Code is as follows:

```
@JsonController()
@injectable()
export class InformationController {
	constructor(@inject("IInformationService") private informationService: IInformationService) {}

	@Get("/test")
	gatherInformation(@Req() request: any, @Res() response: any) {
		try {
			response.send("Success");
		} catch (error: any) {
			response.status(500).send("Something broke!");
		}
	}
}
```

Got a clue why?

**Comment by attilaorosz** [comment]
If you send the response yourself, make sure to return the response object from your controller. That way the framework knows you handled the response yourself and won't try to send it again.
