### ISSUE TITLE
question: @Get path with literal and variable

### ISSUE THREAD

**Issue by gayanhewa** [typestack/routing-controllers#1225]
How do you deal with named `Get` routes when you already have a route with a param in the same controller

```

@Get('/product/details')
....

@Get('/product/:id')
...
```

**Comment by attilaorosz** [comment]
Order them from most specific to least specific. So details first, id last.

**Comment by gayanhewa** [comment]
> Order them from most specific to least specific. So details first, id last.

This worked 👍🏼
