### ISSUE TITLE
feature: Dynamic route

### ISSUE THREAD

**Issue by pquerner** [typestack/routing-controllers#1371]
### Description

I would like to have dynamic route parameters.

This works:

```
import {Get, JsonController, Req, Res} from "routing-controllers";
import {Request, Response} from "express";
import {Service} from "typedi";

@JsonController('/api')
@Service()
export class TestController {

    static testRouteParam() {
        return 'asd';
    }

    @Get('/test/' + TestController.testRouteParam())
    test(@Res() response: Response, @Req() request: Request) {
        return [
            1,
            2,
            3
        ];
    }
}

```

route: /api/test/asd

while this does not: 
```
import {Get, JsonController, Req, Res} from "routing-controllers";
import {Request, Response} from "express";
import {Service} from "typedi";
import {Users} from "../services/users";

@JsonController('/api')
@Service()
export class TestController {

    static async testRouteParam() {
        return await Users.getToken(123123);
    }

    @Get('/test/' + TestController.testRouteParam())
    test(@Res() response: Response, @Req() request: Request) {
        return [
            1,
            2,
            3
        ];
    }
}

```

route: /api/test/foo

No failures are given, its just a 404.

**Comment by attilaorosz** [comment]
Decorators are not async, they will not wait for your async function execution.

What is your usecase?

**Comment by pquerner** [comment]
I have a route like this currently:

`/list/:customer(foo|bar)/`. In the future `baz` could be added to the list. So I thought I could craft the regex in runtime. The values can come from a database.

I _could_ simply accept anything in `:customer` and only do the filtering in the action part. I fear it would be too much, and thought when the routes are built it could be done just once. (Otherwise I would have to come up with caching, or a singleton etc..)

**Comment by attilaorosz** [comment]
I would create a startup script where you fetch those values and store them in a global space before importing the controller. That way you can construct the regex before the decorator is executed and just reference it globally.

**Comment by pquerner** [comment]
Makes sense. Thanks for the hint! :)
