### ISSUE TITLE
Add option for auto-prefixing controller mount paths based on location in controllers directory

### ISSUE THREAD

**Issue by ArcanoxDragon** [typestack/routing-controllers#217]
This is a feature request for auto-prefixing mount paths during controller registration. The expected behavior would be to enable an option when registering controllers on the router such that the router would prefix each controller's mount path with its location relative to the controller base directory.

For example, take the following directory structure:

```
server.ts
  controllers/
    admin/
      DashboardController.ts
    user/
      AvatarController.ts
      LoginController.ts
      ProfileController.ts
    IndexController.ts
```

In `server.ts`, when calling `create___Server` or `use___Server` with an array of directory globs in `controllers` and a new option enabled (`autoPrefixRoutes` or similar), `ProfileController` would be automatically mounted with the `/user` prefix without needing to specify it in the `@Controller()` decorator, and likewise with the other controllers in subdirectories. `IndexController` would be mounted at `/`. This new feature would support theoretically unlimited nesting levels, simply using the relative base directory of each controller's module file as the mount prefix.

**Comment by 19majkel94** [comment]
Is this really so hard to paste a few path letters in `@Controller` decorator? Refactoring using regex is also very simple so I don't see big benefits of this feature.

**Comment by pleerock** [comment]
I also don't think its so useful feature

**Comment by 19majkel94** [comment]
A wise man once said: "is efficient, productive and pragmatic solution for developers" 😜 
Why do you think that it's not so useful feature? I thought that you "would recommend to use it for everyone who have big apps" as it reduce manually managing and boilerplate.

**Comment by pleerock** [comment]
Why would I do it? Or do you think if its something directory or filesystem-related then it make things "efficient, productive and pragmatic"? No, everything has its own role, place and effects on "big apps"

**Comment by pleerock** [comment]
There are few problems with this feature. First, I don't find it useful (just like new entities import syntax). Second, why shall we use directory names and not use file names?

**Comment by 19majkel94** [comment]
TBH, I don't find it useful especially in big apps where we should use folder-by-feature approach, not folder-by-tech and jumping through 20 folders and 300 files to fix/develop feature.

**Comment by pleerock** [comment]
Thats right

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions) and someone from the community may be able to help.
