### ISSUE TITLE
question: elaborate on DI example

### ISSUE THREAD

**Issue by HillTravis** [typestack/routing-controllers#309]
Great product, great documentation. I have been able to do everything I needed so far without having to stray any further than your readme, which is amazing.

At the moment, however, I am struggling a bit with how to properly set up the dependency injection. It looks like the readme is a little light on this area. It suggests to use your other product, typedi, but the documentation for that doesn't assume you're using MVC, so I'm not completely sure how to integrate them.

I have a `UserRepository` class, and I'm using [Knex.js](http://knexjs.org/), that needs to be passed into the constructor of that `UserRepository` class. I would prefer to inject the `knex` object into my controller and create the repository in the controller class, but I would also be okay with injecting the `UserRepository` class directly into the controller.

The part where I'm running into trouble is, I'm not sure where to create the `knex` object and add it to the `Container`. Can you elaborate here?

**Comment by 19majkel94** [comment]
I would store the variable with knex instance connected to the store inside e.g. `database.ts` and just use [custom decorator](https://github.com/pleerock/typedi#custom-decorators) to easily inject it into repository or controller constructor.
