### ISSUE TITLE
Obtaining the Action in middleware

### ISSUE THREAD

**Issue by mtrubs** [typestack/routing-controllers#312]
I have a defined middleware similar to the example in the readme:

```
@Middleware({ type: "before" })
export class MyMiddleware implements KoaMiddlewareInterface {

    public use(context: any, next: (err?: any) => Promise<any>): Promise<any> {
        console.log("do something before execution..");
        return next().then(() => {
            console.log("do something after execution..");
        }).catch((error: any) => {
            console.log("error handling is also here..");
        });
    }
}
```

I am wondering if there is a way to get the `Action` that is currently in flight.  So I could say log something akin to `<MyClass>.<myFunction>`.  I think I know how to get at those things if I can get the `Action`, but I cannot seem to figure out if that is obtainable.

**Comment by 19majkel94** [comment]
It's not possible yet. However we are planing to replace custom classic middlewares with enhanced interceptors:
https://github.com/pleerock/routing-controllers/issues/256#issuecomment-322943901

**Comment by mtrubs** [comment]
thanks.  in the meantime is there a way i could re-resolve the `Action` by passing in the `originalUrl` somewhere or something like that?
