### ISSUE TITLE
Question - How does Interceptor know the result from Controller or JsonController?

### ISSUE THREAD

**Issue by Diluka** [typestack/routing-controllers#313]
I have a global interceptor to make sure all json response in unified form. 
But there has a few non-json routes. 
All json routes are under `@JsonController` and others are `@Controller`. 

Could interceptor know which result should respond as json and others not?

Last time I've questioned #192 about `Content-Type`. They have something in common.

**Comment by 19majkel94** [comment]
Yes, you should be able to detect the content type in this way (#192). Is that work?

**Comment by Diluka** [comment]
Only can get `request` content-type, `response` content-type is undefined

**Comment by Diluka** [comment]
If expose `action.isJsonTyped` to `Action` interface will solve this. @19majkel94

**Comment by 19majkel94** [comment]
Yes, there is a proposal of exposing action metadata to interceptors and middlewares. Hopefully we will find some time to implement it soon 😉
