### ISSUE TITLE
How do I receive Form Data?

### ISSUE THREAD

**Issue by IAMtheIAM** [typestack/routing-controllers#314]
There's no @Form decorator, so how does the route controller receive `x-www-form-urlencoded` data and inject it?

**Comment by 19majkel94** [comment]
Use body-parser and you will have that data in body.

**Comment by xujif** [comment]
how to receive  body as buffer
@19majkel94

**Comment by 19majkel94** [comment]
@xujif 
https://github.com/expressjs/body-parser#bodyparserrawoptions

**Comment by 19majkel94** [comment]
@pleerock @NoNameProvided 
Should we implement an option for `@Body` decorator to declare the type of the `body-parser` method to call before action? It's inconvenient to manually do it with `@UseBefore`.

**Comment by IAMtheIAM** [comment]
@19majkel94 Good idea.

**Comment by NoNameProvided** [comment]
Yeah it’s a good idea

**Comment by BruceHem** [comment]
Umm, `@Body` doesn't parse urlencoded by default?

**Comment by BruceHem** [comment]
Btw, express now has its own bodyparser, so I think we should use that, it's 1 less dep to install.

**Comment by 19majkel94** [comment]
@BruceHem nope, just json/text:
```ts
if (actionMetadata.isBodyUsed) {
            if (actionMetadata.isJsonTyped) {
                defaultMiddlewares.push(this.loadBodyParser().json(actionMetadata.bodyExtraOptions));
            } else {
                defaultMiddlewares.push(this.loadBodyParser().text(actionMetadata.bodyExtraOptions));
            }
        }
```

**Comment by alexey-pelykh** [comment]
Any interest in related PR? Or this is by design?

**Comment by durgeshg** [comment]
Any update on above issue? is it fixed? How can I read form url encoded values? Any help on using @UseBefore(bodyParser.urlencoded()) on controller would be helpful.

**Comment by xlxAciDxlx** [comment]
Also hoping for an update to this, ideally for the `@Body()` parameter to include form data automatically.
