### ISSUE TITLE
Add socket.io to my server

### ISSUE THREAD

**Issue by Bouabidi** [typestack/routing-controllers#317]
HI 
I have the following class server and I would like to integrate socket.io. What is the best way to do that? 

Thx :)

```ts
export class Server {

  public app: Express;

  static setupPassport() {
    passport.use(passportLoginStrategy);
    passport.use(passportJwtStrategy);
  }

  constructor() {

    (<any>mongoose).Promise = global.Promise;

    this.app = createExpressServer({
      routePrefix: '/api',
      controllers: [__dirname + '/controllers/*.js'], // register all controller's routes
      authorizationChecker: RoleAuthorization.checkAuthorization,
      currentUserChecker: CurrentUserDecorator.checkCurrentUser
    });
    this.app.use('/api/uploads', express.static('uploads'));

    Server.setupPassport();
    this.app.use(passport.initialize());
  }

  start() {
    mongoose.connect(config.database);

     this.app.use(morgan('combined'));
     this.app.listen(config.port, () => {
      winston.log('info', '--> Server successfully started at port %d', config.port);
    });

  }
}
```

**Comment by NoNameProvided** [comment]
I have never used socket with routing-controllers before, but you can probably use it side by side with [pleerock/socket-controllers](https://github.com/pleerock/socket-controllers/). So here you should just add your setup code as in step 2 here: https://github.com/pleerock/socket-controllers/#example-of-usage, then you can use it anywhere the way described in step 1.

**Comment by MikeDabrowski** [comment]
How to combine createSocketServer with createExpressServer?

**Comment by 19majkel94** [comment]
Just use useExpressServer?

**Comment by MikeDabrowski** [comment]
```
const io = sio(this._app, {
      serveClient: false,
      wsEngine: 'ws' // uws is not supported since it is a native module
    });
    useSocketServer(io, {
      controllers: [__dirname + '\\socket-controllers\\*.ts']
    });
```
where this._app is what came from createExpressServer. It seems to work :D

**Comment by MikeDabrowski** [comment]
However dependency injection doesn't seem to work. When I use some method from class injected into controller's constructor client can no longer connect. No error is thrown.
useContainer is on routing-controllers and socket-controllers. Should I merge it somehow or use only one?

**Comment by MikeDabrowski** [comment]
Import using alias (`as ...`) and it works now. Here's more details:
https://github.com/typestack/routing-controllers/issues/95

**Comment by gruckion** [comment]
@Bouabidi did you resolve the issue you was having? Can we close this issue?

**Comment by rustamwin** [comment]
Try `socket-controllers@next` :)
