### ISSUE TITLE
array of  QueryParam problem

### ISSUE THREAD

**Issue by xujif** [typestack/routing-controllers#320]
if I wan to parse a query param  to  string[] . for example:
```bash
GET /xxx?p=xx&p=yy
```
with router:  
```typescript
@Get('/xxx')
fun(@QueryParam('flags') flags: string[]){
}
```
will be ok, bug When 
```bash
GET /xxx?p=xx
```
will cause an error:
```
Given parameter p is invalid. Value (\"a\") cannot be parsed into JSON.
```

**Comment by 19majkel94** [comment]
Arrays are not supported in this way. You should try to do this this way:
```ts
class FunQueryParams {
 @Type(() => String)
 flags: string[];
}
// ...
@Get('/xxx')
fun(@QueryParams() { flags }: FunQueryParams) {
}
```
However I'm not sure if it works in 0.7.x, if not you have to ping @pleerock to take a look at #315 😉
