### ISSUE TITLE
Can middleware access controller instance?

### ISSUE THREAD

**Issue by vekexasia** [typestack/routing-controllers#327]
I'd like to create a middleware that have access to the controller instance. is that possible?

**Comment by NoNameProvided** [comment]
What is your use case for this and why it cannot be achieved by modifying the request object?

**Comment by vekexasia** [comment]
Lets say i've a Controller  similar to: 

```typescript
@JsonController()
class XXX {
   instanceOfSomething = null;

   @Get('/whatever')
   public async getWhatever() {
      return instanceOfSomething.getWhatever();
   }
 
}
```

Lets say that I want to add a middleware that checks if `instanceOfSomething` was instantiated and if not return an error

**Comment by vekexasia** [comment]
Ofc this is usful cause i've a lot of methods using instanceOfSomething and depends on the "loading" of it.

**Comment by vekexasia** [comment]
Also using a method of controller as a middleware could be helpful.

**Comment by NoNameProvided** [comment]
It is a strange approach what you try to do. Use dependency injection instead and if `instanceOfSomething` needs some time to fully startup after being created then just defer all call on it. (eg return a response what is resolved when `instanceOfSomething` has finished setting up and completed your call.

**Comment by NoNameProvided** [comment]
Yes for that scenario as I advised you should keep track of the internal state of the service inside the service not in a middleware. You can do something like:

```ts
class MyService {
  private ready: Promise<void>;

  constructor() {
    this.ready = this.setupStuff();
  }

  public async anyMethod(): Promise<any> {
    await this.ready;

   // do your stuff here
  }
}
```

**Comment by vekexasia** [comment]
I already keep track of the readyness in the dependency.

I just want to hook up a middleware, within that middleware do

``` 
if (!this.dependency.isReady()) {
  return { success: false, message: 'App  is not ready' }
}
```

Isn't this the whole point of having a middleware? To perform "guards" over real code? 

If right now middleware cannot be coupled to controller classes instances, to me that's a showstoppers unfortunately.

**Comment by NoNameProvided** [comment]
> Isn't this the whole point of having a middleware? To perform "guards" over real code?

Yes it is, but why do you want to return an error response, when your client can wait until your app is ready (I assume your app doesn't need multi minutes setup time.) You just simply resolve the returned promise when the app has been setup and the request can be processed.

Btw you can inject the service into your middleware if you really want to and check for its readiness in the middleware, however as I already said, this seems a wrong design decision. The service itself should keep track of its state and if you decide the send error to requests which comes before then the service should create the error, not the middleware.

**Comment by vekexasia** [comment]
>  (I assume your app doesn't need multi minutes setup time.) 

Can take hours. Don't ask :)

To me it's more clean to have the middleware check dependencies readyness and keep the Controller methods clean of checking the dependencies readyness for each route.

If I had to do that I'd need to duplicate the readyness (and response handling) code for every route. This looks like an antipattern to me.

BTW I dont want to inject the dependency to the middleware. I think i might create a decorator and decorate each method to perform such validation. Still duplicated code but a decorator looks better than code-dumplication to me.

Feel free to share your thoughts.

**Comment by NoNameProvided** [comment]
> Can take hours. Don't ask :)

Wow, that is a long time! So then why don't you solve this at the level of load balancing? Just dont redirect any traffic to the app until it's not ready.

> To me it's more clean to have the middleware check dependencies readiness and keep the Controller methods clean of checking the dependencies readiness for each route.

Your controllers shouldn't check for readiness, the services itself should check it.

> BTW I don't want to inject the dependency to the middleware. I think i might create a decorator and decorate each method to perform such validation. Still duplicated code but a decorator looks better than code-duplication to me.

Yes, you can do that too, but if you do it via a vanilla decorator then you won't have access to routing-controller itself.

> Feel free to share your thoughts.

I am still thinking you should handle this in your service (the way you want, returning a promise for deferred handling or throwing an error.) By trying to check the service readiness outside of the service you break the encapsulation of logic. Your middleware doesn't need to throw, your service needs to throw when it's not ready.

**Comment by vekexasia** [comment]
> I am still thinking you should handle this in your service (the way you want, returning a promise for deferred handling or throwing an error.) By trying to check the service readiness outside of the service you break the encapsulation of logic. Your middleware doesn't need to throw, your service needs to throw when it's not ready.

Oh now I understand what you mean. Yes you're right. But right now the service code, which was not written by me, works that way so I need to adapt until I can fix that.

BTW I would really consider exposing the controller instance to middlewares as this would open up many other options.

> Yes, you can do that too, but if you do it via a vanilla decorator then you won't have access to routing-controller itself.

What do you mean exactly? If I apply my own decorator after the ones from `routing-controller` then `routing-controller` will call my middleware before then actual `route` implementation (which will need to be called by my middleware)

**Comment by sh3d2** [comment]
> Isn't this the whole point of having a middleware? To perform "guards" over real code?

A given middleware shouldnt know anything about other middlewares in the middleware chain. they all should be "self-contained". A controller (the whole routing-controllers actually) acts as a one big middleware. So accessing controller instance (part of one middleware) in other middleware would break the middleware separation principle. Only thing (in express example) that travels between middlewares is the request (and response) object itself.

Can you not just share an instance of your service between controller and a middleware via a DI container (not a best practice, but something to start with).

say, something like (pseudo-code, not tested in any way):

```
export class Middleware implements ExpressMiddlewareInterface { 
   @Inject('my-service')
   protected service; 
 
    use(request: any, response: any, next?: (err?: any) => any): any {
         if(!service.isInitialized()) {
             throw 'service not ready';
         } 
         next();
    }

}

class Controller {

   @Inject('my-service')
   protected service; 

   @Get('/')
   @UseBefore(Middleware)
   anAction(){
          // we want request to reach action only when service is "ready"
   }
}
```

**Comment by tonyxiao** [comment]
@sh3d2 one issue is that the service being injected can change for each request (i.e. depends on currentUser). How would you handle that in routing-controller?
