### ISSUE TITLE
Proposal: New loading API for Subscriptions

### ISSUE THREAD

**Issue by StickNitro** [typestack/routing-controllers#332]
I am currently using routing-controllers in a project which has multiple micro services.  These services are single responsibility units that do not know about each other, for example:

I have a `ClientService` and a `UserService`, the `UserEntity` has a `clientId` property.  In my `ClientService` when I delete a `ClientEntity` I am publishing an event to a message queue (in my case I am using gcloud pub/sub) and the `UserService` subscribes to this queue.

At the moment I am using the `middlewares` option to load my subscribers and register my subscription with the gcloud API.  This feels wrong as this is not the intended use for middlewares and feels somewhat "hacky".

Would it be possible to add a new property to config called `subscriptions`, this would be similar to `middlewares` and would load the collection of subscription classes and new them up allow the constructor to register the subscription

Config would look something like this

```typescript
useExpressServer(app, {
    subscribers: [MyFirstSubscriber, AnotherSubscriber]
}
```

or 

```typescript
useExpressServer(app, {
    subscribers: [__dirname + "/subscribers/**/*{.js,.ts}"]
}
```

The subscriber classes could have a decorator but I don't feel that is necessary, an example class

```typescript
export class MyFirstSubscriber {
    constructor() {
        // here we can register the subscription with whatever event mechanism you are using (gcloud pubsub, MSMQ, or EventEmitter subscriptions)
        // gcloud pub/sub example
        // subscribe("topic-name", "subscription-name", "event-name", this.handler);
    }

    handler(message: {data: any}): Promise<void> {
    }
}
```

Would be great to hear feedback and whether this is both feasible and desirable

**Comment by NoNameProvided** [comment]
I don't see the reason why we need to add subscribers to handle this. You can create a service for this and inject that where-ever you want to use it.

**Comment by 19majkel94** [comment]
I don't know too, DI is the tool you should use rather than subscription option and injecting by RC under the hood or sth 😕

**Comment by StickNitro** [comment]
I guess I didn't look into using DI because each "subscriber" would essentially subscribe to an event (a message bus queue) which it would need to do at startup and then run in the background waiting for messages to be published to the queue.  It is therefore not an instance that is injected into a controller since it would appear that controllers are not "new'ed up" until they are first called (at least thats my experience) and the subscribers would need to be instantiated when the service starts.

**Comment by NoNameProvided** [comment]
You can load them from the container on startup so the subscriptions will be created immediately. Your routes will be still created only if one of its paths are called, but your service can store, process the events in the meantime.

**Comment by pleerock** [comment]
subscribers usually subscribe to some events. If we add "subscriber" into routing-controllers you'll need to subscriber to some *routing-controllers* events. What routing-controllers events are you suggesting to emit in there?
