### ISSUE TITLE
named router and url generator

### ISSUE THREAD

**Issue by xujif** [typestack/routing-controllers#334]
is there any way to name a router?

**Comment by xujif** [comment]
and inject an url generator

**Comment by NoNameProvided** [comment]
> is there any way to name a router?

Do you mean this?

```ts
@Controller('/my-route')
// ...
@Get('/first')
// -> this will generate a route for /my-route/first
```

> and inject an url generator

What do you mean, can you elaborate a little more?

**Comment by xujif** [comment]
yes, bug I wan't generator the url from  other controller or in some view.

**Comment by xujif** [comment]
this is what I want:
```typescript
@Get('/url/:id',{name:'name-router'})
method(@Url() url:Urlgenerator){
   url.to('name-router',{id:123})
}
```

**Comment by xujif** [comment]
or in views:

<#=url.to('name-router',{id:123}) %>

**Comment by xujif** [comment]
Its an feture request.

**Comment by NoNameProvided** [comment]
I dont like naming your routes, there must be better way. Also while this makes sense in templates, for method calls you can already do: 

```ts
@Redirect('/new-path/')
@Get('/old-path/:id')
method() {
   return 'hello';
}
```

A good addition would be to enable: 

```ts
@Redirect('/new-path/:id')
@Get('/old-path/:id')
```

**Comment by 19majkel94** [comment]
Isn't it related to #196?

**Comment by NoNameProvided** [comment]
Yes, it is! I was looking for it but haven't found it. Thanks!

**Comment by xujif** [comment]
@NoNameProvided Redirect did not  work when  I want to pass absolute url to app.

**Comment by NoNameProvided** [comment]
Can you give a little more detail, please?
