### ISSUE TITLE
sendFile in  an action use get Method always return 404

### ISSUE THREAD

**Issue by xihuanhh** [typestack/routing-controllers#340]
`@Controller('/proxy/reports')
   export class ReportPageController {

    @Get('/abc')
    @ContentType('text/html')
    async getImage(@Req()req,@Res()res){
        const REPORT_PATIENT_PATH = Path.join(__dirname, '..', '..', '..', 'report', 'page', 'test.html');//absolutely path 
        res.sendFile(REPORT_PATIENT_PATH);
    }`

when i visit this api  in local  `http://localhost:3000/proxy/reports`
it always return `Cannot GET /proxy/reports/abc`
someone can help me

**Comment by 19majkel94** [comment]
>  If you want to handle the response by yourself, just make sure you return the response object itself from the action.

https://github.com/typestack/routing-controllers#using-request-and-response-objects

**Comment by xihuanhh** [comment]
@19majkel94  thanks, i will try it .
