### ISSUE TITLE
There seems to be an issue having @Render() and using res.redirect - ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by idchlife** [typestack/routing-controllers#341]
Right after I remove decorator problem vanishes.

It seems that headers are attached or something and before method ends - headers are already sent.

res.redirect is the best option I have right now since there can be several redirects and also there is no redirect by default in method, making @Redirect not suitable for situation

edit: unfortunately res.render also gives this error. Hm

edit: actually the problem as I see it:

errors are not handled. I discovered that when I use res.render() express is also getting an NotFoundError and tries to send 2 things: first error, second template render.

Shouldn't there be default error handler or something which will return something, even blank page but not kill express by allowing next() to go further?

**Comment by 19majkel94** [comment]
> If you want to handle the response by yourself, just make sure you return the response object itself from the action.

https://github.com/typestack/routing-controllers#using-request-and-response-objects

**Comment by idchlife** [comment]
@19majkel94 yep, that was my problem with NotFound.

Is there possibility to make error more informative on this case?
Also about express handling multiple sends - it's total mess in my opinion. Nothing to do actually with routing-controllers. So the best case for this issue is request for more informative error, if it's possible

**Comment by purmi** [comment]
Try this
```
@Get('/home')
home(Res() res: any) {
    res.redirect('/someWhare') or res.render('templateUrl', model);
    return res;
}
```
