### ISSUE TITLE
How to catch custom Error in Koa middleware

### ISSUE THREAD

**Issue by Penggggg** [typestack/routing-controllers#342]
> Question

Excuse me for my abrupt questions. How can i catch my custom Error in Koa middleware ? Thanks !

> Versions

- koa: ^2.3.0
- typescript: ^ 2.5.3
- inversify: ^4.5.2
- routing-controller: ^0.7.6

> myError.ts

```
import { HttpError } from 'routing-controllers';

export class MyError extends HttpError {

  public args: any[];
  public operationName: string;

  constructor(operationName: string, args: any[] = []) {
      super( 404 );
      Object.setPrototypeOf(this, HttpReqError.prototype);
      this.operationName = operationName;
      this.args = args;
  }

  toJSON( ) {
    return {
      state: this.httpCode,
      failedOperation: this.operationName
    };
  }

```

> myHandlerMiddleware.ts

```
@injectable( )
export class MyHandlerMiddleware {

  private async use( ctx: Koa.Context, next: ( err?: any ) => Promise< any >): Promise< any > {

    try {
      return next( );
    } catch ( e ) {
      // I cannot catch any error here
      // including the internal error in routing-controllers
      console.log( e );
    }
  }

}
```

> someCtrl.ts

```
@UseBefore( MyHandlerMiddleware )
@JsonController('/test')
@injectable( )
export class someCtrl {
    @Get('/')
    async test( ) {
        throw new MyError('page not found');
    }
}
```

**Comment by NoNameProvided** [comment]
You have to write your own [custom error handler](https://github.com/typestack/routing-controllers#error-handlers) and disable the default one.

**Comment by Penggggg** [comment]
@NoNameProvided Thanks for your reply! 

But the link you gave me above has specific **rules** : Error handlers are specific **only to express**. 

I try the same code, but it is not working in my **Koa** Server.

How should I catch my custom Error in Koa with **my custom middleware** or anywhere ? Thanks !

**Comment by NoNameProvided** [comment]
Sadly I am not familiar with Koa. 😞

**Comment by ownadi** [comment]
Change `return next( );` to `return await next();`. I belive it should fix your problem.

**Comment by bramkoot** [comment]
I ran into the same issue, not sure how to catch your own errors.

**Comment by ownadi** [comment]
@peterschrott @bramkoot 
Have you tried with `await`?
```js
@injectable( )
export class MyHandlerMiddleware {

  private async use( ctx: Koa.Context, next: ( err?: any ) => Promise< any >): Promise< any > {

    try {
      return await next( );
    } catch ( e ) {
      // you should be able to catch exceptions here
      console.log( e );
    }
  }

}
```

**Comment by Nagato-Yuki** [comment]
This should work
`import { Context } from "koa";
import { KoaMiddlewareInterface, Middleware } from "routing-controllers";
import { Inject } from "typedi";

import { ILogger, LoggerService } from "app/frameworks/services/Logger/ILogger";
import { WinstonLogger } from "app/frameworks/services/Logger/WinstonLogger";
import { MiddlewareExecutor } from "app/frameworks/utils/MiddlewareExecutor";

const UNKNOWN_ERROR_CODE = 500;

@Middleware({type: "before"})
export class ErrorResponder implements KoaMiddlewareInterface {

    @Inject(type => LoggerService)
    public logger: ILogger;
    
    public async use(context: Context, next: MiddlewareExecutor) {
        try {
            await next();
        } catch (error) {
            context.status = error.status || error.httpCode || UNKNOWN_ERROR_CODE;
            context.body = {
                status: error.status,
                message: error.message || error.name || "",
            };

            this.logger.error(`${context.status} response: ${context.body}`, { requestId: context.requestId });
            if (context.status === UNKNOWN_ERROR_CODE) {
                this.logger.error(`${error.stack}`, { requestId: context.requestId });
            }
        }
    }
}
`
The trick is this middleware "must" be the first middleware to execute because it has to catch any errors rejected from the chain of `next()` executions from another middlewares and routers.

**Comment by mdelorenzo** [comment]
I have done this and it's working ...

```
@Middleware({ type: 'before', priority: 50 })
export class ErrorHandlerMiddleware implements KoaMiddlewareInterface {

  public async use(@Ctx() context: Context, next: (err?: any) => Promise<any>): Promise<any> {

    return await next().catch(e => {
      log.error('Unknown error', e);
      return context.throw(500, { error: 'Unknown error' }); 
    });
  
  }

}
```

And the creation of the server:

```
const app = createKoaServer({
  middlewares: [ErrorHandlerMiddleware],
  defaultErrorHandler: false,
});
```
