### ISSUE TITLE
Custom Koa global error handler is override with handleError method from KoaDriver

### ISSUE THREAD

**Issue by jsmonkey** [typestack/routing-controllers#344]
Hi,

I'm using default approach for handling application errors in single entry point https://github.com/koajs/koa/wiki/Error-Handling#catching-downstream-errors

But My global error handler is override by this one:
https://github.com/typestack/routing-controllers/blob/master/src/driver/koa/KoaDriver.ts#L290

And this is a real problem, cuz I need my format of error messages wo/ stack and etc for mobile API.

Thanks

**Comment by jsmonkey** [comment]
Sry, I found such option ` defaultErrorHandler: false`, but in this case after custom handling of error I got this warning `UnhandledPromiseRejectionWarning: Unhandled promise rejection`

**Comment by NoNameProvided** [comment]
I am not familiar with Koa, but I think the logic is the same for koa as for express, even if you handle your errors by yourself, you need to catch it in the last place where it's handled. Otherwise, it will bubble up and cause the `UnhandledPromiseRejectionWarning` warning.

**Comment by kunokdev** [comment]
I am getting same issue with UnhandledPromiseRejectionWarning. Even tho I catch and handle error in final middleware, I am using Koa.
