### ISSUE TITLE
@Param default validation

### ISSUE THREAD

**Issue by jsmonkey** [typestack/routing-controllers#348]
Hi,

I found that `This technique works not only with @Body but also with @Param, @QueryParam, @BodyParam and other decorators.` in this validation [docs article](https://github.com/typestack/routing-controllers#auto-validating-action-params).

But by default `@Param('id') id: number` is not validated and accepts `NaN` as value in case of invalid `id`.
There is no validate option for `@Param` decorator, which mentioned in the docs.

So mb you need a fix to be with your library docs.

Thanks.

**Comment by 19majkel94** [comment]
Validation works only with classes annotated with `class-validator` decorators.
Extented normalization of params from path/query + validation for `@Params` and `@QueryParams` will be in 0.8.x - #315 😉

**Comment by jsmonkey** [comment]
Merge request is in opened state since 31 Aug. When will it be released?

**Comment by 19majkel94** [comment]
I have no idea, pleerock is a busy guy. You can use my fork - `@19majkel94/routing-controllers` :wink:

**Comment by timc13** [comment]
@19majkel94 Can you provide an example of how that would work in the new release with the model & controller that I posted above?  I am using `@IsUUID` decorate from `class-validator`...

**Comment by 19majkel94** [comment]
```ts
@JsonController('/users')
class UserController {

  @Get('/:uuid')
  get (@Params() { uuid }: User) {
    // here uuid will be valid, if not it won't enter this method and throw 400 Bad Request
  }
}
```

**Comment by jsmonkey** [comment]
That's the cons of opensource. It's normal to release the product which is not working according to the docs with bugs and no one knows when the fixes will arrive. Anyways thanks for the suggestions.

**Comment by NoNameProvided** [comment]
And the pro of open source is that you don’t have to spend weeks and months writing software that others already has written. Feel free to fork and use you own version anytime, just don’t forget to push your fixes upstream, thanks!

**Comment by clysto** [comment]
just use:
```ts
@JsonController('/users')
class UserController {

  @Get('/:uuid')
  get (@Param('uuid(\\d+)') uuid: number) {
    // if the uuid does't match `\d+` the request will not go into this handler, and express will throw a 404 page.
  }
}
```
