### ISSUE TITLE
function can't not be passed to template

### ISSUE THREAD

**Issue by aditilee** [typestack/routing-controllers#352]
When using the rendering at this moment, the function can't be passed to template.
I would appreciate it if you consider the options.
Otherwise, I think it would be great if you could make the ExpressDriver itself expandable.

**Comment by NoNameProvided** [comment]
What do you mean the function can't be passed to the template? Why would you want to access your render function in your template? You can pass data to the template this way:

```ts
@Get("/users/:id")
@Render("index.html")
getOne() {
    return {
        param1: "these params are used",
        param2: "in templating engine"
    };
}
```

**Comment by purmi** [comment]
``` js
function foo(str) { return "some" + str; }
```
```js
@Get("/users/:id")
@Render("index.html")
getOne() {
    return {
        name: "NoNameProvided",
        gender: "male",
        **myFunc: foo**
    };
}
```

Can't find "myfunc" function  from template.
If turn the option '**class-transformer**' off, it works, But not works '@body etc..'
There is no way to pass function with class-transform by force in SuccessHandler function.
If response.render dorectly, it's possible to pass function, but I wanna pass function by @Render

**Comment by patrickmichalina** [comment]
Can confirm, turning off class-transformer allows lets function pass to the template locals object.
