### ISSUE TITLE
Usage without typedi?

### ISSUE THREAD

**Issue by interphx** [typestack/routing-controllers#354]
As I understand, using `typedi` is the only way to pass dependencies to the controllers, assuming that I keep them DI-framework-agnostic and use constructor injection.

It doesn't always make sense to have a DI framework at all, especially for smaller-scale projects.

Is there a way to manually construct controller instances (injecting the dependencies via constructors and doing all the other necessary setup) and pass them to `routing-controllers`? If not, are there any plans for supporting this use case? It seems like `controllers` option in `createExpressServer` doesn't accept class instances.

**Comment by 19majkel94** [comment]
routing-controllers has built-in DI feature
https://github.com/typestack/routing-controllers/blob/master/src/container.ts#L23

You can also use it with TypeDI or whatever DI lib you want (Inversify) 😉 
If you don't like constructor injection, you can create instances in your controllers, import the instances from another module, use service locator pattern or whatever you want.

**Comment by interphx** [comment]
@19majkel94 I see. Custom containers look like a nice feature.

What I  meant, though, is something along these lines:

```
createExpressServer({
    controllers: [
        new FooController(fooRepository, someService),
        new BarController(someOtherService),
        ...
    ]
})
```

So, constructor injection is precisely what I want, but I want to do it manually.

Are controllers also created using a DI container? If so, I guess I could something like this (with a helper to build this mapping from a list of instances):

```
useContainer({
    get<T>(someClass: { new(...args: any[]): T } | Function): T {
        return {
            'FooController': new FooController(fooRepository, someService),
            'BarController': new BarController(someOtherService)
        }[someClass.name];
    }
})
```

**Comment by 19majkel94** [comment]
I think that this should work, it's container responsibility to resolve and inject dependencies to constructor.
However you should make sure that middlewares, interceptors, etc. will work too.

For me it's better to use TypeDI and call`Container.set` with your prepared and injected controller instances:
https://github.com/typestack/typedi#providing-values-to-the-container
