### ISSUE TITLE
how to use javascript?

### ISSUE THREAD

**Issue by semmy2010** [typestack/routing-controllers#356]
Is this library can provide javascript use, not the use of typescript, I found that when I use javascript, the following code does not work, getOne method parameter `id` becomes `undefined`.

```ts
@Get('/users/:id')
getOne(@Param('id') id: number) {
  console.log(id);
  return 'This action returns user #' + id;
}
```

**Comment by NoNameProvided** [comment]
Please describe your problem in more detail. How do you transpile your app? Decorators (like `@Get`) doesn't supported by NodeJS yet. So how do you run your example code?

**Comment by 19majkel94** [comment]
`id: number` is not a valid JS syntax

**Comment by semmy2010** [comment]
@NoNameProvided 我使用了babel，配置node支持es6和es7的特性，我在.babelrc中配置如下：
`{
    "presets": [
        [
            "env",
            {
                "targets": {
                    "node": true
                },
                "useBuiltIns": true
            }
        ],
        "flow"
    ],
    "plugins": ["transform-decorators-legacy"]
}
`

**Comment by semmy2010** [comment]
@NoNameProvided Routing now no problem, I request localhost: 3000 / users, can be implemented into the following code
`` `ts
@Get ('/ users')
     getAll () {
         return 'This action returns all users';
     }
`` `

I request localhost: 3000 / users / 2, but also to the implementation of the following code.
`` `ts
     @Get ('/ users /: id')
     getOne (@Param ('id') id: number) {
         console.log (id);
         return 'This action returns user #' + id;
     }
`` `

Although the implementation of the getOne code, but the parameter id is undefined, I suspect it is "emitDecoratorMetadata" problem, but I do not know how to configure "emitDecoratorMetadata" in javascript, because I do not use typescript, there is no tsconfig.json file

**Comment by semmy2010** [comment]
@19majkel94 I use flow for type checking.
```js
"flow-bin": "^0.63.1"
```

**Comment by semmy2010** [comment]
I upload code on github "`https://github.com/semmy2010/niuniutu-nodejs-boilerplate`"

**Comment by 19majkel94** [comment]
I can only recommend you to switch from the babel (and it's amusement of configs and presets) and flow to TypeScript - one simple config and everything works out of the box 😉

**Comment by gugadev** [comment]
@19majkel94 I prefer use JavaScript too, I prefer standard ones. Many of projects out there, like [core-decorators](https://github.com/jayphelps/core-decorators) or even [typeorm](https://github.com/typeorm/typeorm) works fine with ES decorators, so, I guess the implementation should be generally the same. Thanks.
