### ISSUE TITLE
Expose local params [feature request]

### ISSUE THREAD

**Issue by davidpaulhunt** [typestack/routing-controllers#357]
I saw that koa support will be dropped and express will become a permanent dependency. Knowing that, it probably makes sense to expose this particular feature of express. I already do it with a custom decorator.

`response.locals` is express' built in method of making variables available throughout the request / response lifecycle. From their docs:
> This property is useful for exposing request-level information such as the request path name, authenticated user, user settings, and so on.

Reference [here](http://expressjs.com/en/4x/api.html#res.locals).

Examples:
```typescript
// all local params
@Get("/account")
getAccount(@Locals(): locals: { [index: any]: any }) {
}

// a single local param
@Get("/account")
getAccount(@LocalParam("client"): apiClient: APIClient) {
}
```

Thoughts, opinions, gripes? 😺

**Comment by 19majkel94** [comment]
I don't know if local isn't designed for template purposes - `express-session` or `express-jwt` store user data in `req.user` by default 😉

**Comment by NoNameProvided** [comment]
There is an open proposal for this, basically, we want to re-implement koas context with type-safety in routing-controllers.

**Comment by davidpaulhunt** [comment]
@19majkel94 locals is described as being used with views, but in the next sentence they say otherwise, it mirrors `app.locals` and can hold variables such as authenticated user. There's no mention of `req.user` since Express 3.x - and we don't use sessions or jwt, we use a form of OAuth2 for API clients. User is just an example.

All of this is to say that express documents an API for setting and using variables in `res.locals` - and if there are decorators for all other types of params, it probably makes sense to add locals for consistency. But that's my opinion 😋 

@NoNameProvided oh, I looked through issues and projects but didn't see anything about it. I'd love to see what's ahead. Are you still planning to drop koa support?

**Comment by NoNameProvided** [comment]
Hmm, yeah I cannot find the complete proposal either, weird I thought I have written it. :D I comment about it is [here][1]. It is for interceptors, but the idea would be the same, having typed context for every route and interceptor, local to themselves (and maybe a global one).

[1]: https://github.com/typestack/routing-controllers/issues/256#issuecomment-326445726

Yes, it's planned still. Basically, there is no reason to use Koa now, in the age of ES6. However now I focus on foundational work for class-validator then class-transformer. Both need some improvement in functionality and performance. Then I can focus on routing-controllers.
