### ISSUE TITLE
Controller method which redirect other controllers, HttpErrorNotFound

### ISSUE THREAD

**Issue by hydexon** [typestack/routing-controllers#358]
Hi, pretty new to this library i found, i loved it because it's in typescript.

So i became in a issue, i saw a lot of your examples there's none about redirecting to other controllers (which renders templates) and mostly are made for RESTful APIs, for example, an login controllers which redirects to the Dashboard controller once the login is successful via Passport.js, and also i'm stuck in other couple of issues.

Since i didn't found an similar example tried this:

```typescript
@Controller()
export class UserController
{
    @Get('/login')
    @Render('login')
    public login_screen(@Req() request: any) 
    {
        let req = <express.Request>request;
        let message_err : string | undefined = undefined; //req.flash('error').length > 0 ? req.flash('error') : undefined;
        
        return {
            Title: "login",
        }
    }

    @Post('/login')
    public login_user()
    {
        console.log('called passport.authenticate');
        passport.authenticate('local', {
            successRedirect: '/dashboard',
            failureRedirect: '/login',
            failureFlash: 'Username or Password ',
            successFlash: 'Welcome to dashboard!'
        } );
    }

    @Get('/logout')
    public logout(@Req() request: any,  @Res() response: any)
    {
        request.logout();
        response.redirect('/login');
    }
}
```

Somehow, routing-controllers redirects the root url, `/` to my login page (`/login`) which i don't even did an mention of the root in my code, i need to know if i should tweak that or not or there's an special way to do it in the routing to do it.

when passport.js successfully or unsuccessfully redirects to other url mentioned in the code i provided, it simply triggers the following output:

```
Error at NotFoundError.HttpError [as constructor] (C:\Develop\dashboard\node_modules\routing-controllers\http-error\HttpError.js:27:23) at new NotFoundError (C:\Develop\dashboard\node_modules\routing-controllers\http-error\NotFoundError.js:20:28) at ExpressDriver.handleSuccess (C:\Develop\dashboard\node_modules\routing-controllers\driver\express\ExpressDriver.js:289:23) at C:\Develop\dashboard\node_modules\routing-controllers\RoutingControllers.js:128:61 at at process._tickCallback (internal/process/next_tick.js:188:7)
```
the startup code is an main class called AppMain which creates the express instance in the following way:

```typescript
    export class AppMain
    {
        public express = createExpressServer(
            {
                //controllers: [ __dirname + "controllers/*.js"],
                controllers: [ UserController, DashboardController ],
                //middlewares: [ LocalAuthFunctions.UnauthLoginRedirect ],
                //authorizationChecker: LocalAuthFunctions.LocalAuthChecker
            }
        );

        constructor()
        {
            this.SetupExpress();
            this.PassportSetup();
        }
```
Thanks you,
Running under Microsoft Windows 10, Node 5.5.1 x64, npm5.5.1, and routing-controllers 0.7.6.

**Comment by 19majkel94** [comment]
> If you want to handle the response by yourself, just make sure you return the response object itself from the action.
https://github.com/typestack/routing-controllers#using-request-and-response-objects

So your actions manipulate the response directly but routing-controllers doesn't know about that, so it tries to handle the value returned from an action, which is undefined, so it assume that the resource hasn't been found.

**Comment by hydexon** [comment]
oh i see, i think i've omitted that part, really sorry about that, i understand everything now. thanks.-

**Comment by yaoyel** [comment]
@hydexon I have  the same problem. Can you tell me how to solve it?

**Comment by hydexon** [comment]
@yaoyel I didn't find any solution with integrating passport.js in routing controllers but i did this, before initializing routing-controllers,just add this line:
```typescript
            this.express.post('/login', passport.authenticate('local', {successRedirect:'/dashboard', failureRedirect:'/login'}));
```

an will work like a charm.

**Comment by NoNameProvided** [comment]
Closing as OP solved his issue.
