### ISSUE TITLE
Async response

### ISSUE THREAD

**Issue by sebastiandelaroche** [typestack/routing-controllers#364]
Hi everyone,

I'm having  a issue when I try to do a response async by example:

```
    @Get('/')
    create(@Req res, @Res res) {
        event.on('response-from-cqrs', () => {
           res.json(<response>);
        });
    }
```

seems that this isn't possible, is there some way the able to do that without do a return?

Thank you so much !

**Comment by 19majkel94** [comment]
You need to wrap it with the promise:
```ts
@Get('/')
create(@Req res, @Res res) {
    return new Promise(resolve => {
        event.on('response-from-cqrs', () => {
            resolve(<response>);
        });
    });
```
Or just handle response by yourself:
> If you want to handle the response by yourself, just make sure you return the response object itself from the action.

**Comment by sebastiandelaroche** [comment]
@19majkel94  The first piece of code worked correctly, thank you very much!

**Comment by stefan--** [comment]
@19majkel94 @NoNameProvided I would expect the below block to work, unless I have totally misunderstood something:

```typescript
@Get('/test/callback')
public async onLoginWithOauthProvider(@Req() request: express.Request, @Res() response: express.Response): Promise<any> {
    return new Promise((resolve, reject) => {
        // Placeholder for some async work, e.g. fetching user data from OAuth service
        setTimeout(() => resolve({ foo: 'bar' }), 1000);
    });
}
```

However, it returns a `404` and complains that `Error: Can't set headers after they are sent.`. I am using `routing-controllers` version `0.7.7`. Thanks for your help.

**Comment by 19majkel94** [comment]
Because when you use `@Res()` decorator, you declare that you take care of handling response to client by yourself. You should use `res.send` along with `return res` to prevent automatic headers sent.

**Comment by stefan--** [comment]
@19majkel94 thanks for your response. If I understand you correctly, it should work like this:
```typescript
@Get('/test/callback')
public onLoginWithOauthProvider(@Req() request: express.Request, @Res() response: express.Response): express.Response {
        setTimeout(() => response.send({ foo: 'bar' }), 2000);
        return response;
}
```

Unfortunately, I am experiencing the same behaviour.

**Comment by stefan--** [comment]
@19majkel94 would be awesome if you could help me out with this. Thanks
