### ISSUE TITLE
class-validator should be a peerDependency

### ISSUE THREAD

**Issue by jdforsythe** [typestack/routing-controllers#369]
Due to it's nature, `class-validator` holds state about the registered classes and their validations.

In our project, we load the models with the validation decorators before `routing-controllers` is loaded. We directly import `class-validator` into the models and use the decorators.

When `routing-controllers` is loaded and the routes are created, it instantiates a **new** copy of `class-validator` to use with the routes, which doesn't contain any of the previously-registered validation rules.

We must load the models ahead of time due to our some of our express/ORM/etc. setup that gets performed before the controller routes are attached.

If I explicitly use:

```ts
import { IsInt } from 'routing-controllers/node_modules/class-validator'
```

in the models, the auto-validation works. Importing the `validate()` function also fails from `class-validator` but works from `routing-controllers/node_modules/class-validator`

**Comment by 19majkel94** [comment]
npm tries to flatten the tree so if you have both `class-validator` and `routing-controllers` as a dependency (with matching versions), you should have only one class-validator inside node_modules.

Making `class-validator` a peer dependency is a bad idea - it's turned on by default so users has to make additional step while installing `routing-controllers`.

You can always use common container to make it work in different parts of your project:
https://github.com/typestack/class-validator/blob/master/src/container.ts

**Comment by jdforsythe** [comment]
package.json
```json
{
  "name": "anything",
  "version": "1.0.0",
  "main": "index.ts",
  "dependencies": {
    "class-validator": "0.8.1",
    "routing-controllers": "0.7.6"
  }
}
```

```sh
$ ls node_modules/routing-controllers/node_modules
drwxr-xr-x 1 0 Feb  8 15:04 class-validator
drwxr-xr-x 1 0 Feb  8 15:04 validator
```

It is installed in `./node_modules` **and** `./node_modules/routing-controllers/node_modules`. This is true whether using npm or yarn.

Wouldn't this be the same as requiring the user to install `reflection-metadata` (which should probably be listed as a peerDependency, too)?

At the very least, it might be helpful to add something to the documentation explaining that this can/will occur if using class-validator outside of routing-controllers.

**Comment by 19majkel94** [comment]
> with matching versions

This is the secret key - how `0.8.1` can work with `0.7.0`? There are two different libraries 😉

**Comment by jdforsythe** [comment]
I'll explain how I arrived here so it makes sense.

We started using routing-controllers and liked the validation stuff, so I started marking up models with it. We have a tslint rule to not allow implicit imports, so:

```ts
import { IsInt } from 'class-validator';
```

throws an error because that package isn't listed in our `package.json` - even though the module will resolve properly.  In order to suppress the message, I simply `npm install`-ed class-validator. Now I see that the version mismatch was causing the two instances.

I would bet that I'm not the last person this happens to. In this case, all objects passed validation without any errors and it took quite a bit of stepping through code to figure it out. It would have been very helpful if I had gotten an error that I had validation turned on but there were zero validation rules registered. Or a quick mention in the docs that a version mismatch between the two `package.json` files could cause this to happen (the class example in the validation section of the docs doesn't show an import - that might be a good place for a note)

In any case, we'll just import from `routing-controllers/node_modules/class-validator` because we definitely won't remember to check the `class-validator` version when bumping the `routing-controllers` version and I don't want to waste this much time again!

**Comment by 19majkel94** [comment]
> In any case, we'll just import from routing-controllers/node_modules/class-validator because we definitely won't remember to check the class-validator version when bumping the routing-controllers version and I don't want to waste this much time again!

This won't solve the problem - when `routing-controllers` makes a major release you still has to dig through the changelog and after `class-validator` upgrade which may change the API you still may need to makes some changes in your code.
