### ISSUE TITLE
class-validator Whitelist not supported

### ISSUE THREAD

**Issue by eagleairplane** [typestack/routing-controllers#373]
Hi,

I am trying to use "class-validator" whitelist feature, and since "routing-controllers" is using class-validator version 0.7.0, and the whitelist feature inroduced in later version, its not supported.

When I tried to manually update the "class-validator" version, other functionality broke and the whitelist feature didn't work either.

Please update the "class-validator" package and fix the breaking changes.

Thanks

**Comment by BogdanUngureanu** [comment]
If you use yarn, you can fix this by using the "resolutions" property in your package.json file.

**Comment by NoNameProvided** [comment]
Now it's updated to the latest `class-transformer` and `class-validator`.
