### ISSUE TITLE
res.sendFile() and Webpack

### ISSUE THREAD

**Issue by circy** [typestack/routing-controllers#376]
Hello.

I would like to send an image file to the frontend, but unfortunately always get a 404 error although the image is present. I packed the whole thing with webpack.

my code: 
`
```
import {
    Controller,
    Get,
    QueryParam,
    Param,
    Res
  } from "routing-controllers";
import * as path from "path";
import { Response } from "express";

@Controller('/media')
export class MediaController {
    @Get("/:file")
    NewDayBookPost(
        @QueryParam('key') key: string,
        @Param('file') file: string,
        @Res() res: Response
    ) {
        const fileName = path.resolve(__dirname, "data", file);
        res.download(fileName);
    }
}
```
`

the error:
Error at NotFoundError.HttpError [as constructor] (C:\projects\gsk-wohnbau\server\node_modules\routing-controllers\http-error\HttpError.js:27:23) at new NotFoundError (C:\projects\gsk-wohnbau\server\node_modules\routing-controllers\http-error\NotFoundError.js:20:28) at ExpressDriver.handleSuccess (C:\projects\gsk-wohnbau\server\node_modules\routing-controllers\driver\express\ExpressDriver.js:289:23) at C:\projects\gsk-wohnbau\server\node_modules\routing-controllers\RoutingControllers.js:128:61 at process._tickCallback (internal/process/next_tick.js:109:7)

Thx :)

**Comment by circy** [comment]
That's my solution, it's not pretty, but that's the way it works.

```
import { Controller, Get, QueryParam, Param, Res } from "routing-controllers";
import * as path from "path";
import { Response } from "express";

@Controller("/media")
export class MediaController {
  @Get("/:file")
  async NewDayBookPost(
    @QueryParam("key") key: string,
    @Param("file") file: string,
    @Res() res: Response
  ) {
    const fileName = path.resolve(__dirname, "data", file);

    try {
      await new Promise((resolve, reject) => {
        res.sendFile(fileName, (err: any) => {
          if (err) reject(err);
          resolve();
        });
      });
    } catch (error) {
      console.log(error);
      throw new Error(error);
    }

    return;
  }
}
```

**Comment by 19majkel94** [comment]
> If you want to handle the response by yourself, just make sure you return the response object itself from the action.
https://github.com/typestack/routing-controllers#using-request-and-response-objects
