### ISSUE TITLE
Koa @Render makes all the other routes fail

### ISSUE THREAD

**Issue by AegoYu** [typestack/routing-controllers#378]
After I add @Render(page) to a particular route, all the other routes (even in the different controllers) render that page as well.

**Comment by NoNameProvided** [comment]
Is there any reason you cannot use Express? There is no difference between to two nowadays with ES6 around. None of us (contributors) is really familiar with Koa, so feel free to propose a fix if you cannot switch to express.

Also, Koa support will be eventually removed in favor of full abstraction, so we can swap the underlying engine.

**Comment by kyle-mccarthy** [comment]
@AegoYu I am getting this issue too when the server starts I can git a route that should return JSON and it works.  When I load a route that renders a template, I correctly see the rendered HTML.  However, when I then go back to a route that will return JSON it shows part of the rendered HTML.

**Comment by zkeyword** [comment]
same

**Comment by nodew** [comment]
https://github.com/typestack/routing-controllers/blob/master/src/driver/koa/KoaDriver.ts#L235

the value `action.renderedTemplate` was putted into a js closure. once the middleware initialized, the view will never changed.

**Comment by iyobo** [comment]
For Koa-specific things like this, the best bet is to use a typescript routing controller made specifically for Koa, like https://github.com/iyobo/koa-ts-controllers.

This particular repo `routing-controllers` is more for express. Koa is and will always be an after-thought and when clashes like this happen, express will take priority.
