### ISSUE TITLE
Can this library do black box testing with itself !?

### ISSUE THREAD

**Issue by Chanasit** [typestack/routing-controllers#379]

**Comment by NoNameProvided** [comment]
Please detail your question a little more. 

If you simply want to test routes and what is the response to it, then you can use some lib like [Chakram](http://dareid.github.io/chakram/).

**Comment by Chanasit** [comment]
Thank for your question.
Yeah I'm looking for mock a http request.
If this library can't mock a routing with itself, so I need a 3rd library like a Chakram right ?

**Comment by NoNameProvided** [comment]
Yes, you need to use a testing lib for that.

**Comment by Chanasit** [comment]
Appreciate for your reply :)
