### ISSUE TITLE
Swagger Support

### ISSUE THREAD

**Issue by jasperblues** [typestack/routing-controllers#382]
Fantastic library. Just started using it with InversifyJS - brilliant that any DI container can be plugged in. 

Does it support Swagger or generating OpenAPI data to produce API documentation? If not, would this feature be interesting?

**Comment by 19majkel94** [comment]
https://github.com/typestack/routing-controllers/issues/11
https://github.com/typestack/routing-controllers/issues/169

**Comment by pairmix** [comment]
Hi there,
What about this feature?
Is https://github.com/epiphone/routing-controllers-openapi the current "official" project?
