### ISSUE TITLE
What is the best process for passing a DB Object?

### ISSUE THREAD

**Issue by EvanBurbidge** [typestack/routing-controllers#386]
In the past i've simply passed my database down through the call stack. But I do quite like this library, I think that trying and getting frustrated trying has caused the answer to evade me. So the way it would work would be.

App starts,
Connects to DB
Db is sent down the chain.

Or do I need to do a different workflow when using this ?

**Comment by NoNameProvided** [comment]
You probably should wrap your logic into services, inject those services into the routes and call them with proper parameters.
