### ISSUE TITLE
Respond to different Accept headers

### ISSUE THREAD

**Issue by et** [typestack/routing-controllers#390]
In #277 there's support to change the response's `Content-Type` dependent on the route.

So
`GET /route/text-html` would return html
`GET /route/text-plain` would return plain text
`GET /route/json` would return json

However, this isn't really the semantically proper way to handle this functionality. Rather, we should be able to trigger off the client's `Accept` header so they can tell us what they want.

e.g.
`Accept: text/html GET /route` would return html
`Accept: text/plain GET /route` would return plain text
`Accept: application/json GET /route` would return json

Unless I'm missing something, I don't believe this is possible with routing-controllers. I believe routing-controllers would need to expose something like `respondTo` to handle this:

e.g.

```js
export class MyController {
  @respondTo('application/json')
  @Get('/users')
  async usersJson() {
    const users = await this.userRepo.all();
    return JSON.stringify(users);
  }

  @respondTo('text/plain')
  @Get('/users')
  async usersText() {
    const users = await this.userRepo.all();
    return users.toString();
  }
}
```

Thoughts?

**Comment by vfaramond** [comment]
It's possible to do it manually today, I'm doing this to return a CSV or a JSON response:

```
@JsonController("/v1/transactions")
export class TransactionController {
  @Inject()
  private transactionService: TransactionService;

  @Get()
  public async find(
    @Res() res: express.Response,
    @HeaderParam("Accept") accept?: string
  ): Promise<string | Transaction[]> {
    const transactions = await this.transactionService.find();

    if (!accept || accept !== "text/csv") {
      return transactions;
    }

    res.setHeader("Content-Type", "text/csv");

    let response = "transactionId,createdAt\r\n";

    response += transactions.map(
      transaction =>
        `${transaction.id},${transaction.createdAt.toISOString()}\r\n`
    );

    return response;
  }
}

```
