### ISSUE TITLE
Best way to pass data from middleware to controller?

### ISSUE THREAD

**Issue by acrocat** [typestack/routing-controllers#396]
I'm putting together an API in which every request can take a range of parameters like offset, limit, fields etc. I'd rather only parse and validate these once and pass them into my controllers, so I'm trying to set up a middleware that'll do it for me. But I can't figure out a good way to pass data from the middleware to the controller. Any good practices for Express?

**Comment by acrocat** [comment]
That's typically how I'd solve this without TypeScript, but with Request being a defined type in Express it's not happy with me attaching non-defined properties to it.

**Comment by 19majkel94** [comment]
```ts
declare global {
  namespace Express {
    interface Request {
      yourProperty: any;
    }
  }
}
```

**Comment by acrocat** [comment]
That works, thanks
