### ISSUE TITLE
How can an instance of a controller be injected into another controller?

### ISSUE THREAD

**Issue by babakyakhchali** [typestack/routing-controllers#403]
Hi
I have a simple json controller like this:
```ts
@JsonController('/test')
export class TestController{
    @Get("/")
    async getAll() {
        return this.testRepo.find();
    }
}
```

now I need to use this controller in another controller to get all Test  objects. currently I'm creating a new instance of TestController class whenever I need it like this:
```ts
@JsonController('/other')
export class OtherController{
    testController:TestController;
    constructor(){
        testController = new TestController();
    }
    @Get("/")
    async getAll() {
        return testController.getAll();
    }
}
```
This is just a simple version of my code to explain the issue. Is it possible to use the same instance created by library using injection?

**Comment by 19majkel94** [comment]
You should extract the common logic into a service that you will later inject to both controller.

**Comment by babakyakhchali** [comment]
yes you are right. but because my logic is simple as storing and retrieving from database I was thinking may be there is a way to use same controller for now.
thanks
