### ISSUE TITLE
Function as role-specifier?

### ISSUE THREAD

**Issue by alexey-pelykh** [typestack/routing-controllers#404]
https://github.com/typestack/routing-controllers/blob/4a56d176db77bc081dfcd3d8550e8433b5bc476e/src/decorator/Authorized.ts#L31

yet

https://github.com/typestack/routing-controllers/blob/4a56d176db77bc081dfcd3d8550e8433b5bc476e/src/metadata/ActionMetadata.ts#L210

and

https://github.com/typestack/routing-controllers/blob/4a56d176db77bc081dfcd3d8550e8433b5bc476e/src/AuthorizationChecker.ts#L7

Please give a hint, what am I missing?

**Comment by Legiew** [comment]
Hey,

we are also affected by this issue. We want to use a custom object as the parameter in the @Authorized decorator. This is possible but we can't use it in the  authorizationChecker function because of the missing type information.
