### ISSUE TITLE
Integration with Passport.js (@Authorized and @CurrentUser decorators)

### ISSUE THREAD

**Issue by gremo** [typestack/routing-controllers#406]
What about providing an integration with [Passport.js](https://github.com/jaredhanson/passport)? Right now, you have to provide your own `authorizationChecker ` and `currentUserChecker`.

It's not that simple for a "new comer" like me, but I managed it. I know that probabily passport can be used with `@UseBefore` middleware, however It would be nice to have integration with `@Authorized` and `@CurrentUser` decorators.

Is this that hard?

**Comment by RiabininDmitriy** [comment]
same question

**Comment by gruckion** [comment]
> same question

Same as which? Would you mind including a url?

I agree, it would be nice, I am looking into this and will get back to you soon. I am currently using my own middleware for JWT authentication. Converted from [this article](https://github.com/gruckion/typescript-rest-api-express-typeorm) referenced in my repo.

I am now looking into using the `@Authorized` decorator but I am concerned about having to write my own middleware to deal with OAuth providers. Which I don't want to have to do.
