### ISSUE TITLE
Injecting next ? Calling middleware manually, need req,res and next.

### ISSUE THREAD

**Issue by appsolutegeek** [typestack/routing-controllers#412]
Hi,

I need to call some middleware manually like so, as you can see, I can inject the request, response which I can pass into the middleware but where do I get "next" from ??

I don't wish to use UseBefore etc.

In a standard express route, you can pass in "req", "res" and "next" but a little confused here..

Currently, I am not able to pass in next, do you just ignore it ?

Anyone know ?

```
  @Post('/login')
  private login(@Req() request: Request, @Res() response: Response) {
    passport.authenticate('local', function(err, user, info) {

    })(request, response, next)
```

**Comment by 19majkel94** [comment]
next is not injectable, it's called automatically, you should use passport in middleware, not in route handler logic

**Comment by appsolutegeek** [comment]
Agreed, that's what I decided to do. Thanks
