### ISSUE TITLE
Allow calling next(err) when an error occurs while streaming a response.

### ISSUE THREAD

**Issue by bvanreeven** [typestack/routing-controllers#416]
We are using routing-controllers with Express to stream a response to the client (see example code below). When an error occurs in the read stream that we're piping into the response, we want to abort the request, so that the client knows it is not a valid response.

According to [the Express documentation](https://expressjs.com/en/guide/error-handling.html#the-default-error-handler), when an error occurs after the headers have been sent, we should call `next(err);` so that the default Express error handler can take care of aborting the request.

However, as far as I can tell there is currently no way to obtain the `next` function in routing-controllers. There is no `@Next() next` param decorator for example.

How should we proceed? What should we write instead of `next(err);` in the following example code?

```typescript
@Controller
export class StreamController {
    @Get("/stream")
    public getStream(@Req() req: Request, @Res() res: Response) {
        const readStream = ...;

        readStream.on("error", (err) => {
            console.log("Error in stream:", err.message);
            // According to Express documentation, should call `next(err);` here.
        });

        readStream.pipe(res);

        return res;
    }
}
```

**Comment by 19majkel94** [comment]
```ts
@Controller()
export class StreamController {
    @Get("/stream")
    public getStream(@Req() req: Request, @Res() res: Response) {
		return new Promise((resolve, reject) => {
          const readStream = ...;

          readStream.on("error", (err) => {
              console.log("Error in stream:", err.message);
              reject(err);
          });

		  readStream.on("finish", () => {
            resolve(res);
          });

          readStream.pipe(res);
    }
}
```

**Comment by bvanreeven** [comment]
Express itself destroys the request socket when an error occurs after the headers have been sent: https://github.com/pillarjs/finalhandler/blob/024f493418f62a59592a98f07b23b265092c1006/index.js#L128

So a workaround is to inject the request using the `@Req() req` param decorator and then calling `req.socket.destroy()` when a stream error occurs.

However, instead of having to copy-paste code from Express, I would like routing-controllers to handle this for me, or be able to use the default Express behavior.

**Comment by 19majkel94** [comment]
For now there's no way to call `next(err)` as `next()` is called automatically and there's no `@Next()` decorator.

**Comment by bvanreeven** [comment]
I just discovered that routing-controllers has support for returning a stream from an action and will then make sure the stream is piped into the response. I think it makes sense that routing-controllers also provides the error handling in this case, as it abstracts over the "raw" Express API.

I made a pull request that enables error handling of streams returned from routing-controller actions in the Express driver: #418
