### ISSUE TITLE
Update routing-controllers class-validator dependency to latest (0.9.1)

### ISSUE THREAD

**Issue by rmuchall** [typestack/routing-controllers#424]
Please could you update the class-validator dependency to the latest version (0.9.1)?
If I use the latest version (0.9.1) and routing-controllers is still using the older version (0.8.5) then oddities occur as described in this issue by @NoNameProvided 
https://github.com/typestack/class-validator/issues/166

EDIT: should class-validator be a peer dependency?

As always, thanks for your awesome efforts guys :)

**Comment by MardariG** [comment]
Last publish 5 months ago, it seems abandoned.

**Comment by FSM1** [comment]
@19majkel94 I tried doing the same (created my own routing-controllers package on npm), and after `npm dedupe` I now only have one version of class-validator installed in the project (0.9.1), but I am still getting the error message about no metadata. Any suggestions on what else I can try?

**Comment by MardariG** [comment]
> @19majkel94 I tried doing the same (created my own routing-controllers package on npm), and after `npm dedupe` I now only have one version of class-validator installed in the project (0.9.1), but I am still getting the error message about no metadata. Any suggestions on what else I can try?

You can try mine clone: [https://www.npmjs.com/package/@mardari/routing-controllers](url)
Just updated package.json

**Comment by FSM1** [comment]
@MardariG will give it a try... are you using your version as part of the TypeORM stack?

**Comment by MardariG** [comment]
> @MardariG will give it a try... are you using your version as part of the TypeORM stack?

Sorry I deleted the comment, didn't noticed **19majkel94** has published already another version;

[https://www.npmjs.com/package/@mardari/routing-controllers](url)

I'm using it in [https://github.com/w3tecch/express-typescript-boilerplate](url) boilerplate, as with official version validation of @Body is not working.

**Comment by FSM1** [comment]
@MardariG I had also done the exact same with my package, and now I have replaced with your version of Routing-Controllers and I still get the metadata error log and no validation happens. 

> Yes, I'm using it in https://github.com/w3tecch/express-typescript-boilerplate boilerplate, as with official version validation of @Body is not working.

I am using the exact same boilerplate and not having any luck with the validation. Any ideas what else I could look at?

**Comment by MardariG** [comment]
**FSM1** can you share your error trace?

**Comment by FSM1** [comment]
@MardariG not getting any errors. I just get a console log from class-validator that no metadata has been found, and a response of an empty ValidationErrors array, even though the request is invalid.

```
    @Post()
    @HttpCode(201)
    public async create(@Body({validate: true}) user: User): Promise<User> {
        this.log.info('Validating request');
        const valid = validateSync(user);
        console.log(valid);
   ......
```

the following is logged to console when executing:
```
No metadata found. There is more than once class-validator version installed probably. You
 need to flatten your dependencies.
info: [api:controllers\UserController] Validating request
No metadata found. There is more than once class-validator version installed probably. You
 need to flatten your dependencies.
[]
```

**Comment by MardariG** [comment]
**FSM1**  can you share your ```package.json``` also ?

**Comment by FSM1** [comment]
```
{
  "name": "MoleculeRestApiServer",
  "version": "1.0.0",
  "description": "Molecule API server built using NodeJS, MongoDb, Mongoose, Typegoose",
  "main": "src/app.ts",
  "scripts": {
    "start": "nps",
    "test": "npm start test",
    "build": "npm start build",
    "presetup": "yarn install",
    "setup": "npm start config && npm start setup.script"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "keywords": [
    "NodeJS",
    "TypeScript",
    "express",
    "boilerplate",
    "skeleton",
    "starter-kit",
    "mongoose"
  ],
  "homepage": "https://gitlab.com/linumlabs/molecule-sandbox/Api",
  "author": "Linum Labs - Michael Yankelev",
  "dependencies": {
    "@mardari/routing-controllers": "^0.7.9",
    "bcrypt": "3.0.1",
    "body-parser": "^1.18.2",
    "chalk": "^2.3.0",
    "class-validator": "0.9.1",
    "commander": "^2.11.0",
    "compression": "^1.7.1",
    "copyfiles": "^2.0.0",
    "cors": "^2.8.4",
    "dataloader": "^1.3.0",
    "dotenv": "6.0.0",
    "event-dispatch": "^0.4.1",
    "express": "^4.16.2",
    "express-basic-auth": "^1.1.3",
    "express-graphql": "^0.6.11",
    "express-status-monitor": "^1.0.1",
    "figlet": "^1.2.0",
    "glob": "^7.1.2",
    "graphql": "^0.13.0",
    "helmet": "^3.9.0",
    "jsonfile": "5.0.0",
    "jsonwebtoken": "^8.3.0",
    "lodash": "^4.17.4",
    "microframework-w3tec": "^0.6.3",
    "mongodb-uri": "^0.9.7",
    "mongoose": "^5.3.4",
    "mongoose-lean-virtuals": "^0.3.1",
    "morgan": "^1.9.0",
    "nodemon": "^1.12.1",
    "nps": "^5.7.1",
    "nps-utils": "^1.5.0",
    "path": "^0.12.7",
    "reflect-metadata": "^0.1.10",
    "request": "^2.83.0",
    "serve-favicon": "^2.4.5",
    "supertest": "^3.0.0",
    "swagger-ui-express": "4.0.1",
    "ts-node": "7.0.1",
    "tslint": "^5.8.0",
    "typedi": "0.8.0",
    "typegoose": "^5.4.1",
    "typescript": "3.0.3",
    "uuid": "^3.3.2",
    "winston": "3.1.0"
  },
  "jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/test/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "testEnvironment": "node",
    "setupTestFrameworkScriptFile": "./test/unit/lib/setup.ts"
  },
  "license": "MIT",
  "devDependencies": {
    "@types/bcrypt": "^2.0.0",
    "@types/bluebird": "^3.5.18",
    "@types/body-parser": "^1.16.7",
    "@types/cors": "^2.8.1",
    "@types/dotenv": "^4.0.2",
    "@types/express": "^4.0.39",
    "@types/faker": "^4.1.2",
    "@types/figlet": "^1.2.0",
    "@types/helmet": "0.0.41",
    "@types/jest": "23.3.2",
    "@types/jsonwebtoken": "^7.2.8",
    "@types/lodash": "^4.14.80",
    "@types/mongoose": "^5.2.19",
    "@types/morgan": "^1.7.35",
    "@types/nock": "^9.1.3",
    "@types/request": "^2.0.8",
    "@types/serve-favicon": "^2.2.29",
    "@types/supertest": "^2.0.4",
    "@types/uuid": "^3.4.3",
    "cross-env": "^5.1.1",
    "faker": "^4.1.0",
    "jest": "23.6.0",
    "mock-express-request": "^0.2.0",
    "mock-express-response": "^0.2.1",
    "nock": "10.0.0",
    "ts-jest": "23.10.1"
  }
}
```

**Comment by MardariG** [comment]
**FSM1** Strange, using this [https://github.com/w3tecch/express-typescript-boilerplate](url) template, all I have to change is replacing official ```routing-controllers``` with mine ```@mardari/routing-controllers``` .
That's it, and @Body()  is validated. Maybe there is a problem with models maybe other settings idk. 

You can clone a clean project and see what is different from yours.

**Comment by FSM1** [comment]
I have changed quite a bit from the original boilerplate (ripped out TypeORM and using Mongoose + Typegoose instead).

Class-validator should be quite agnostic to that though. I am using other annotations throughout the project without issue.

Think I am just going to give up on the W3tecch boilerplate and move on over to Nest.js, hopefully with a lot less issues and a bit more support.

thanks for the help @MardariG
