### ISSUE TITLE
Deployment best practices

### ISSUE THREAD

**Issue by MikeDabrowski** [typestack/routing-controllers#426]
Its my second app made with this awesome library and again I'm wondering how to properly deploy it to prod server. So far I moved source code to the server, `npm install` it and then `ts-node server.js`. I tried webpack it to one bundle, server starts but no requests can be made and no sockets respond. 

What would you recommend for deployment (mostly unix server with nginx, but anything is possible).

**Comment by acuntex** [comment]
We use a docker image for the node server and a nginx proxy (also a docker container) with an upstream to this docker image.
For the docker image we have a docker registry which we use to push the image. On the server we can simply pull it.

Works great.

**Comment by 19majkel94** [comment]
While building a docker image you just run `tsc` and when the container is started, it just run `node ./build/app.js`.

**Comment by MikeDabrowski** [comment]
So, ditching docker, just `tsc` and `node app.js` ? Well that was simple... :D

**Comment by albertorm95** [comment]
Hello, I'm doing `tsc` and the running `node ./build/app.js` but I get `Cannot GET /api/auth/getPreferencesData` so it seems that the endpoints are not being exposed:

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./build",
    "strict": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
  }
}
```
