### ISSUE TITLE
Is this project still under active development?

### ISSUE THREAD

**Issue by GBeushausen** [typestack/routing-controllers#436]
Hi,

Is this project still under active development or is it abandoned? Thanks.

**Comment by 19majkel94** [comment]
This project is not abandoned but all of the core contributors have also other projects under his wing and not enough time for open source 😞

**Comment by GBeushausen** [comment]
Thanks. So if i started a new enterprise application, would it be safe enough to use routing-controllers, or might there be a chance it will get abandoned or not the needed support in the future, so it's better to look for another solution?

**Comment by 19majkel94** [comment]
For enterprise applications I would use Nest Framework by @kamilmysliwiec 😉 
https://github.com/nestjs/nest
