### ISSUE TITLE
Resource Owner on Authorized Roles

### ISSUE THREAD

**Issue by MarkMatute** [typestack/routing-controllers#441]
Propper implementation of allowing only resource owner, ex. **Owner of picture**

**Comment by 19majkel94** [comment]
Could you show us how the API should look like?

**Comment by 19majkel94** [comment]
Ok, but what do `resolvers` do? What is it's API, how it should be called?

**Comment by MarkMatute** [comment]
the api is for updating user profile.
the concept is if the **Logged In User** owns the **Profile Being Updated** then only it will be updated.

**Comment by MarkMatute** [comment]
**Resolvers** on my code will be called inside the **authorizationChecker** to run logic check the id in the context and the current user.

**Comment by MarkMatute** [comment]
[Here is the file](https://github.com/SimpleIdeaLabs/balls/blob/master/src/helpers/AuthChecker.helper.ts)

**Comment by 19majkel94** [comment]
So basically, as it's not called automatically, all you need is an `extra` property of `@Authorized` decorator option to store arbitrary data that you can access in custom authChecker function?

**Comment by MarkMatute** [comment]
yes correct, it works but its more like a hack, is there a better way to implement this with the routing-controllers?

I tried to leverage this **export declare function Authorized(role: any): Function;** overload, but im getting array on the authChecker
