### ISSUE TITLE
When is 0.7.8 going to be published on npm?

### ISSUE THREAD

**Issue by geomC** [typestack/routing-controllers#442]
I tried installing the package by pointing to this repos, which failed.
I would like to use new features like the `toJSON` method of custom `HttpError`s.

**Comment by 19majkel94** [comment]
ping @NoNameProvided 	😉

**Comment by geomC** [comment]
Thanks @19majkel94, but how to? Github removed private messages.

**Comment by rustamwin** [comment]
@geomC on twitter

**Comment by atlas1119** [comment]
When is 0.7.8 going to be published on npm? I need it
