### ISSUE TITLE
@param decorator doesn't have options parameter

### ISSUE THREAD

**Issue by msudgh** [typestack/routing-controllers#443]
In [link](https://github.com/typestack/routing-controllers#method-parameter-decorators), `@Param` decorator doesn't have `options` parameter in it's signature. is it wrong typings implementation or type fault?

**Comment by 19majkel94** [comment]
https://github.com/typestack/routing-controllers/pull/315/files#diff-2eb9d11171d5f3018e080f484fc1814a

**Comment by msudgh** [comment]
@19majkel94 Thanks.
