### ISSUE TITLE
Use existing global express.js middelwares "before"?

### ISSUE THREAD

**Issue by the-daniel-rothig** [typestack/routing-controllers#447]
The documentation seems to suggest that

```
let app = createExpressServer({
   controllers: [UserController]
}); // creates express app, registers all controller routes and returns you express app instance
app.use(compression());
```

is equivalent to applying
```
@UseBefore(compression())
```

to all controllers or actions. However, middlewares injected with `app.use(...)` are applied *afterwards*.

How can I use an existing middleware globally and have it applied *before*? My particular use case is `express-ejs-layouts`

**Comment by 19majkel94** [comment]
`useExpressServer` is your friend

**Comment by the-daniel-rothig** [comment]
Ah indeed it is - thank you, I'm glad that there is a solution to the problem :-) 

I'd still say the documentation is a bit misleading on this point, though.
