### ISSUE TITLE
Pattern for conditional redirect?

### ISSUE THREAD

**Issue by the-daniel-rothig** [typestack/routing-controllers#448]
Hi

I want for my paths to have control flow logic, e.g.
- If a user navigates to `/` but is unauthenticated (no session set), they should be redirected to /login
- otherwise, a server-side rendered view should be returned

Another example
- If a user posts a valid form, a server-side rendered success view should be rendered
- If a user posts an invalid form, the server-side rendered form should be re-rendered with some messaging at the top

I found these kinds of conditional responses pretty universal in server-side rendered web apps and as far as I have seen this logic is usually done within the controller, but I haven't seen how this is done in the context of `routing-controllers`. Any help would be appreciated!

**Comment by 19majkel94** [comment]
just use middlewares :)
