### ISSUE TITLE
Not support Template literals ?

### ISSUE THREAD

**Issue by Himself65** [typestack/routing-controllers#459]
when I use
```ts
private name = 'article'
@Get(`/${this.name}s`)
  async getAll () {
    return Article.find((err, docs) => {
         ...
    })
  }
```
then I post it but return 404

but I change `@Get(`/${this.name}s`)` to `@Get(‘/articles’)`

that situation  disappear

**Comment by 19majkel94** [comment]
How it can even compile and run? `this` is not available outside method classes in decorators as they are static in Typescript.

**Comment by Himself65** [comment]
@19majkel94 thanks
