### ISSUE TITLE
Using typedi

### ISSUE THREAD

**Issue by impzero** [typestack/routing-controllers#462]
How can I integrate typedi with my controllers? For example let's say I would like to set a redis client instance in my typedi container, then how can I use the redis client instance? The example in the README is very broad and unclear for me.

**Comment by fr3fou** [comment]
Any news?

**Comment by 19majkel94** [comment]
Just use `Container.set` to provide a redis instance, then place `@Service` above the controller class, place proper `@Inject` in constructor/class field and remember about `useContainer(Container)`
