### ISSUE TITLE
Include controller in another controller

### ISSUE THREAD

**Issue by ajcerejeira** [typestack/routing-controllers#463]
Good afternoon, and thank you for this great library!

I'm creating a simple JSON API to deal with car accidents with the following routes:
- `/accidents/:id` - details of the accident
- `/accidents/:id/vehicles` - list of vehicles on the accident
- `/accidents/:id/vehicles/:vehicle` - vehicle details

I would like to have separate controllers for `accidents` and `vehicles` and be able to "include" the `VehicleController` into `AccidentController`:

```typescript
@JsonController("/vehicles")
export class VehicleController {
  @Get("/:id")
  public detail(@Param("id") id: string) {
    ...
  }
}
```

Is it possible for this controller to be somehow included in another controller, something like:

```typescript
@JsonController("/accidents")
export class AccidentController {
  @Get("/:id")
  public detail(@Param("id") id: string) {
     ...
  }

  @Include(VehicleController)
}
```

Otherwise I'll end up with only one big controller (`AccidentController`), defining subroutes.

With the best regards

**Comment by carmanchris31** [comment]
You don't want `/vehicles` to route to the VehicleController then, right? Only `/accidents/:id/vehicles`? 

In that case you can simply define that as your controller's base path and the params will cascade into the routes:

```js
@JsonController("/accidents/:id/vehicles")
export class VehicleController {
  @Get("") // Don't add a slash here or a trailing slash in the url will be required
  public vehicles(@Param("id") id: string) {
    // list of vehicles in accident :id
  }

  @Get("/:vehicle")
  public detail(@Param("id") id: string, @Param("vehicle") vehicle: string) {
    // detailed info about vehicle :vehicle in accident :id
  }
}
```
