### ISSUE TITLE
express async/ await controller error handling

### ISSUE THREAD

**Issue by devmattrick** [typestack/routing-controllers#464]
When a request handler in a controller uses an async function, the request will error without being properly passes on to the handlers (using the `next()` function). This can break middleware that run after the request (for example, logging).

Just as a small example, if you have a handler as follows:
```typescript
  @Post("/login")
  private async getLogin(
    @BodyParam("email") email: string,
    @BodyParam("password") password: string,
  ) {
    await this.login(email, password);
  }
```

If `await this.login(email, password);` throws an error, it won't properly pass on the request to future middleware.

The way I've seen most people recommend handling this is to wrap the handler in an ["async handler"](https://itnext.io/using-async-routes-with-express-bcde8ead1de8) which will catch errors and call `next`, but that's not really possible when its inside of a controller. The other option would to wrap the entire thing in a try/ catch, but this seems like a poor solution, in my opinion, as it would be required on every route that uses an async function.

I think it might be a good idea for routing-controllers to handle async functions by default in controller handlers.

**Comment by jondot** [comment]
Did you actually reproduce this? I'm evaluating this library, and that's one of the first pitfalls I wanted to check. Looks like it works properly though.

**Comment by devmattrick** [comment]
@jondot it may be that [Express 5](https://github.com/expressjs/express/issues/2259) handles errors properly in async functions now, but if you are still on Express 4 perhaps routing-controllers quietly resolved this issue?

**Comment by peter-donovan** [comment]
I am actually extremely surprised that routing-controllers does not really even mention much at all about async/await. I can't even seem to get simple things to work such as setting a session within a controller. I get "Cannot set property 'uid' of undefined" when trying to set a session via express-session. Regardless, there seems to be zero support for async/await.

Is this project still maintained? I can't really tell... It looks like it has stopped being maintained? If it cannot handle the most simple of things then how it is any better than regular express? All it seems to do is add unnecessary complexity to a node.js application without providing anything besides syntactic sugar (that doesn't even work correctly).

I really hope that I am missing something. It does work really well with `class-validator` and such, which is really amazing. Other than that, the library feels outdated and seemingly unmaintained.

**Comment by attilaorosz** [comment]
As @jondot mentioned, async/await should work properly. @devmattrick Could you try the latest version if still relevant?

**Comment by devmattrick** [comment]
@attilaorosz I appreciate the follow up but this issue is no longer relevant for me 😅 Feel free to close, thanks!
