### ISSUE TITLE
Pass array of middlewares to @Usebefore

### ISSUE THREAD

**Issue by geomC** [typestack/routing-controllers#466]
Hey there! Thanks for this awesome repo.

I would like to bind multiple multiwares to an action using `@UseBefore`.
Since the function does not accept an array, I tried to state two middelwares like:
```typescript
@Post('/myroute')
@UseBefore(someMiddleware)
@UseBefore(anotherMiddleware)
public async post(@Req() req, @Res() res, @Body() body): Promise<any> {
   // ...
}
```
It seams like only the last middleware stated using `@UseBefore` gets executed.

Will this be supported in the future?

Regards
Sascha

**Comment by 19majkel94** [comment]
```
export function UseBefore(...middlewares);
```
Use the spread operator

**Comment by geomC** [comment]
thanks! works like a charm
