### ISSUE TITLE
Can the middleware hijack the controller object globally?

### ISSUE THREAD

**Issue by zhump** [typestack/routing-controllers#469]
I want to inject some httpRequset objects into the global controller, because the global middleware can't bind the controller object, the code needs to write once for each controller, is there a more elegant way?

userController.ts
```
@UseBefore(LoggingMiddleware.bind(this))
export class userController {
   public httpReq: any
}

```

LoggingMiddleware.ts
```
import { Middleware, ExpressMiddlewareInterface } from "routing-controllers";
export default function LoggingMiddleware(request: any, response: any, next?: (err?: any) => any): any {
  let traceId = request.traceId = 'TC' + String(Date.now()).slice(-7)
  let _this = this[Object.keys(this)[0]]
  _this.prototype.httpRequest = request
  next();
}
```

**Comment by 19majkel94** [comment]
@zhump 
`this` is not available during decorators evaluation - it refers to window/global.
Turn on `noImplicitThis` and you will get an error.
