### ISSUE TITLE
Support mixin `@Ctx`

### ISSUE THREAD

**Issue by Himself65** [typestack/routing-controllers#471]
example

```js
// import something
const app = new Koa() 
app.use(ctx=>{
 ctx.foo = 123
})

class Example {
  @Get('/xxx')
  foo(@Ctx() ctx) {
    console.log(ctx.foo) // why undefined ???
  }
}

useKoaServer(app, {
  controllers:  [Example]
})
```

**Comment by crycime** [comment]
I also have this problem.

**Comment by Himself65** [comment]
@crycime 
this repository has abandoned I think. so I had dropped it.

**Comment by hendratommy** [comment]
Mine is working fine

**Comment by iyobo** [comment]
Just use this instead https://github.com/iyobo/koa-ts-controllers.
It's very similar to routing-controllers, but made specifically for Koa, and supports versioning.

Koa is a 2nd class citizen for this project.
