### ISSUE TITLE
ValidateNested not working

### ISSUE THREAD

**Issue by matzmz** [typestack/routing-controllers#483]
I've the following entities:
```ts
export class SubDTO {

   @IsNotEmpty()
   name: string;

   @IsOptional()
   description: string;

   @IsOptional()
   other: string;
}

export class MainDTO {
   @IsNotEmpty()
   identifier: string;

   @IsBoolean()
   active: boolean;

   @IsOptional()
   @ValidateNested()
   @Type(() => SubDTO)
   inner: SubDTO;
}
```

managed by the following controller
```ts
@JsonController()
export class MainController {

   @Post("/main")
   async create(@Body({ validate: true, required: true }) main: MainDTO) {
      console.log(main);

      return main;
   }
}
```
posting this body **I get an error** (it's a right behaviour). 
```json
{
	"identifier": "lll11",
	"active": true,
	"inner": 1
}
```
nestedValidation: nested property inner must be either object or array

If I post these bodies **I don't get errors**  (I expect to get an error)

```json
{
	"identifier": "lll11",
	"active": true,
	"inner":  {}
}
```
```json
{
	"identifier": "lll11",
	"active": true,
	"inner":  { "description": "descr"}
}
```

It seems that decorators belonging to nested class are ignored. Do you have any idea ?

**Comment by matzmz** [comment]
I found the problem, I've installed two version of **class-transformer** in the past I got a similar problem with **class-validator**

**Comment by vs4vijay** [comment]
Whats the solution for this now? I am having the same problem.
