### ISSUE TITLE
@Authorized and @UseBefore together

### ISSUE THREAD

**Issue by vikasgarghb** [typestack/routing-controllers#489]
Has anyone tried to use `@Authorized` and `@UseBefore` together? I have been trying to use them both but looks like `@UseBefore` overrides `@Authorized` and `@Authorized` never gets called.

app.ts
```
expressConfig, {
  authorizationChecker: Container.get(AuthChecker).check,
  controllers: [Foo],
  defaultErrorHandler: false,
  middlewares: [someMiddleware],
}
```

FooController.ts
```
@Authorized()
export class Foo {
  @UseBefore(someMiddleware())
  function foo() {
    // do something
  }
}
```

**Comment by jiemurat** [comment]
What your `someMiddleware()` is returning?
May be, you should write `@UseBefore(someMiddleware)`.

**Comment by rustamwin** [comment]
Did you resolve your issue?

**Comment by vikasgarghb** [comment]
Yes, I was able to solve it by using `@UseBefore` and using express authorizer middleware. I had to do away with `@Authorized`.
