### ISSUE TITLE
Multiple controllers called if routes overlap

### ISSUE THREAD

**Issue by ninja-** [typestack/routing-controllers#494]
If two routes are overlapping, for example

```js
@Get('/debug')
method() {}
@Get('/:id')
someMethod() {}
```

both will be called, instead of only one.
This can cause unexpected behaviour and hard to debug errors like 'Headers already sent'...

**Comment by wallopthecat** [comment]
Slap some regex on that `:id` `@Get('/:id') -> @Get('/:id([0-9]+)')`
