### ISSUE TITLE
Anonymous middleware make it difficult to debug in express

### ISSUE THREAD

**Issue by saulotoledo** [typestack/routing-controllers#505]
Express allows debugging by setting `DEBUG=express:*` as described in [https://expressjs.com/en/guide/debugging.html](https://expressjs.com/en/guide/debugging.html).

After activating the debug messages, it is possible to see the middleware being called in the console as, for example:

```bash
express:router dispatching GET /v1/users/?page=1&limit=100 +3s
express:router query  : /v1/users/?page=1&limit=100 +2ms
express:router expressInit  : /v1/users/?page=1&limit=100 +2ms
express:router corsMiddleware  : /v1/users/?page=1&limit=100 +0ms
express:router <anonymous>  : /v1/users/?page=1&limit=100 +1ms
express:router <anonymous>  : /v1/users/?page=1&limit=100 +0ms
express:router <anonymous>  : /v1/users/?page=1&limit=100 +14ms
```

The previous example is from an application with routing-controllers and express. The anonymous functions are three middleware registered in the application by routing-controllers. Note that it is hard to know which middleware were triggered.

That happens because routing-controllers use anonymous functions as wrappers. We should be able to see the proper names in such logs.

**Comment by saulotoledo** [comment]
@pleerock

**Comment by GabeKuslansky** [comment]
You can achieve this functionality by registering middleware that logs this information. Example:

```
const app = createExpressServer({
  middlewares: [ResponseTimeLogger],
  controllers: [controllers]
});

@Middleware({
  type: "before"
})

export class ResponseTimeLogger implements ExpressMiddlewareInterface {
    use(req: Request, res: Response, next: NextFunction): void {
      const startTime = process.hrtime();
      res.on('finish', () => {
        const elapsedTime = process.hrtime(startTime);
        const elapsedTimeInMs = Math.round(elapsedTime[0] * 1000 + elapsedTime[1] / 1e6);
        console.log(`express:router ${req.method} ${req.path} +${elapsedTimeInMs}ms`);
      });
      next();
    };
  }
}
```
