### ISSUE TITLE
fix: decorator "SessionParam" is missing

### ISSUE THREAD

**Issue by janaszer** [typestack/routing-controllers#519]
Hi. I think you forgot to reexport SessionParam decorator in your main index.ts file. 
Session decorator is in place and there should be SessionParam as well
https://github.com/typestack/routing-controllers/blob/master/src/index.ts#L52

But following piece of code gives me error:
import { Session, SessionParam } from 'routing-controllers';

"routing-controllers" has no exported member 'SessionParam'

**Comment by drdreo** [comment]
Same happens for me

**Comment by yinxulai** [comment]
https://github.com/typestack/routing-controllers/pull/526
