### ISSUE TITLE
question: how do I disable error logging?

### ISSUE THREAD

**Issue by TheCactusBlue** [typestack/routing-controllers#528]
Title says all - whenever I throw 400 errors, it gets logged - something that's unneccesary. Is there a way to prevent this?

**Comment by JHyeok** [comment]
I usually threw the error myself. Others have overridden the error handler.
This is my example project. https://github.com/JHyeok/jaebook-server

```
    @HttpCode(200)
    @Get("/:id")
    @OpenAPI({
        summary: "사용자 정보",
        description: "UserId로 사용자 정보를 반환한다",
        statusCode: "200",
    })
    public async getOne(@Param("id") id: string, @Res() res: Response) {
        const user = await this.userService.getUsersById(id);

        if (!user) {
            return res.status(400).send({ message: "custom error message" });
        }

        return user;
    }
```

**Comment by NoNameProvided** [comment]
You can overwrite the default error handler with your own implementation. For that, you need to set `defaultErrorHandler` option to `false` and provide your own error handler as a middleware:

```ts
import { Middleware, ExpressErrorMiddlewareInterface } from "routing-controllers";

@Middleware({ type: "after" })
export class CustomErrorHandler implements ExpressErrorMiddlewareInterface {
    error(error: any, request: any, response: any, next: (err: any) => any) {
        // do whatever you like with the error here
        next();
    }
}
```

**Comment by NoNameProvided** [comment]
Closing this as solved, if the proposed solution doesn't solve your problem please reply to this issue and we reopen for further discussion.
