### ISSUE TITLE
How to set keepAliveTimeout and headersTimeout?

### ISSUE THREAD

**Issue by nrcmkoh** [typestack/routing-controllers#535]
Is there a way to set node's [`server.keepAliveTimeout`](https://nodejs.org/docs/latest-v10.x/api/https.html#https_server_keepalivetimeout) and [`server.headersTimeout`](https://nodejs.org/docs/latest-v10.x/api/https.html#https_server_headerstimeout)? 

I've tried this, but it doesn't appear to be working:
```ts
const server = createKoaServer({
  ...
});

server.listen(3000);
server.keepAliveTimeout = 90 * 1000;
server.headersTimeout = 95 * 1000;
```

If anyone's interested as to why I'm trying to do this, it's because of [an issue](https://github.com/nodejs/node/issues/27363) with running node behind AWS Load Balancer.

**Comment by attilaorosz** [comment]
createKoaServer returns the koa server instance so unfortunately this is out of scope of this package. Maybe you will find some answers to this in the koa repo.
