### ISSUE TITLE
How to render a 404 page?

### ISSUE THREAD

**Issue by DiefBell** [typestack/routing-controllers#541]
Express isn't running "after" middleware if a route isn't found and I can't seem to work out how to render an error page. Is there a built in system for this?

**Comment by andrewsantarin** [comment]
@MerrickKing I ran into this problem myself. On the docs, this is what you need to do: https://github.com/typestack/routing-controllers#error-handlers. It's not obvious enough that you need to deactivate `defaultErrorHandler` and introduce your own handlers.

Do these work for you?

-------

##### With `createExpressServer()`, `@Middleware()`, `ExpressMiddlewareInterface `, `ExpressErrorMiddlewareInterface`

```ts
import 'reflect-metadata';
import path from 'path';
import { createExpressServer, Middleware, ExpressErrorMiddlewareInterface, ExpressMiddlewareInterface } from 'routing-controllers';
import { controllers } from './controllers'; // I assume you already implemented this.
import { RequestHandler, ErrorRequestHandler } from 'express';

// I assume you've already implemented the HTTP status code pages.

@Middleware({ type: "after" })
class InternalServerErrorHandler implements ExpressErrorMiddlewareInterface {
  error: ErrorRequestHandler = (err, req, res, next) => {
    console.log('handleInternalServerError');
    res.status(500).render('http_500-internal-server-error');
  }
}

@Middleware({ type: 'after' })
class NotFoundErrorHandler implements ExpressMiddlewareInterface {
  use: RequestHandler = (req, res, next) => {
    console.log('handleNotFound');
    res.status(400).render('http_404-not-found');
  }
}

const middlewares = [
  NotFoundErrorHandler,
  InternalServerErrorHandler
];

// Same thing as above.
const app = createExpressServer({
  controllers: controllers,
  middlewares: middlewares,
  defaultErrorHandler: false,       // Apply your handlers.
});

app.set('views', path.join(__dirname, '../views'));
app.set('view engine', 'pug');      // I assume you use pug.

app.listen(3000);
```

-------

##### With `useExpressServer()`, `express()`, `RequestHandler`, `ErrorRequestHandler`

```ts
import 'reflect-metadata';
import path from 'path';
import express, { RequestHandler, ErrorRequestHandler } from 'express';
import { useExpressServer } from 'routing-controllers';
import { controllers } from './controllers'; // I assume you've already implemented this.

// I assume you've already implemented the HTTP status code pages.

const handleNotFound: RequestHandler = (req, res, next) => {
  console.log('handleNotFound');
  res.status(400).render('http_404-not-found');
};

const handleInternalServerError: ErrorRequestHandler = (err, req, res, next) => {
  console.log('handleInternalServerError');
  res.status(500).render('http_500-internal-server-error');
};

const app = express();

app.set('views', path.join(__dirname, '../views'));
app.set('view engine', 'pug');      // I assume you use pug.

useExpressServer(app, {
  controllers: controllers,
  defaultErrorHandler: false,       // Apply your handlers.
});

// Apply these handlers after the controllers. The order matters!
app.use(handleNotFound);            // 404 = resouce can't be located
app.use(handleInternalServerError); // 500 = errors aren't handled

app.listen(3000);
```

**Comment by MerrickKing** [comment]
@andrewsantarin so does disabling the default error handler mean that I have to manually set the status code? I've noticed that it seems to be "200" before I do that.

**Comment by andrewsantarin** [comment]
> so does disabling the default error handler mean that I have to manually set the status code?

Yup. When you deactivate `defaultErrorHandler`, you're effectively allowing `routing-controllers` to give you full control of HTTP status code error handling.

This means **you're on your own**.

I mean, why shouldn't you be? You get the freedom to do whatever you want with the error, which is a good thing in my book.

-----
You can see it implemented here: 

https://github.com/typestack/routing-controllers/blob/134b01224848269f1ec2f7473e77a1374aa52ec3/src/index.ts#L181-L185

https://github.com/typestack/routing-controllers/blob/134b01224848269f1ec2f7473e77a1374aa52ec3/src/driver/BaseDriver.ts#L149-L156

https://github.com/typestack/routing-controllers/blob/134b01224848269f1ec2f7473e77a1374aa52ec3/src/driver/BaseDriver.ts#L181-L188

If `defaultErrorHandler` is `false`, the framework exits early from those two `BaseDriver` error processors and just returns the errors to you to manage them yourself.

**Comment by apgapg** [comment]
> ```ts
> app.use(handleNotFound); 
> ```

This throws me following error

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/Users/ayushpgupta/WebProjects/fa_nodejs_dms_dashboard_api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/Users/ayushpgupta/WebProjects/fa_nodejs_dms_dashboard_api/node_modules/express/lib/response.js:599:15)
    at ServerResponse.send (/Users/ayushpgupta/WebProjects/fa_nodejs_dms_dashboard_api/node_modules/express/lib/response.js:145:14)
    at handleNotFound (/Users/ayushpgupta/WebProjects/fa_nodejs_dms_dashboard_api/src/app/app.ts:113:19)
 ```
 
 This means after every request my 404 middleware is invoken causing not found error..

**Comment by apgapg** [comment]
I was able to solve via https://github.com/typestack/routing-controllers/issues/491#issuecomment-573045524

**Comment by NoNameProvided** [comment]
As said, you need to register a custom error handler.
