### ISSUE TITLE
question: cannot get Request Body for Swagger

### ISSUE THREAD

**Issue by kamleshkatpara** [typestack/routing-controllers#545]
Hi,
@pleerock @MichalLytek @NoNameProvided 

This are my settings:

```ts
private routingControllersOptions = {
        routePrefix: '/api',
        controllers: [__dirname + "/controllers/*{.js,.ts}"],
        cors: true,
        classTransformer: false,
        defaultErrorHandler: false,
        defaults: {`
            `paramOptions: {`
                required: tru`
            }
        }
    };
```

This is my Todo :

```ts
import { Document } from 'mongoose';

export interface Todo extends Document {
    readonly _id: string;
    readonly name: string;
    readonly description: string;
}
```

and this is my POST method:
```ts
    @Post()
    async create(@Body({ required: true, validate: true }) todo: Todo) {
        return await this.todoService.create(todo);
    }
```

I am not able to set the default request body for swagger as shown below:

![Screenshot from 2020-03-10 02-42-19](https://user-images.githubusercontent.com/16983847/76258123-fd179480-6278-11ea-885d-31993e97774e.png)

**Comment by jotamorais** [comment]
@kamleshkatpara,

You will be better off if you annotate the object you take in your request with [`class-validator`](https://github.com/typestack/class-validator#readme). You use it like:

Like:

`todoDTO.ts`
```ts
export class Todo {
    @IsString()
    public _id: string;

    @IsString()
    @MinLength(3)
    public name: string;

    @IsString()
    @MinLength(3)
    @MaxLength(50, { message: 'Language name is too long' })
    public description: string;
}
```

Enable class transformation and validation in your `RoutingControllerOptions`:

```ts
/**
   * Routing Controllers configuration object
   */
  private routingControllersOptions(): RoutingControllersOptions {
    return {
      defaults: {
        // with this option, null will return 404 by default
        nullResultCode: 404,

        // with this option, void or Promise<void> will return 204 by default
        undefinedResultCode: 204,
      },
      defaultErrorHandler: false,
      classTransformer: true,
      validation: true,
      development: process.env.APP_ENV === 'development',
      controllers: [
        `${process.env.SRC_PATH}/server/controllers/*{.ts,.js}`,
      ],
      middlewares: [CORSMiddleware, multer, ErrorHandler],
      routePrefix: '/api/v1',
      authorizationChecker: async (action: Action, requiredRoles: string[]) => {
        try {
          const payload = this.decodeJWT(action);
          console.log(`Payload: ${JSON.stringify(payload)}`);
          //TODO: implement your authorization logic here
          return true;
        } catch (error) {
          logger.error(error);
          throw new UnauthorizedError(error);
        }
      },
      currentUserChecker: async (action: Action) => {
        const payload = this.decodeJWT(action);
        const authService = Container.get(AuthService);
        return await authService.GetUserAndRoles(username);
      },
    };
  }
```

and then you can build your API documentation the way you want using `routing-controllers-openapi`:

```ts
/**
   * Configure, generate and expose API documentation (Swagger UI and OpenAPI)
   *
   * @returns {void}
   */
  private generateAPIDocumentation(): void {
    const metadatas = (getFromContainer(MetadataStorage) as any)
      .validationMetadatas;
    const schemas = validationMetadatasToSchemas(metadatas, {
      refPointerPrefix: '#/components/schemas/',
    });
    // Parse routing-controllers classes into OpenAPI spec:
    const storage = getMetadataArgsStorage();

    const securityRequirement = {
      bearerAuth: [],
    };

    const spec = routingControllersToSpec(
      storage,
      this.routingControllersOptions(),
      {
        openapi: '3.0.0',
        components: {
          schemas,
          securitySchemes: {
            bearerAuth: {
              type: 'http',
              scheme: 'bearer',
              bearerFormat: 'JWT',
            },
          },
        },
        info: {
          description: 'My API',
          title: 'My-API',
          version: '1.0.0',
        },
        servers: [
          {
            url: '',
            variables: {
              protocol: {
                enum: ['http', 'https'],
                default: 'http',
              },
              environment: {
                enum: [
                  'localhost:3000',
                  'dev.mydomain.com',
                  'test.mydomain.com',
                  'prod.mydomain.com'
                ],
                default: 'localhost:3000',
              },
              site: {
                enum: ['', '/', '/API'],
                default: '',
              },
              basePath: {
                enum: [
                  '',
                  '/',
                  `${this.routingControllersOptions().routePrefix}`,
                ],
                default: '',
              },
            },
          },
        ],
        security: [securityRequirement],
      },
    );

    // Render spec on /api/v1/docs/swagger.json:
    this.express.get(
      `${this.routingControllersOptions().routePrefix}/docs/swagger.json`,
      (_req, res) => {
        res.json(spec);
      },
    );

    const options = {
      displayRequestDuration: true,
      swaggerOptions: {
        docExpansion: ['list'],
        explorer: false,
        filter: true,
        tagsSorter: 'alpha',
      },
    };

    this.express.use(
      `${this.routingControllersOptions().routePrefix}/docs`,
      swaggerUi.serve,
      swaggerUi.setup(spec, options),
    );
    console.log(
      `API documentation available at: ${
      this.routingControllersOptions().routePrefix
      }/docs`,
    );
  }
```

**Comment by kamleshkatpara** [comment]
@jotamorais ,

Thanks, I tried your suggested solution still its the same can't get schema for post

![Screenshot from 2020-03-13 12-03-43](https://user-images.githubusercontent.com/16983847/76595913-df6d5800-6522-11ea-8471-fe3d7d1d55e9.png)

`import { json, urlencoded } from 'body-parser';
import { MetadataStorage } from 'class-validator';
import { validationMetadatasToSchemas } from 'class-validator-jsonschema';
import * as express from 'express';
import * as httpContext from 'express-http-context';
import * as helmet from 'helmet';
import 'reflect-metadata';
import { getFromContainer, getMetadataArgsStorage, useContainer, useExpressServer, Action, UnauthorizedError, RoutingControllersOptions } from 'routing-controllers';
import { routingControllersToSpec } from 'routing-controllers-openapi';
import * as swaggerUi from 'swagger-ui-express';
import { Container } from 'typedi';
import * as uuid from 'uuid';
import { Logger, LoggerService } from './common/logger';
import * as mongoose from 'mongoose';
import * as config from 'config';
import * as health from 'express-ping';

export class App {

    private app: express.Application;

    private routingControllersOptions(): RoutingControllersOptions {
        return {
            defaults: {
                // with this option, null will return 404 by default
                nullResultCode: 404,

                // with this option, void or Promise<void> will return 204 by default
                undefinedResultCode: 204,
            },
            defaultErrorHandler: false,
            classTransformer: true,
            validation: true,
            development: true,
            controllers: [__dirname + "/controllers/*{.js,.ts}"],
            routePrefix: '/api'
        };
    }

    constructor(@Logger(__filename) private logger: LoggerService = new LoggerService(__filename)) { }

    public async initApp(): Promise<void> {
        try {
            this.app = express();
            this.setupExpress();
            await this.setupRouting();
            this.initDatabase();
            this.setupSwagger();
        } catch (error) {
            this.logger.warn(`Something went wrong while initializing server, see log for details`);
            this.logger.error(error.stack);
            process.exit(1);
        }
    }

    private setupExpress(): void {
        this.logger.info('Setting up server...');
        this.app.use(json());
        this.app.use(urlencoded({
            extended: true
        }));
        this.app.use(helmet());
        this.app.use((req, res, next) => {
            res.setHeader('X-Powered-By', 'Custom');
            next();
        });
        this.app.use(httpContext.middleware);
        this.app.use((req, res, next) => {
            httpContext.set('reqId', uuid.v1());
            httpContext.set('useragent', req.headers['user-agent']);
            httpContext.set('ip', req.ip);
            next();
        });
        this.app.use(health.ping());
        process.on('uncaughtException', (error) => {
            this.logger.error(error.stack);
        });
    }

    private async setupRouting(): Promise<express.Application> {
        this.logger.info('Setting up routes...');
        useContainer(Container);
        this.app = useExpressServer(this.app, this.routingControllersOptions());
        this.logger.info('Routing setup successful');
        return this.app;
    }

    private initDatabase(): void {
        this.logger.info('Setting up database...');
        try {
            mongoose.connect(config.get('database.url'), { useNewUrlParser: true, useUnifiedTopology: true });
            this.logger.info('Database setup succesful');
        } catch (error) {
            this.logger.error(`Something went wrong while initializing database => ${error.message}`);
        }
    }

    private setupSwagger(): void {
        this.logger.info('Setting up swagger...');
        const metadatas = (getFromContainer(MetadataStorage) as any).validationMetadatas
        const schemas = validationMetadatasToSchemas(metadatas, {
            refPointerPrefix: '#/components/schemas/'
        })

        const storage = getMetadataArgsStorage();
        const securityRequirement = {
            bearerAuth: [],
        };
        const spec = routingControllersToSpec(storage, this.routingControllersOptions(), {
            openapi: '3.0.0',
            components: {
                schemas,
                securitySchemes: {
                    bearerAuth: {
                        type: 'http',
                        scheme: 'bearer',
                        bearerFormat: 'JWT',
                    },
                }
            },
            info: {
                description: 'CustomJS API',
                title: 'CustomJS',
                version: '1.0.0',
            },
            servers: [
                {
                    url: '',
                    variables: {
                        protocol: {
                            enum: ['http', 'https'],
                            default: 'http',
                        },
                        environment: {
                            enum: [
                                'localhost:3000',
                                'dev.mydomain.com',
                                'test.mydomain.com',
                                'prod.mydomain.com'
                            ],
                            default: 'localhost:3000',
                        },
                        site: {
                            enum: ['', '/', '/API'],
                            default: '',
                        },
                        basePath: {
                            enum: [
                                '',
                                '/',
                                `${this.routingControllersOptions().routePrefix}`,
                            ],
                            default: '',
                        },
                    },
                },
            ],
            security: [securityRequirement],
        });
        this.logger.info('Swagger setup successful');
        console.log(spec);

        this.app.use('/explorer', swaggerUi.serve, swaggerUi.setup(spec));
    }

    public getAppInstance(): express.Application {
        return this.app;
    }
}`

**Comment by jotamorais** [comment]
@kamleshkatpara what about your entities - did you annotate them like in the example I gave?

**Comment by kamleshkatpara** [comment]
@jotamorais  yes, the same way

`import { IsString, MinLength, MaxLength } from "class-validator";

export class Todo {
    @IsString()
    public _id: string;

    @IsString()
    @MinLength(3)
    public name: string;

    @IsString()
    @MinLength(3)
    @MaxLength(50, { message: 'Language name is too long' })
    public description: string;
}`

**Comment by NoNameProvided** [comment]
I am not familiar with the Swagger integrations, so I cannot help. You should ask for help at the library that you use to generate this documentation, not us.
