### ISSUE TITLE
Big trouble with Koa

### ISSUE THREAD

**Issue by root1984** [typestack/routing-controllers#556]
In KoaDriver.ts
This statement is not logic of Koa, how to fix this?
```
if (action.redirect) { // if redirect is set then do it
            if (typeof result === "string") {
                options.response.redirect(result);
            } else if (result instanceof Object) {
                options.response.redirect(templateUrl(action.redirect, result));
            } else {
                options.response.redirect(action.redirect);
            }
        } else if (action.renderedTemplate) { // if template is set then render it // TODO: not working in koa
            const renderOptions = result && result instanceof Object ? result : {};

            this.koa.use(async function (ctx: any, next: any) {
                await ctx.render(action.renderedTemplate, renderOptions);
            });
        }
```

**Comment by jotamorais** [comment]
@root1984 I didn't get your question and don't know what you want fixed when you say 'how to fix this'.

Can you please elaborate a bit more on what you're trying to do and the result you got?
It would be great if you could put a minimal reproduction of the issue in a sandbox as well. You can use https://codesandbox.io/s/stoic-johnson-7r2hd?file=/src/index.ts

Thank you!

**Comment by NoNameProvided** [comment]
Koa support is being deprecated and will be removed in the next version. Please use express adapter instead.
