### ISSUE TITLE
question: UnprocessableEntityError

### ISSUE THREAD

**Issue by incompletude** [typestack/routing-controllers#561]
Hey guys, amazing lib, thx.

For the context of the routing-controllers, I think it makes perfect sense to have UnprocessableEntityError along with the other http errors. I'm extending this for now, but it looks unnecessary.

I can open a PR.

**Comment by jotamorais** [comment]
@incompletude, as described in the [documentation](https://github.com/typestack/routing-controllers#throw-http-errors), it's always possible to extend `HttpError` class and create custom exception types to fit your need.

**`/sandbox/src/exceptions/UnprocessableEntityError.ts`**
```typescript
import { HttpError } from "routing-controllers";

export class UnprocessableEntityError extends HttpError {
  public operationName: string;
  public args: any[];

  constructor(operationName: string, args: any[] = []) {
    super(500);
    Object.setPrototypeOf(this, UnprocessableEntityError.prototype);
    this.operationName = operationName;
    this.args = args; // can be used for internal logging
  }

  toJSON() {
    return {
      status: this.httpCode,
      failedOperation: this.operationName
    };
  }
}

```

**`/sandbox/src/example/example.controller.ts`**
```typescript
import { Controller, Get } from "routing-controllers";
import { UnprocessableEntityError } from "../exceptions/UnprocessableEntityError";

@Controller("/")
export class ExampleController {
  @Get()
  public get(): string {
    throw new UnprocessableEntityError("Your custom error msg here!");
  }
}
```

Check the running example here: https://codesandbox.io/s/routing-controller-unprocessableentityerror-561-9oos4?file=/src/example/exampe.controller.ts

**Comment by incompletude** [comment]
@jotamorais Thank you.

I'm already doing that.

What I'm saying is that the 422 error is a common HttpError for RESTful APIs, thus it makes sense to have it along with the other classes provided with routing-controllers.

**Comment by NoNameProvided** [comment]
I am not entirely sold on including error classes beside the bare minimum as they are overwritten with custom behavior most of the time. That's said we can discuss what error should we include, but let's do that later, routing-controller will be refactored and modernized once the libs it's built on are refactored (TypeDI, class-transformer, class-validator).

Closing this for now as adding it would just leave to having more stuff to refactor and break.
