### ISSUE TITLE
0.8.1 changelog is wrong

### ISSUE THREAD

**Issue by nolazybits** [typestack/routing-controllers#565]
Dunno what happened but if you look at the 0.8.1 tag (and npm release)
this is what you will see
https://github.com/typestack/routing-controllers/blob/0.8.1/src/metadata-builder/MetadataBuilder.ts#L62

whereas this is what the fix was (and in master)
https://github.com/typestack/routing-controllers/blob/master/src/metadata-builder/MetadataBuilder.ts#L62

@jotamorais  could you please amend the log and re-release to have the interceptors order solved please.

**Comment by jotamorais** [comment]
@nolazybits I've fixed that in [0.9.0-alpha.1](https://github.com/typestack/routing-controllers/releases/tag/0.9.0-alpha.1). 
Give it a try and let me know if you see anything wrong.

Thank you!

**Comment by nolazybits** [comment]
tried 0.9.0-alpha.1 and it works
thank you so much for being reactive on this one :+1:
