### ISSUE TITLE
Update CI/CD and package.json so one can consume either NPM or GIT

### ISSUE THREAD

**Issue by nolazybits** [typestack/routing-controllers#566]
Currently, if someone tries to use GITHUB URL in npm
`"routing-controllers": "git+https://github.com/typestack/routing-controllers.git#master"`
 this is not possible as the package.json main doesn't match the folder structure in the project.

The main should be changed to a path that wouldn't change in ts/js world and the extension could be emitted (eg `src/index`)
Of course, this would be only available to TS projects as the source files are ts files.

**Comment by NoNameProvided** [comment]
You cannot consume tha package directly, because the repository contains the Typescript source while we publish the compiled JS to NPM. Closing as invalid as the only solution would be to bundle the compiled source in the repository which we won't do.
