### ISSUE TITLE
question: how do I return a file from a buffer with a specific file name?

### ISSUE THREAD

**Issue by RW-DiefBell** [typestack/routing-controllers#573]
So I want to return a file from a buffer, however returning the buffer in my action downloads the file as a zip file, when I want to download it as an xlsx (I know I can just rename it, but it's for non-techy people to use).

At the moment, I'm achieving it like this:

```typescript
const workbookBuffer = xlsx.write(workbook, { type: "buffer" });
res.writeHead(200, {
    "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
     "Content-disposition": `attachment;filename=${Date.now()}.xlsx`,
      "Content-Length": workbookBuffer.length
});
res.end(workbookBuffer);
return res;
```

but is there a more elegant way of doing this? Can I return some kind of object in my action that will do all of this without me needing to work directly with res?

Cheers :)

**Comment by nadunindunil** [comment]
@RW-DiefBell any luck? 
and how did you use the above code?
is it inside a controller?

**Comment by RW-DiefBell** [comment]
I got it working as above. Just inject the Response into your controller with @Res and then put this at the end of your controller

**Comment by nadunindunil** [comment]
@RW-DiefBell  I did the exact same thing but I get a corrupted xlsx file. Do you have any idea?

```
@JsonController('/excel')
export default class ExcelController {
  @Authorized()
  @Get('/')
  public generateExcel(@Res() response: Response): any {
    const data = [
      ['a', 'b', 'c'],
      ['1', '2', '3']
    ];

    const ws = XLSX.utils.aoa_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'SheetJS');

    const wopts: XLSX.WritingOptions = { bookType: 'xlsx', bookSST: false, type: 'buffer' };
    const buffer = XLSX.write(wb, wopts);

    response.writeHead(200, {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-disposition': `attachment;filename=${Date.now()}.xlsx`,
      'Content-Length': buffer.length
    });
    response.end(buffer);
    return response;
  }
}
```

**Comment by RW-DiefBell** [comment]
Have you tried saving your XLSX to a file first? I should point out that all of the XLSX options out there for js are pretty crap so could just be that

**Comment by nadunindunil** [comment]
I see 
Thank you very much for the information.
Never thought downloading a JSON as an excel would be this much hard :laughing:

**Comment by nadunindunil** [comment]
Definitely, I will try that 
I was looking for a `write` method because I am using a serverless function.
But it seems I have no other options.

**Comment by RW-DiefBell** [comment]
This is just to test

**Comment by nadunindunil** [comment]
`XLSX.writeFile(wb, 'out.xlsx');` works as expected.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions) and someone from the community may be able to help.
