### ISSUE TITLE
Sending streams as response

### ISSUE THREAD

**Issue by azaslonov** [typestack/routing-controllers#576]
Hi there,

Is it possible to send streams somehow? Roughly, I'm trying to do this:
```
@Get("/*")
public async processRequest(@Req() request, @Res() response) {
        ...
        const readableStream = await myStorage.getBlobAsStream();
        readableStream.pipe(response);
       ...
}
```
...and receive the error like this:
```
Application has thrown an uncaught exception and is terminated:
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:572:17)
    at ServerResponse.write (_http_outgoing.js:567:10)
    at RetriableReadableStream.ondata (_stream_readable.js:666:20)
    at RetriableReadableStream.emit (events.js:182:13)
    at RetriableReadableStream.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Could you please advise?

**Comment by vs4vijay** [comment]
Any update on this? Is this possible using Routing Controllers?

**Comment by wsmd** [comment]
Hey all - `routing-controllers` does actually support returning streams from a controller method (via https://github.com/typestack/routing-controllers/pull/285), but I've found it a bit tricky at first compared to a simple `readable.pipe(response)`.

I've managed to get piping streams to work by using either of the two following methods:

**1. Piping the readable to the response and returning a Promise**

```ts
@Get('/pipe_with_promise')
promise(@Res() res: Request) {
  const readable = getReadableStreamSomehow();
  return new Promise<Response>((resolve, reject) => {
    readable
      .on('end', () => resolve(res))
      .on('error', (error) => reject(error))
      .pipe(res);
  });
}
```

**2. Piping the readable to a Passthrough stream and returning it**

```ts
import { PassThrough } from 'stream';

// ...

@Get('/pipe_with_passthrough')
passthrough() {
  const stream = new PassThrough();
  getReadableStreamSomehow().pipe(stream);
  return stream;
}
```

Note that with the Passthrough approach, I've encountered some with issues the content-type not being inferred automatically, so you may need to use [`@ContentType`](https://github.com/typestack/routing-controllers/blob/f8e00f38953ff3f0bf8187bacbad6cd5e76e9297/README.md#set-custom-contenttype) as well, depending on your use case.

**Comment by GreatEarl** [comment]
@wsmd really appreciate your answer here! I literally wasted half of the day trying to understand why piping doesn't work with routing controllers.
I need to do the same but with zip also, like (as actually i'm passing a *.docx file)
`readable.pipe(zlib.createGzip()).pipe(res);`

within standard Express it works fine. Consider 
`function bufferToStream(binary) {
    const readableInstanceStream = new stream.Readable({
        read() {
        this.push(binary);
        this.push(null);
        }
    });
    return readableInstanceStream;
}
// ...
    const fileStream = bufferToStream(file);
    fileStream.pipe(zlib.createGzip()).pipe(res);
`
Injecting zlib gives 404 again. Can you give some ideas of what I'm missing?
Thanks.

**Comment by GreatEarl** [comment]
I was able to solve my question above with this code below. 

`      
  
      return new Promise<any>(async (resolve, reject) => {
            const readable = await addinService.convertTemplate(user); // <- here we get a readable stream with content of *.docx

            const gzip = createGzip();
            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
            res.setHeader('Content-Disposition', 'attachment; filename=template.docx');
            res.setHeader('Content-Encoding', 'gzip');

            
            await pipe(readable, gzip, res);
            readable.on('end', () => { 
                resolve(res);
            });
            readable.on('error', (error) => reject(error));
        });`

Insert 
`const { createGzip } = require('zlib');`
`const { pipeline } = require('stream');`
`const { promisify } = require('util');`
`const pipe = promisify(pipeline);`
somewhere above as well.

**Comment by attilaorosz** [comment]
Seems like a soltuion was found.
