### ISSUE TITLE
Is there a way to configure wildcard routes?

### ISSUE THREAD

**Issue by azaslonov** [typestack/routing-controllers#583]
Hi there,
Is there a way to configure wildcard routes? I have defined several fixed routes and one that handles all the rest requests:

app.get("/route1/", ...)
app.get("/route1/", ...)
app.get("/*", ...) - this is one declared after all the fixed routes.

Question is can I do the same with controllers? My controller that contains "/*" route always executes, intercepting fixed routes, no matter what position it was added to in `controllers` collection:
```
useExpressServer(app, {
     controllers: [
         Route1Controller,
         Route1Controller,
         AllRoutesController
     ]
}
```

Please advise.

**Comment by attilaorosz** [comment]
Currently the workaround is to import your controllers in order (importing them in your ts file, not in the controllers array). This is obviously not the best option but you can live with it until there is a fix.

**Comment by azaslonov** [comment]
Got it, thanks!
