### ISSUE TITLE
question: ability to set global driver middleware options

### ISSUE THREAD

**Issue by varanauskas** [typestack/routing-controllers#586]
There should be a way to set global options for driver middleware (for example body-parser options)

It could be done in `create${driver}Server` by extending the RoutingControllersOptions for each driver, for example

```ts
interface ExpressRoutingControllersOptions extends RoutingControllersOptions {
  bodyParserOptions: any; // or even better, grab them from @types/body-parser
}
```

Then on request with `@Body` the router would utilize set options

There needs to be a discussion on functionality, if both global options are provided and `@Body` parser options are provided on how should it work, should it merge these two objects or should it just use the options defined in `@Body`

My use case for this would be modifying the way `body-parser` handles numbers globally

**Comment by attilaorosz** [comment]
This would require a major change and you can already do this by using useExpressServer instead of createExpressServer. @NoNameProvided thoughts?

**Comment by NoNameProvided** [comment]
Eventually, we may want to do this, but as @attilaorosz said, you can currently do this via using `useExpressServer`.
