### ISSUE TITLE
question: ability customise validation errors

### ISSUE THREAD

**Issue by cupcakearmy** [typestack/routing-controllers#588]
I wanted to ask if there is a way to customise validation errors, as the default behaviour exposes to much data in my case.

Any ideas? Thaaaanks ❤️

**Comment by suyash-kale** [comment]
in my case I ended up using 'express-mung' for changing the validation response object:
Example:
`import mung from 'express-mung';
const expressApp = express();
expressApp.use(
  mung.json(
    (body: Record<string, unknown>) => {
      if (body.stack) {
        delete body.stack;
      }
      return body;
    },
    { mungError: true },
  ),
);
const app = useExpressServer(expressApp);`

**Comment by NoNameProvided** [comment]
The error object is not optimal currently, and eventually will be updated in the `class-validator`. However, that doesn't solve the problem of exposing too much data. 

Currently, we don't have any way to manipulate the class-validator error response? I think you should be able to do it in a custom error handler as any payload validation error should go through that.

**Comment by NoNameProvided** [comment]
I will close this a solved, you can update the response in the custom error middleware.
