### ISSUE TITLE
Why is next function called after send a response?

### ISSUE THREAD

**Issue by fega** [typestack/routing-controllers#589]
Hello, I was checking an issue that was breaking the behavior of the compression middleware for express.

I ended solving it commenting out these "options.next" calls. which seems to be very strange. usually, express apps don't expect to next be called after the response is sent, for that reason middleware like compression and errors like "Can't set headers after they are sent" can appear unexpectedly.

https://github.com/typestack/routing-controllers/blob/53264285466a0472ef9644f28f0b0a1dca0df939/src/driver/express/ExpressDriver.ts#L350

**Comment by attilaorosz** [comment]
Next is called because we have to make sure that every registered express middlware is executed.
