### ISSUE TITLE
@Render will not work with Koa

### ISSUE THREAD

**Issue by ericwong3** [typestack/routing-controllers#592]
# Summary

The @Render decorator cannot be paired with Koa, the first rendered page will stuck and be rendered over and over, unable to render any new page.

# Steps to Reproduce

1. Clone the repo
1. `npm install`
1. Go to [sample/sample13-koa-views-render](https://github.com/typestack/routing-controllers/blob/master/sample/sample13-koa-views-render/)
1. Edit `BlogController.ts`, change `title: "My Blog",` to `title: "My Blog" + new Date(),` (for easier visualization)
1. `npx ts-node app.ts`
1. Visit http://localhost:3001/bad , observe "Not Found" appearing, which is expected
1. Go to http://localhost:3001/ , observe the blogs list appearing, seems good
1. Refresh several times, observe the timestamp won't change
1. Go to http://localhost:3001/bad again, observe the blogs list with stale timestamp appear

# Diagnostics

The problem should be coming from the `handleSuccess` function in `KoaDriver`:
```ts
    handleSuccess(result: any, action: ActionMetadata, options: Action): void {
        // ... omitted
        } else if (action.renderedTemplate) { // if template is set then render it // TODO: not working in koa
            const renderOptions = result && result instanceof Object ? result : {};

            this.koa.use(async function (ctx: any, next: any) {
                await ctx.render(action.renderedTemplate, renderOptions);
            });
        }
        // ... omitted
    }
```

Having worked with express, on first glance there is one obvious issue, the koa.use is called repetitively each time `handleSuccess` is called, you do not normally want to `.use` again and again, it is both a performance hit and a hidden can of worm. (May be what #556 is saying?)

And given more thinking, one will see why the stale HTML phenomenon appear. On first time the `handleSuccess` is executed, the render function is enqueued in first position (at least first rendering function), with `renderedTemplate` and `renderOptions` from this request. So far so good, but then subsequent rendering will not work, because the first request's middleware, along with its `renderedTemplate` and `renderOptions` is now stuck in first place and is always executed first.

# Proposed Solution

I used a quick patch on `KoaDriver`, changing
```ts
handleSuccess(result: any, action: ActionMetadata, options: Action): void {
```
to
```ts
async handleSuccess(result: any, action: ActionMetadata, options: Action): void {
```
and
```ts
            this.koa.use(async function (ctx: any, next: any) {
                await ctx.render(action.renderedTemplate, renderOptions);
            });
```
to
```ts
            await options.context.render(action.renderedTemplate, renderOptions);
```

The thing to remember is, `ctx.render` must be called within the handling loop with `await`, so we are bound to doing `await options.context.render`, and luckily the places calling `handleSuccess` can already process a promise returning from it. So this trick works.

(Actually the source code [src/driver/koa/KoaDriver.ts#L233](https://github.com/typestack/routing-controllers/blob/9b5d39d3e1f97b6cbf337b2adb8ec3be95f409fb/src/driver/koa/KoaDriver.ts#L233) said it has not been working for almost 3 years)

**Comment by NoNameProvided** [comment]
Koa support is being deprecated and removed.

**Comment by ericwong3** [comment]
okay... but why? There is no mention of deprecation on README. Is it because it is too much too handle? As I see the project already contains the driver abstraction layer, it would be a waste to drop the support..
