### ISSUE TITLE
Support the new koa router package

### ISSUE THREAD

**Issue by feimosi** [typestack/routing-controllers#595]
`koa-router` package has been renamed to [`@koa/router`](https://github.com/koajs/router). However, using the latter fails with:
> `koa-router package was not found installed. Try to install it` 

The issue is, because `routing-controllers` uses the old import: 
https://github.com/Keyj1n/routing-controllers/blob/master/src/driver/koa/KoaDriver.ts#L394
I think this logic should be refactored to simply allow passing a custom `koa-router` instance to `routing-controllers`.
What do you think?

**Comment by NoNameProvided** [comment]
Koa is being deprecated and will be removed.

**Comment by feimosi** [comment]
@NoNameProvided so you're saying routing-controllers will drop support for koa.js completely?

**Comment by NoNameProvided** [comment]
Yes. In the close future.

**Comment by NoNameProvided** [comment]
Do you rely on some "low-level" Koa functionality which doesn't supported in Express?

**Comment by feimosi** [comment]
@NoNameProvided nothing low-level. Is there going to be any way to still hook it up, even in a hacky way, or only express apps will work? We can't afford the migration.
