### ISSUE TITLE
fix: Conflicting router paths

### ISSUE THREAD

**Issue by malinda1986** [typestack/routing-controllers#599]
### Description
Im using JsonController() for handle routes, but it calls two route paths for single api call  
**Minimal code-snippet showcasing the problem**

```ts
@JsonController()
export class OrderController {
    
    @Get("/sequence-id")
    @UseBefore(Header)
    async get(
        @HeaderParam("location") location: number,
        @HeaderParam("Authorization") token: string
    ) {
       
            console.log("/sequence-id");
  }

    @Get("/order-id")
    @UseBefore(Header)
    async getById(
        @HeaderParam("location") location: number,
        @HeaderParam("Authorization") token: string
    ) {
       
            console.log("/order-id");
  }
}

```

when calling the orders/sequence-id it triggers order-id path also 
orders/sequence-id - get
orders/{orderid} - get

Appreciate any advice

**Comment by ivanproskuryakov** [comment]
@malinda1986, I'm not 100%, but it seems that the route `orders/{orderid}` includes `orders/sequence-id`, where `sequence-id` is id and follows the rule of {orderid}.

**Comment by NoNameProvided** [comment]
This has been fixed, but not released yet. The next version of routing-controllers will stop after processing the first route-handler.

**Comment by cupcakearmy** [comment]
@NoNameProvided nice to hear :)
Is there a planned release soon?

**Comment by cupcakearmy** [comment]
nvm, updated to `0.9.0-alpha.6` and seems to be fixed
