### ISSUE TITLE
question: How to ensure removing inner containers

### ISSUE THREAD

**Issue by TKul6** [typestack/routing-controllers#603]
**I was trying to...**
Every request coming to my server containing a correlation id.
In order to do so I have 2 middlewares.
1. A **Before middleware** that creates a container for the request `Container.of(req.correlationId)`.
2. An **After middleware** that removes the container after the request id fulfilled / rejected.
**The problem:**
Sometimes the after middleware is not called:
- When an authentication middleware returns status 401 without advancing to the next middleware.
- When error is raised by the controller / service.

In this case I have a leak since the request's container will never be removed.

Do you have a suggestion how can I ensure removing the container (at least for the first case I mentioned).

Thank you.

**Comment by attilaorosz** [comment]
@TKul6 If you disable the default error handler and implement your own you could destroy your container instance there.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions) and someone from the community may be able to help.
