### ISSUE TITLE
question: how to mock a middleware used with @UseBefore decorator for unit testing

### ISSUE THREAD

**Issue by alexfradiani** [typestack/routing-controllers#609]
**I was trying to...**
create jest unit tests for a controller action that implements UseBefore with a custom middleware

**The problem:**
What would be the recommended way of mocking the middleware as used by routing-controllers? I need to overwrite part of the request data before it reaches the controller action.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
