### ISSUE TITLE
question: how to inject the server in a middleware?

### ISSUE THREAD

**Issue by rafaell-lycan** [typestack/routing-controllers#614]
**I have the following scenario when adding a 3-party lib:**
 
 

A 3-Party library that needs the `server/express` instance to be used as a Middleware on my app that mainly set some values on it:

e.g.:

```js
  // on Before
  server.set('env', config.env);
  server.set('appName', config.app.name);
  server.set('broker', `tcp://${config.app.broker}:9604`);

  server.use(vendorMiddleware.forRequests(server));
  server.use(vendorMiddleware.forLogging(logger, 'winston'));

  // on After
  server.use(vendorMiddleware.forErrors(server));
```

So the current solution that doesn't follow the rest of our custom middlewares is:

```js
// server.ts
const server = express(); 

usePreMiddleware(server);

useExpressServer(server, {
    controllers: [...],
    middlewares: [...],
});

usePostMiddleware(server);

export default server;
```

**Then I stook on the following piece of code:**
 

```js
import { Middleware, ExpressMiddlewareInterface } from "routing-controllers";

@Middleware({ type: "before" })
export class useVendorMiddleware implements ExpressMiddlewareInterface {

    use(request: any, response: any, next: (err: any) => any): void {
        // TODO: How to have access to app from here ?

        next();
    }

}
```

Do I have a way to access the application/container easily or not?

**Comment by HctrM** [comment]
Routing controllers (and express') middlewares are intended to be used after or before each http requests incoming even if they're declared globally (for every incoming http request no matter what). `request `and `response` objects are incoming and outgoing http payload and `next()` is to pass along these informations to controller or the next middleware. 

Configuring the `server` is only possible once, on startup and has nothing to do in a middleware. You cannot access the server container in a middleware. Also there is no notion of before and after useExpressServer, you should usually put all of your initializations before.

This is what I would recommend for initial configuration of your express app:
```
// server.ts
const server = express(); 

server.set('env', config.env);
server.set('appName', config.app.name);
server.set('broker', `tcp://${config.app.broker}:9604`);

server.use(vendorMiddleware.forRequests(server));
server.use(vendorMiddleware.forLogging(logger, 'winston'));

server.use(vendorMiddleware.forErrors(server));

useExpressServer(server, {
    controllers: [...],
    middlewares: [...],
});

usePostMiddleware(server);

export default server;
```
