### ISSUE TITLE
question: https support for routing-controllers 

### ISSUE THREAD

**Issue by marvelTracker** [typestack/routing-controllers#620]
I was trying to use routing-controllers in my project. It is a dockize solution.

Can you guys point me to some documentation/direction for configuring https for createExpressServer with routing-controllers ?

Thanks in Advance

**Comment by angelxmoreno** [comment]
Not sure I understand your question. Where are your hosting you application?  If you mean you want your docker container to serve HTTPS then that is outside the scope of routing controllers. There are various ways to achieve this. Take a look at https://techsparx.com/nodejs/docker/express-https.html and see if that helps.

**Comment by attilaorosz** [comment]
If you mean setting up https with ssl support then your best bet is to create the express app yourself and use useExpressServer. https://github.com/typestack/routing-controllers#pre-configure-expresskoa

**Comment by NoNameProvided** [comment]
As @attilaorosz said, you need to configure the underlying express instance correctly.
