### ISSUE TITLE
question: How can I read the form data in koa

### ISSUE THREAD

**Issue by iakoug** [typestack/routing-controllers#632]
@UseBefore(bodyParser.urlencoded())
handleForm(@Body() form: any) {}

For Express only.
There will be throw   TypeError: next is not a function in koa because req and res were replaced by ctx.

// Wrong
```
 @Post('/gallery/upload')
 @UseBefore(bodyParser.urlencoded())
  upload_photos(@Body() body) {
    return write_photos(body)
  }
```

**Comment by emik** [comment]
Having just learned that multipart form data is not accessible with `@Body` or `@BodyParam` I would also like to know if there is a simple solution to this that I'm missing. Am porting an app at the moment and much of the client code sends text and numerical data in this format.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
