### ISSUE TITLE
question: Can I use DI in an per-action Middleware?

### ISSUE THREAD

**Issue by Liioooo** [typestack/routing-controllers#635]
I would like to use DI in a per-action middleware like in global middleware like this.
```typescript
export class GoogleLoginMiddleware implements ExpressMiddlewareInterface {

  constructor(private translationService: TranslationService) {}

  use(request: Request, response: Response, next: (err?: any) => any): any {
    // do something with this service
    console.log(this.translationService.availableLanguages);
    next();
  }
}
```
But the problem is that I don't get the Service but the `ContainerInstance`.

What I did to work around this is this:
```typescript
export class GoogleLoginMiddleware implements ExpressMiddlewareInterface {

  private translationService = Container.get(TranslationService);

  use(request: Request, response: Response, next: (err?: any) => any): any {
    // do something with this service
    console.log(this.translationService.availableLanguages);
    next();
  }
}
```

Did I miss something or is this just not possible to do?

**Comment by attilaorosz** [comment]
@Liioooo Did you add the @Service decorator to your middleware?

**Comment by attilaorosz** [comment]
Did you try to add the Middleware decorator to your class? Also don’t forget to add the Service decorator too.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
