### ISSUE TITLE
question: How do I customize internal HttpErrors with custom Http errors with KoaDriver?

### ISSUE THREAD

**Issue by coneforapine** [typestack/routing-controllers#650]
I was sending custom HttpErrors that changes the response to the user but I can't do this when I'm validating request bodies because it's using the one that came with the library.

This is the response I want to throw when a validation fails;

```json
{
    "status": false,
    "message": "Validation errors.",
    "errors": "ValidationError[] from class validator"
}
```

This is what it currently returns

```json
{
    "name": "BadRequestError",
    "message": "Invalid body, check 'errors' property for more info.",
     "errors": "ValidationError[] from class validator"
}
```

One way that I could find is to use [this](https://github.com/typestack/routing-controllers#error-handlers) but since I'm using Koa I can't use it.

One workaround for this is disabling the validator from `@Body()` and calling class-validator inside the request function.

**Comment by nodejsdeveloperskh** [comment]
> If I remember correctly you can use custom error handlers with express.
> 
> [Here's the doc for the interface.](https://github.com/typestack/routing-controllers#error-handlers)

Hi, I solve it. IDK why, but the `ValidationError` was in the `error.errors` and it was an array of `ValidationError`. so i did this kind of trick to send the error message to the client:

```ts
class CustomValidationError {
    errors: ValidationError[];
}

/* CustomErrorHandler class - error method */
if (
    'errors' in error &&
    error.errors[0] instanceof ValidationError
) {
    const errorMessages: { [x: string]: string }[] = findProp(
        error,
        'constraints',
    );

    response
        .status(400)
        .json(new ErrorResponse(false, getValues(errorMessages)));
}

function findProp(obj: any, key: string, result: any[] = []): any[] {
    const proto = Object.prototype;
    const ts = proto.toString;
    const hasOwn = proto.hasOwnProperty.bind(obj);

    if ('[object Array]' !== ts.call(result)) {
        result = [];
    }

    for (let i in obj) {
        if (hasOwn(i)) {
            if (i === key) {
                result.push(obj[i]);
            } else if (
                '[object Array]' === ts.call(obj[i]) ||
                '[object Object]' === ts.call(obj[i])
            ) {
                findProp(obj[i], key, result);
            }
        }
    }

    return result;
}

function getValues(arrayOfObjects: { [x: string]: string }[]): string[] {
    const result: string[] = [];

    for (let item of arrayOfObjects) {
        result.push(...Object.values(item));
    }

    return result;
}
```

and with this trick, I resolve it. HOPE this would be helpful later. :dart:

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
