### ISSUE TITLE
support for awilix DI

### ISSUE THREAD

**Issue by sujansaresta** [typestack/routing-controllers#656]
### Description
I do not see any support for awilix for dependency Injection.

**Comment by warapitiya** [comment]
I think probably not only `awilix` but all other DIs. Like `TSyringe`.

Basically DI indipentant.

**Comment by thanipro** [comment]
I just found this package and this is how I am using it with TSyringe


`import { ClassConstructor, IocAdapter } from 'routing-controllers';
import { DependencyContainer } from 'tsyringe';

class TsyringeAdapter implements IocAdapter {
  // eslint-disable-next-line no-unused-vars,no-useless-constructor,no-empty-function
  constructor(private readonly TsyringeContainer: DependencyContainer) {}

  get<T>(someClass: ClassConstructor<T>): T {
    const childContainer = this.TsyringeContainer.createChildContainer();
    return childContainer.resolve<T>(someClass);
  }
}

export default TsyringeAdapter;`


And then in app.ts/index.ts  

` useContainer(new TsyringeAdapter(container));`

**Comment by attilaorosz** [comment]
You are free to use whatever DI lib you want as long as it complies with the typedi contracts, just as @thanipro showed. @NoNameProvided I think since the package provides the IocAdapter interface, we can close this.

**Comment by NoNameProvided** [comment]
Yes, as all above me said, currently routing-controllers don't depend on any specific typedi functionality. You can use any other lib with the `useContainer` helper.

In the future, we may use stricter integration which may disallow some other packages, but currently, we don't.
