### ISSUE TITLE
question: I have Service Decorator but got ServiceNotFoundError:

### ISSUE THREAD

**Issue by gudwnsdl88** [typestack/routing-controllers#672]
### Description

When I testing with mocha, other Services is working good and perfect.
But Specific Service(Just One Service) is not working **"only"** when I use Mocha .
In Product, typedi Working good too. 

I have this error message 

`ServiceNotFoundError: Service with "<UNKNOWN_IDENTIFIER>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.`

**Minimal code-snippet showcasing the problem**
 

this is my Service Code 

```ts
@Service()
export class ReservService {
	constructor(
		private readonly Res: ResRepo,
		private readonly User: UserRepo,
		private readonly Fac: FacRepo,
		private readonly Lesson: LessonRepo,
		private readonly Trans: TransRepo,
	) {}

	async getStandbyRes(partners_id: string): Promise<StandByResOutput> {

     ....  .... 
}
```

and this is my Test code 

```ts


const reservationService = Container.get<ReservService>(ReservService);

describe('Testing Reservation Service', () => {
	before(async () => {
		await database();
	});

	describe('Get Standby Reservation', () => {
.....
}

```

**Comment by NoNameProvided** [comment]
Do you import `reflect-metadata` in the first line of your test?

**Comment by gudwnsdl88** [comment]
> Do you import `reflect-metadata` in the first line of your test?

Yes sure in my service code

**Comment by huyintang** [comment]
Maybe it will not start the subscription Service process in the test file, you didn't start server, how about using ... = new ReservService()
