### ISSUE TITLE
Why do I get extra fields when I return directly

### ISSUE THREAD

**Issue by edcjian** [typestack/routing-controllers#673]
![image](https://user-images.githubusercontent.com/48635933/110481202-43206600-8122-11eb-8bb9-76cee42590f0.png)
![image](https://user-images.githubusercontent.com/48635933/110481250-53384580-8122-11eb-9972-79cf422ecba4.png)

**Comment by attilaorosz** [comment]
I assume toString and toJson return different things on your result object. Could you try to see what these methods produce?

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
