### ISSUE TITLE
question: get rid of class-validator

### ISSUE THREAD

**Issue by ifree92** [typestack/routing-controllers#676]
I have read sources a bit.
As I understand, you have a strong class-validator dependency.

For some cases I don't need validation and should just receive a dynamic object. Surely, I can just disable validation, but anyway I must install `class-validator` module.

Just wondering about strategy of further development of `routing-controllers`. Is it good and match your further expectations if we would set `class-validator` as an optional dependency (and amend the project accordingly?).

Wondering your thoughts. Thanks guys, you made a really good job in NodeJS + Typescript world 👍

**Comment by attilaorosz** [comment]
@ifree92 Currently class validator is a crucial part of the project. Maybe in the future it would be feasible to include a configuration to provide a validation library of your choice with maybe an adapter, or disable it completely, but for now I believe it should stay as this would be a breaking change. @NoNameProvided thoughts?

**Comment by NoNameProvided** [comment]
The class-transformer and class-validator packages are integrated into routing-controller and this won't change. 

I don't understand what advantages would it bring if they would not be included? They are extremely lightweight: class-transformer has zero dependencies and class-validator only has two. 
 
In short, they won't be removed.
