### ISSUE TITLE
How to use vhost middleware?

### ISSUE THREAD

**Issue by woowjc2020** [typestack/routing-controllers#687]
import vhost = require('vhost')

**Comment by shinelp100** [comment]
Similarly encountered this problem, how to use？

**Comment by attilaorosz** [comment]
@woowjc2020 @shinelp100 
AFAIK routing-controller does not officially support this but if you could provide a bit more details on your needs then maybe we can come up with a solution using the existing functionality.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
