### ISSUE TITLE
question: How to get route.param on a RoutingController?

### ISSUE THREAD

**Issue by rafaell-lycan** [typestack/routing-controllers#688]
**I was trying to...**
 
 
I have a very specific scenario giving the following situation where I need to check on all my routes if a param `resourceType` exists or not  add some params to the `request` object giving my param value:

```js
app.param('resourceType', (req, res, next, resourceType) => {
  try {
     const { 
        getResource,
        getResources,
        getUsers,
        getRoles,
        updateRole,
        deleteRole,
        createSuperAdmin,
        deleteSuperAdmin,
      } = getResourceRoutersParams(resourceType);

    req.resource = {
        getResource,
        getResources,
        getUsers,
        getRoles,
        updateRole,
        deleteRole,
        createSuperAdmin,
        deleteSuperAdmin,
    };

     next();
    } catch (e) {
      logger.error(e);
      throw new ResourceNotFoundError();
    }
})
```
I'm solving the issue using the [`app.param`](http://expressjs.com/en/api.html#app.param) API

**The problem:**
 

All my routes contain a `:resourceType` param:

- GET `/resources/:resourceType/:resourceId/users`
- GET `/resources/:resourceType/roles`
- GET/PUT/DELETE `/users/:userId/:resourceType`
- GET/PUT/DELETE `/users/:userId/:resourceType/:resourceId`

There is any way to implement it other than adding a middleware for each route?

**Comment by drpym** [comment]
What i have done in the past, is I create a class:
```ts
class Params {
  @IsUUID()
  resourceType:  string; 
}
```

 then you can extends the class for other params. 

```ts
class OtherParam extends Params {
 userId: string
}
```

then on your controller
```ts
class Controller {
  @Get("something")
  dosomething(@Params() params: Params) {
  }
}
```

**Comment by rafaell-lycan** [comment]
@drpym I got your point, but is not the same idea, the `app.param` API works mostly like middleware and honestly, I don't wanna implement a middleware, although my `ResourcesController` needs it for each route, the `UsersController` only needs on 2 routes, so I was wondering if there's an easier way for it.

**Comment by drpym** [comment]
Ah ok. That makes sense. Sorry for the wrong answer 🤦🏾 If you find a more elegant solution I would be curious as to what you do.

**Comment by attilaorosz** [comment]
@rafaell-lycan You might be able to use a global middleware that does this for you. https://github.com/typestack/routing-controllers#global-middlewares. Could you please check if this solves your issue?

**Comment by attilaorosz** [comment]
Closing as stale.
