### ISSUE TITLE
feature: Restify Support

### ISSUE THREAD

**Issue by rafaell-lycan** [typestack/routing-controllers#689]
### Description

Hi guys, 

At the moment the project only supports express and koa and at my company, we're testing Restify instead of Express giving we have manly APIs and Restify response its a bit faster than Express overall. I've checked the codebase and I found the `BaseDriver` so I'd like to ask why not implement one?

#### Why Restify?

Restify uses the lib [find-my-way](https://www.npmjs.com/package/find-my-way) underneath which is much faster to load routes and process them:

**Koa:** 41324 req/sec
**Restify:** 34424 req/sec
**Express:** 11795 req/sec

[Benchmarks provided by Fastify](https://www.fastify.io/benchmarks/)

### Proposed solution

Does it make sense for more people at the moment? 

Regarding maintaining it, once we have the first draft we can potentially start planning a roadmap, so I'd suggest opening a poll or something regarding it as it might be a benefit for many other developers.

Cheers.

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/feature-ideas) and someone from the community may be able to help.
