### ISSUE TITLE
question: Can you help me figure out why I'm getting this NotFoundError?

### ISSUE THREAD

**Issue by whylock** [typestack/routing-controllers#690]
**I was trying to...**
 
I am trying to perform some basic Postman tests on my routes.  After successfully finding a user and verifying a password hash, I am attempting sign a JWT and this is where I'm encountering a NotFoundError.

```typescript
    @Post("/login")
    async login(@Body() body: any, @Req() req: Request, @Res() res: Response, next: NextFunction) {
        const { email, password } = body;
        await this.userRepository
            .findOne({ where: { email: email } })
            .then((user) => {
                const match = bcrypt.compare(password, user.passwordHash);

                if (match) {
                    signJWT(user, (_error, token) => {
                        if (_error) {
                            return res.status(401).json({
                                message: "Unable to sign to JWT",
                                error: _error,
                            });
                        } else if (token) {
                            return res.status(200).json({
                                message: "Auth Successful",
                                token,
                                user: user,
                            });
                        }
                    });
                }
            })
            .catch((error) => {
                res.status(401).json({
                    message: "The information you entered does not match any profile.",
                    error: error,
                });
            });
    }
```

```typescript
function signJWT(user: User, callback: (error: Error | null, token: string | null) => void): void {
    let timeSinceEpoch = new Date().getTime();
    let expirationTime = timeSinceEpoch + Number(config.server.token.expireTime) * 100000;
    let expirationTimeInSeconds = Math.floor(expirationTime / 1000);

    logging.info(NAMESPACE, `Attempting to sign token for User with ID: ${user.id}`);
    try {
        jwt.sign(
            {
                email: user.email,
            },
            config.server.token.secret,
            {
                issuer: config.server.token.issuer,
                algorithm: "HS256",
                expiresIn: expirationTimeInSeconds,
            },
            (error, token) => {
                if (error) {
                    callback(error, null);
                } else if (token) {
                    callback(null, token);
                }
            }
        );
    } catch (error) {
        logging.error(NAMESPACE, error.message, error);
        callback(error, null);
    }
}
```

**The problem:**
As briefly stated above, I'm able to successfully make a request to my login controller, find a user, and verify a password with a hash. However, I'm encountering the following NotFoundError while attempting to sign a JWT with the function above. The function runs until the logging function just before the try/catch. The error is below. I included the logging function output in the code snippet just to show that it is happening. 

```error
[2021-03-28T01:28:08.926Z] [INFO] [Authentication] Attempting to sign token for User with ID: 1
Error
    at new HttpError (/dev/server/node_modules/src/http-error/HttpError.ts:16:18)
    at new NotFoundError (/dev/server/node_modules/src/http-error/NotFoundError.ts:10:5)
    at ExpressDriver.handleSuccess (/dev/server/node_modules/src/driver/express/ExpressDriver.ts:324:15)
    at /dev/server/node_modules/src/RoutingControllers.ts:164:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by angelxmoreno** [comment]
take a look at https://github.com/typestack/routing-controllers#controlling-empty-responses it states 
`
If your controller returns void or Promise<void> or undefined it will throw you 404 error. To prevent this if you need to specify what status code you want to return using @OnUndefined decorator.
`

May I suggest cleaning up your code a bit as it is a little confusing and seems like a frankenstein of different code snippets. It would make debugging much easier. For example, your route function should either be async or work with thenables but not both.  Your `signJWT` should be promisified. 

May I also suggest you look into the @CurrentUser decorator which is super useful in my opinion because it extrapolates logic you do not need to code so less bugs.

**Comment by whylock** [comment]
> take a look at https://github.com/typestack/routing-controllers#controlling-empty-responses it states
> `If your controller returns void or Promise<void> or undefined it will throw you 404 error. To prevent this if you need to specify what status code you want to return using @OnUndefined decorator.`
> 
> May I suggest cleaning up your code a bit as it is a little confusing and seems like a frankenstein of different code snippets. It would make debugging much easier. For example, your route function should either be async or work with thenables but not both. Your `signJWT` should be promisified.
> 
> May I also suggest you look into the @currentuser decorator which is super useful in my opinion because it extrapolates logic you do not need to code so less bugs.

Thanks! I'll try this out and see if I can get it work. I appreciate the suggestion on the code. I'll definitely refactor soon. I just want to get code that works, and that I understand why/how it works first. I'm just trying to learn by doing here.

**Comment by whylock** [comment]
> take a look at https://github.com/typestack/routing-controllers#controlling-empty-responses it states
> `If your controller returns void or Promise<void> or undefined it will throw you 404 error. To prevent this if you need to specify what status code you want to return using @OnUndefined decorator.`
> 
> May I suggest cleaning up your code a bit as it is a little confusing and seems like a frankenstein of different code snippets. It would make debugging much easier. For example, your route function should either be async or work with thenables but not both. Your `signJWT` should be promisified.
> 
> May I also suggest you look into the @currentuser decorator which is super useful in my opinion because it extrapolates logic you do not need to code so less bugs.

I took a look at that @currentuser decorator. I don't understand how it works. I appreciate the suggestion, but I'll just try to get something functional with what I understand.

**Comment by loriswit** [comment]
@whylock Your `login` function does not return anything, so you get a 404 error by default according to the docs. The only things being returned are inside the callback function, but you are ignoring its return value.

`@CurrentUser` is probably of no use in this scenario. You would typically need it to identify an already logged in user.

Anyway, I must agree that your code is somewhat messy. Try avoiding callbacks and only use async-await and try-catch instead (`jwt.sign` is probably synchronous anyway).

**Comment by whylock** [comment]
> @whylock Your `login` function does not return anything, so you get a 404 error by default according to the docs. The only things being returned are inside the callback function, but you are ignoring its return value.
> 
> `@CurrentUser` is probably of no use in this scenario. You would typically need it to identify an already logged in user.
> 
> Anyway, I must agree that your code is somewhat messy. Try avoiding callbacks and only use async-await and try-catch instead (`jwt.sign` is probably synchronous anyway).

Hey, I've been trying to play with for a while and just can't wrap my head around signing this jwt and giving the controller something to return so it doesn't throw an error. Hate to be a bother, but could you suggest something? I'm still learning so I've kinda thrown myself into the deep end here.

**Comment by jotamorais** [comment]
> > @whylock Your `login` function does not return anything, so you get a 404 error by default according to the docs. The only things being returned are inside the callback function, but you are ignoring its return value.
> > 
> > `@CurrentUser` is probably of no use in this scenario. You would typically need it to identify an already logged in user.
> > 
> > Anyway, I must agree that your code is somewhat messy. Try avoiding callbacks and only use async-await and try-catch instead (`jwt.sign` is probably synchronous anyway).
> 
> Hey, I've been trying to play with for a while and just can't wrap my head around signing this jwt and giving the controller something to return so it doesn't throw an error. Hate to be a bother, but could you suggest something? I'm still learning so I've kinda thrown myself into the deep end here. I appreciate the response here either way.
> 


You can use `AuthorizationChecker` and perform the JWT validation and user lookup in your DB, for example. Check this comment: https://github.com/typestack/routing-controllers/issues/531#issuecomment-578822912


and this sample: https://codesandbox.io/s/routing-controllers-authorizationchecker-559-3ekl0

**Comment by loriswit** [comment]
@whylock To handle a login request with a username/password and send a JWT back to the user, I would probably write something along these lines:
```ts
@Get("/login")
async login(@Req() req: Request): Promise<UserWithToken> {

    const credentials = auth(req) // basic-auth
    if (!credentials)
        throw new UnauthorizedError("Basic authentication required")

    const user = await this.userRepository.findOne({ where: { email: credentials.name } })
    if (!user || !await bcrypt.compare(credentials.pass, user.passwordHash))
        throw new UnauthorizedError("Wrong username and/or password")

    const token = jwt.sign(/* ... */)

    return { user, token }
}
```
(Here I put everything into a single controller method. Of course, you can still split that code into multiple middlewares/functions to keep things a bit cleaner).

**Comment by whylock** [comment]
Thank you! This has been very helpful. I'm going to close the question now.
