### ISSUE TITLE
fix: koa dependencies are outdated

### ISSUE THREAD

**Issue by loriswit** [typestack/routing-controllers#692]
### Description
**koa-router**, **koa-multer** and **kcors** are not the recommended packages anymore.
They should be changed to **@koa/router**, **@koa/multer** and **@koa/cors** respectively.

Note that koa-router actually seems to be a mirror of @koa/router, so it might not really be an issue, but koa-multer has been marked as deprecated, and kcors hasn't been updated for 3 years.

Related issues: #428 #435 #534 #604

**Comment by attilaorosz** [comment]
Fixed in #948

**Comment by loriswit** [comment]
> Fixed in #948

None of the issues I mentioned have been fixed in this PR. These packages are still outdated.

**Comment by loriswit** [comment]
I haven't tested it myself now, but I'm pretty sure that this requires some change to the source code as well, since these packages are being dynamically imported in some place. For instance:

https://github.com/typestack/routing-controllers/blob/d43bf9a64096d1824de90f304b86d9cb474e7562/src/driver/koa/KoaDriver.ts#L49

https://github.com/typestack/routing-controllers/blob/d43bf9a64096d1824de90f304b86d9cb474e7562/src/driver/koa/KoaDriver.ts#L379

https://github.com/typestack/routing-controllers/blob/d43bf9a64096d1824de90f304b86d9cb474e7562/src/driver/koa/KoaDriver.ts#L396

They are also referenced in the readme:
https://github.com/typestack/routing-controllers/blob/139004207aab3c8950d224a0b1a2f678a445f79f/README.md?plain=1#L103

**Comment by attilaorosz** [comment]
Indeed, that was an oversight from my end.
