### ISSUE TITLE
question: Are Cookies supported

### ISSUE THREAD

**Issue by nadunindunil** [typestack/routing-controllers#694]
**I was trying to...**
send cookies clear and cookies set from the application side

**The problem:**
but it didn't return to the frontend

does routing controllers support cookies?
if so does this code work?

```  
      response.clearCookie('AWSELBAuthSessionCookie-0', { path: '/' });	
      response.clearCookie('AWSELBAuthSessionCookie-1', { path: '/' });
```

**Comment by attilaorosz** [comment]
@nadunindunil It should work, I'm using it in production. When you say it didn't return the frontend what do you exactly mean?

**Comment by attilaorosz** [comment]
Closing as stale.
