### ISSUE TITLE
question: Why the deserialization is not the same between routing-controller and deserializeArray method

### ISSUE THREAD

**Issue by tblazz** [typestack/routing-controllers#704]
Hi, 

I am a total beginner with your framework but I discovered something quite interesting that I can't figure it out. 

I have the following controller :

```
import { deserializeArray } from 'class-transformer';

@Controller()
export class BetController {
	@Post('/bet/batch')
	post(@Body() bets: Array<TestBet>) {
		console.log(bets[0])
		console.log("//////")
		const test = deserializeArray(TestBet, JSON.stringify(bets))
		console.log(test[0])
		return 'Test Only';
	}
	@Get('/events')
	getAll() {
		return 'This action returns all users';
	}
}
```
**The problem:**
You can see here after the console logs : 
```
i  functions: Beginning execution of "webApi"
>  { eventId: '686314', bet: { __type: 'MATCH_WINNER', winner: 'Away' } }
>  //////
>  TestBet {
>    eventId: '686314',
>    bet: BetMatchWinnerApi { winner: 'Away' }
>  }
```

Why bets[0] is different than test[0] ? (I saw in your documentation that @Body uses also class-transformer.)

Thank you !
Thomas

**Comment by attilaorosz** [comment]
@tblazz This seems to be a bug. It seems like all array-like body params are handled as string arrays, so your request just transforms to a simple object.

**Comment by attilaorosz** [comment]
Closing in favor of #612
