### ISSUE TITLE
auto validtion not working 

### ISSUE THREAD

**Issue by hatemragab** [typestack/routing-controllers#705]
```
@JsonController()
class UserController {
    @Post('/login')
    login(@Body({validate: true}) user: User) {
        console.log('this is a valid body');
        return 'success!!!';
    }
}

class User {
    @IsEmail()
    email: string;

    @MinLength(6)
    password: string;
}

createExpressServer({
    controllers: [UserController]
}).listen(3000);
```
when ever I send the request it reply 
 console.log('this is a valid body');
although 
this my config 
```
useExpressServer(app, {
  cors: true,
  validation: true,
  classTransformer: true,
  routePrefix: '/api/v1',

  controllers: [UserController],
});
```

**Comment by drpym** [comment]
I just used your example. 

```ts
import 'reflect-metadata';
import {
  JsonController,
  Post,
  Body,
  createExpressServer,
} from 'routing-controllers';
import { IsEmail, MinLength } from 'class-validator';

class User {
  @IsEmail()
  email: string = '';

  @MinLength(6)
  password: string = '';
}

@JsonController()
class UserController {
  @Post('/login')
  login(@Body({ validate: true }) user: User) {
    console.log('this is a valid body');
    return 'success!!!';
  }
}

createExpressServer({
  controllers: [UserController],
}).listen(3000);
```

and it worked as expected. Can you share more?

**Comment by bratanon** [comment]
@drpym Im having the same problem. 

Send `["asd"]` with Content-Type application/json

It will print success.

**Comment by drpym** [comment]
@bratanon  ah yes this problem. I have a simple patch that should solve the problem. *not throughly tested yet*

```ts
@JsonController()
class UserController {
  @Post('/login')
  login(@Body({ validate: true }) user: User) {
    if (!(user instanceof User)) {
      //do something to show an error
    }
    console.log('this is a valid body');
    return 'success!!!';
  }
}

```

**Comment by bratanon** [comment]
@drpym Thanks, guess that will work and in the if statement thrown a `BadRequestError`. I will go for that solution in my project for now. 

However it is not solving the root issue. But I doubt that the issue is on routing-controllers either. Feels more like a class-transformer issue, or even class-validator issue. 

Havent digged to far into this.

**Comment by drpym** [comment]
I haven't either. it's on my list of things though if no one else figures it out first

**Comment by hatemragab** [comment]
finally fix i have to import 'reflect-metadata'; in each controller at first line
