### ISSUE TITLE
fix: "message": "Cannot read property 'prototype' of undefined",

### ISSUE THREAD

**Issue by wghglory** [typestack/routing-controllers#709]
### Description

@QueryParams() will break code under Express server. I have to change to @QueryParam one by one. The error is like 

`"message": "Cannot read property 'prototype' of undefined",`

```
"name": "TypeError",
"message": "Cannot read property 'prototype' of undefined",
"stack": "TypeError: Cannot read property 'prototype' of undefined\n at /projectFolder/node_modules/src/ActionParameterHandler.ts:110:32\n at Array.map (<anonymous>)\n at ActionParameterHandler.normalizeParamValue (/projectFolder/node_modules/src/ActionParameterHandler.ts:105:28)\n at ActionParameterHandler.handle (/projectFolder/node_modules/src/ActionParameterHandler.ts:39:24)\n at /projectFolder/node_modules/src/RoutingControllers.ts:114:43\n at Array.map (<anonymous>)\n at RoutingControllers.executeAction (/projectFolder/node_modules/src/RoutingControllers.ts:114:8)\n at /projectFolder/node_modules/src/RoutingControllers.ts:82:23\n at routeHandler (/projectFolder/node_modules/src/driver/express/ExpressDriver.ts:165:14)\n at Layer.handle [as handle_request] (/projectFolder/node_modules/express/lib/router/layer.js:95:5)"
```

```ts
  @Get('/cloud/azure/subscriptions')
  // getAll(@QueryParam('limit') limit: number, @QueryParam('offset') offset: number) {
  getAll(@QueryParams() limit: any) {
    return { test: 1 };
  }
```

My Environment:

```
  "dependencies": {
    "@types/body-parser": "^1.19.0",
    "@types/express": "^4.17.11",
    "@types/faker": "^5.5.2",
    "@types/lodash": "^4.14.168",
    "@types/multer": "^1.4.5",
    "body-parser": "^1.19.0",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "faker": "^5.5.3",
    "lodash": "^4.17.21",
    "multer": "^1.4.2",
    "reflect-metadata": "^0.1.13",
    "routing-controllers": "^0.9.0",
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.2.4"
  }
```

**Comment by pavan-jaju** [comment]
Is it resolved?

**Comment by attilaorosz** [comment]
@wghglory I cannot reproduce this. Could you please include a sample query to test with? `?asd=asd&asd2=asd2` works as expected for me in this scenario:

```typescript
@JsonController('/test')
class Cnt {
    @Get('/test')
    async route(@QueryParams() limit: any) {
        console.log(limit);

        return null;
    }
}
```

**Comment by wghglory** [comment]
> @wghglory I cannot reproduce this. Could you please include a sample query to test with? `?asd=asd&asd2=asd2` works as expected for me in this scenario:
> 
> ```ts
> @JsonController('/test')
> class Cnt {
>     @Get('/test')
>     async route(@QueryParams() limit: any) {
>         console.log(limit);
> 
>         return null;
>     }
> }
> ```



> @wghglory I cannot reproduce this. Could you please include a sample query to test with? `?asd=asd&asd2=asd2` works as expected for me in this scenario:
> 
> ```ts
> @JsonController('/test')
> class Cnt {
>     @Get('/test')
>     async route(@QueryParams() limit: any) {
>         console.log(limit);
> 
>         return null;
>     }
> }
> ```

Would you please check this repo? https://github.com/wghglory/routing-controllers-bug-report-demo. It doesn't work using your query as well. My query is like `http://localhost:9999/api/v1/tenants?limit=10&offset=10`

**Comment by attilaorosz** [comment]
@wghglory I'm not gonna lie, I spent a good hour on debugging this when I relized you are missing `"emitDecoratorMetadata": true` from your tsconfig.json. Could you please try with that added?

**Comment by wghglory** [comment]
@attilaorosz It works with `emitDecoratorMetadata`! I'm sorry that it takes you such a long time to debug this. And thank you so much for helping me to solve this issue!
