### ISSUE TITLE
question: Where is the userRepository ?  And how to add Repository or createConnect() ?

### ISSUE THREAD

**Issue by zellkon** [typestack/routing-controllers#714]
I was trying to add UserController 

@Get('/users')
  async getAll(@Req() request: any, @Res() response: any) {
    createConnection();
    const users = await getRepository(User).find({
      select: ['id', 'name', 'email', 'dob', 'gender', 'phone'],
      relations: ['addresses']
    });

    return response.send(users);
  }

**The problem:**
The document like : 
 @Get('/users')
  getAll() {
    return userRepository.findAll();
  }

So Where is the userRepository ? How to import this ? 
Thank typeStack !

**Comment by apgapg** [comment]
User repository in docs is just an example to show how it works. They havent provided the actual implementation of user repo because its not needed to explain this docs
