### ISSUE TITLE
question: is there a plan for v1 ?

### ISSUE THREAD

**Issue by mcnally** [typestack/routing-controllers#717]
As per the title, just wondering if there are plans to publish v1 ?

Happy to contribute if there are things needed to get there

I had a dig around and found an old issue referencing v1 but nothing since

**Comment by attilaorosz** [comment]
@NoNameProvided Any inputs? I believe we can aim for V1 in the near future but we have to discuss the general scope first.

**Comment by NoNameProvided** [comment]
Generally yes, we should reach v1 but I think there is quite a few stuff to iron out before releasing 1.0. If the project is active again, we can start a discussion on what we should include in it and what goals/criteria we set.

One big breaking change I can think of is the updated configuration of class-validator/class-transformer for sane defaults. There are other things as well, but we would have to catch up on the project status.
