### ISSUE TITLE
question: How to catch error and handler error ? 

### ISSUE THREAD

**Issue by zellkon** [typestack/routing-controllers#721]
**I was trying to...**
I was trying to catch error from mySQL 
![image](https://user-images.githubusercontent.com/20116654/118097403-d6b13400-b3fc-11eb-8491-8921f6be3d8a.png)

**The problem:**
but middlesaware ErrorrHandle not run, this i my ErrorHandler.ts
![image](https://user-images.githubusercontent.com/20116654/118097513-ff392e00-b3fc-11eb-8f74-83003adc3ec0.png)

Thank all !

**Comment by attilaorosz** [comment]
@zellkon Could you share your controller and how you do the promise?

**Comment by zellkon** [comment]
> @zellkon Could you share your controller and how you do the promise?

I fixed the error, thank you!
