### ISSUE TITLE
question: JSON file based routing possible ?

### ISSUE THREAD

**Issue by octalpixel** [typestack/routing-controllers#723]
I want to  on implementing JSON based routing , essentially trying to use the JSON file to configure all that routes and middleware. 
Does anyone know it's possible with this library ?

**Comment by attilaorosz** [comment]
This seems like an interesting idea but that would basically invalidate the reason for using controller classes in general. @NoNameProvided what do you think?

**Comment by NoNameProvided** [comment]
This is not possible currently, and I agree with @attilaorosz, this is out of scope. This lib is about defining routes with decorators.

As a side note, in the future, we may expose internal meta-data in a structured way, but that would not help here.
