### ISSUE TITLE
feature: socket-controllers in routing-controllers

### ISSUE THREAD

**Issue by stingers** [typestack/routing-controllers#735]
### Description
I want just to know if your still planning to integrate socket-controllers  in routing-controllers.
I'm sure mix  the both will amazing et be double or triple  routing-controllers downloads

Thanks

**Comment by NoNameProvided** [comment]
Yes, this is out of scope for the project. Closing as wontfix.

**Comment by stingers** [comment]
I don't think It is out of scope for the project.

**Comment by NoNameProvided** [comment]
There is nothing preventing you from using both in a project. It won't be merged officially into the project.

**Comment by stingers** [comment]
'There is nothing preventing you from using both in a project': I know, but put both in only one  project can be easy to get like All in one, and it may be an opportunity to think about maintaining  socket-controllers includes than routing-controllers
