### ISSUE TITLE
fix:  Hostname spoofing via backslashes in URL

### ISSUE THREAD

**Issue by AdelUnito** [typestack/routing-controllers#751]
### Description
npm security audit suggesting moderate vulnerability

```ts
[moderate] Hostname spoofing via backslashes in URL
 - dependencies (optional): routing-controllers>koa-router>urijs

```

### Expected behavior
Solid & Secure library

### Actual behavior
Moderate security threat due to a dependency

**Comment by attilaorosz** [comment]
Koa-router has been switched to @koa/router
