### ISSUE TITLE
Sending a JSON body in a HTTP error response

### ISSUE THREAD

**Issue by pra-richardg2-sportsbet** [typestack/routing-controllers#758]
I was trying to send a response with a JSON body but with a 422 HTTP error code.

the only way I can see of sending a 422 is to throw a `HttpError`. The issue is that `HttpError()` only takes a status code and a message string whereas I would like to send a JSON body detailing that error, seeing as it's using `@JSONController`. 

I want to do this:

```
throw new HttpError(422, {
  message: 'Validation error',
  errorList: errors as ValidationError[]
})
```

Is there an alternative way of doing this? 

I can see there is a `@OnUndefined(statusCode: number)` for setting the status code but that doesn't help as I need to return a body in the response.

**Comment by vs4vijay** [comment]
You need to create your own error class and return JSON as per your expectation: 

Link: https://github.com/typestack/routing-controllers#throw-http-errors

Example:

```class DbError extends HttpError {
  public operationName: string;
  public args: any[];

  constructor(operationName: string, args: any[] = []) {
    super(500);
    Object.setPrototypeOf(this, DbError.prototype);
    this.operationName = operationName;
    this.args = args; // can be used for internal logging
  }

  toJSON() {
    return {
      status: this.httpCode,
      failedOperation: this.operationName,
    };
  }
}
```

**Comment by pra-richardg2-sportsbet** [comment]
@vs4vijay Ah, great, thanks for that I missed it. I'll give that a go 👍

**Comment by attilaorosz** [comment]
Seems like a solution was provided. Closing it for now. Feel free to reopen if needed.
