### ISSUE TITLE
Any HttpError thrown shows 500 server error when the api is called

### ISSUE THREAD

**Issue by aftabaig** [typestack/routing-controllers#760]
### Description
When using any HttpError extended error class, it should throw appropriate error message at the client.
But instead it throws 500.

**Minimal code-snippet showcasing the problem**
 

```ts
throw new NotFoundError("Site not found");
```

### Expected behavior
To client, it should show a status of 404 and a json message
{
  "name": "NotFoundError",
  "message": "Site not found."
}

### Actual behavior
It throws a 500 error with html in response

**Comment by biton-ron** [comment]
I was facing the same issue, you should turn off the default error handler like so:

![image](https://user-images.githubusercontent.com/51159662/147133861-d176673f-8e12-4f96-96e2-47a0e4d2b0f6.png)

and then you can create a custom error handle to send json instead as they explain in the README of this repo:

https://github.com/typestack/routing-controllers#error-handlers

**Comment by attilaorosz** [comment]
@aftabaig I cannot reproduce this. I've tried the following scenario:

```typescript
process.env.NODE_ENV = 'production';

import {createExpressServer, Get, JsonController, NotFoundError} from 'routing-controllers';

@JsonController('/test')
class Cnt {
    @Get('/test')
    async route() {
        throw new NotFoundError("Site not found");
    }
}

const app = createExpressServer({controllers: [Cnt]});
app.listen(3001);
console.log('Running');
```
When called, this is the response:
```json
{
    "name": "NotFoundError",
    "message": "Site not found"
}
```

If I use Controller instead of JsonController this is the response as simple text:
```
Site not found
```

To be honest I don't see a scenario where routing-controller could return you HTML. Could you share a bit more about your use case?
