### ISSUE TITLE
Please update class-transformer dependency to the latest version

### ISSUE THREAD

**Issue by slavafomin** [typestack/routing-controllers#783]
Hello!

Thank you for this great library!

However, right now it requires `class-transformer@0.3.1` (exact version `0.3.1`) as a peer dependency. This prevents my project from using the latest version of the `class-transformer` (which is `0.4.0`).

This generates the following error on `npm install`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @acme/project
npm ERR! Found: class-transformer@0.4.0
npm ERR! node_modules/class-transformer
npm ERR!   class-transformer@"0.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer class-transformer@"^0.3.1" from routing-controllers@0.9.0
npm ERR! node_modules/routing-controllers
npm ERR!   routing-controllers@"0.9.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Would you be so kind to update `class-transformer` dependency to the latest version?

Thanks!

**Comment by slavafomin** [comment]
The same issue is with `class-validator`.

Also, it would be **much easy** to avoid these kind of issues if you would switch to a stable semver range (major version > 0) because it would allow to match dependencies in a more relaxed manner.

**Comment by SandraShklyaeva** [comment]
Dependency update sounds even more urgent because of the latest security vulnerability fixes for the following packages:
class-validator => 0.13.2 [(changelog)](https://github.com/typestack/class-validator/blob/develop/CHANGELOG.md)
class-transformer => 0.5.0 ([changelog](https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md))

**Comment by biton-ron** [comment]
Same issue for us, a fix will be for a great help. 

Thanks!

**Comment by juniopereirab** [comment]
Same problem here... 

TypeError: class transformer 1.classToPlain is not a function

**Comment by RatakondalaArun** [comment]
I there any workaround for this?

**Comment by amellalkamel** [comment]
+1 
this is a serious issue

**Comment by GisCat** [comment]
Is there any update ?

**Comment by seblaz** [comment]
Hi @NoNameProvided @attilaorosz, would you mind having a look at the pr? Thanks!

**Comment by zSakuraEvilz** [comment]
Is there no new update for this issue?

**Comment by attilaorosz** [comment]
Seems like there are no real breaking changes in terms of class-transformer usage (I might be wrong here) so you can just update the package since it is only a peer dependency.

**Comment by biton-ron** [comment]
> Seems like there are no real breaking changes in terms of class-transformer usage (I might be wrong here) so you can just update the package since it is only a peer dependency.

We're working with TypeScript and we get some type differences that reflect breaking changes in the library.

**Comment by KillaSushi** [comment]
> Is there any workaround for this?
> 
> I want to use `exposeDefaultValues` which was added in [v0.3.2](https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md#added-1)

I just found a workaround which seems to work, you can install two versions of the same package using an alias:
- `npm install class-validator12@npm:class-validator@0.12.2`
- `npm install class-transformer3@npm:class-transformer@0.3.1`

Never saw that syntax before, but this is working for me.

**Comment by pfgallagher** [comment]
> > Is there any workaround for this?
> > I want to use `exposeDefaultValues` which was added in [v0.3.2](https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md#added-1)
> 
> I just found a workaround which seems to work, you can install two versions of the same package using an alias:
> 
> * `npm install class-validator12@npm:class-validator@0.12.2`
> * `npm install class-transformer3@npm:class-transformer@0.3.1`
> 
> My package.json now looks like this:
> 
> ```
>         "class-transformer": "^0.5.1",
>         "class-transformer3": "npm:class-transformer@^0.3.1",
>         "class-validator": "^0.13.2",
>         "class-validator12": "npm:class-validator@^0.12.2",
> ```
> 
> Never saw that syntax before, but this is working for me.

@KillaSushi - Could you please share your full package.json? Is there additional config you needed to do to point at the aliases? Doesn't seem to be doing the trick on my end.

**Comment by KillaSushi** [comment]
> > > Is there any workaround for this?
> > > I want to use `exposeDefaultValues` which was added in [v0.3.2](https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md#added-1)
> > 
> > 
> > I just found a workaround which seems to work, you can install two versions of the same package using an alias:
> > 
> > * `npm install class-validator12@npm:class-validator@0.12.2`
> > * `npm install class-transformer3@npm:class-transformer@0.3.1`
> > 
> > My package.json now looks like this:
> > ```
> >         "class-transformer": "^0.5.1",
> >         "class-transformer3": "npm:class-transformer@^0.3.1",
> >         "class-validator": "^0.13.2",
> >         "class-validator12": "npm:class-validator@^0.12.2",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Never saw that syntax before, but this is working for me.
> 
> @KillaSushi - Could you please share your full package.json? Is there additional config you needed to do to point at the aliases? Doesn't seem to be doing the trick on my end.

There is no additional config in my package.json. My package-lock.json looks like this, it is important that both versions do appear. That should be the case after running `npm install class-validator12@npm:class-validator@0.12.2` (I'm using Node 16). Is that your case?
```
 "node_modules/class-validator": {
            "version": "0.13.2",
            "resolved": "https://registry.npmjs.org/class-validator/-/class-validator-0.13.2.tgz",
            "integrity": "sha512-yBUcQy07FPlGzUjoLuUfIOXzgynnQPPruyK1Ge2B74k9ROwnle1E+NxLWnUv5OLU8hA/qL5leAE9XnXq3byaBw==",
            "dependencies": {
                "libphonenumber-js": "^1.9.43",
                "validator": "^13.7.0"
            }
        },
        "node_modules/class-validator12": {
            "name": "class-validator",
            "version": "0.12.2",
            "resolved": "https://registry.npmjs.org/class-validator/-/class-validator-0.12.2.tgz",
            "integrity": "sha512-TDzPzp8BmpsbPhQpccB3jMUE/3pK0TyqamrK0kcx+ZeFytMA+O6q87JZZGObHHnoo9GM8vl/JppIyKWeEA/EVw==",
            "dependencies": {
                "@types/validator": "13.0.0",
                "google-libphonenumber": "^3.2.8",
                "tslib": ">=1.9.0",
                "validator": "13.0.0"
            }
        },   
```

**Comment by FrancisBehnen** [comment]
If someone is forking, please let me know!

**Comment by JotaRaffalli** [comment]
Pls, update this 😮‍💨

**Comment by laujonat** [comment]
No temporary workarounds?

**Comment by spicemc** [comment]
Did you try my suggested workaround?

**Comment by Rasfuranku** [comment]
Trying to install `"routing-controllers": "^0.9.0"` in a new project, having the same issue.

**Comment by jstanislawczyk** [comment]
Please update it. It's hard to use it in new project when it has such big issue

**Comment by spicemc** [comment]
> If someone is forking, please let me know!

i [forked](https://github.com/typestack/routing-controllers/issues/900#issuecomment-1312529908) it. Feel free to use it in your projects.

**Comment by NoNameProvided** [comment]
Hi folks! I have added branch protection bypass to @attilaorosz so he will be able to handle this.

**Comment by FrancisBehnen** [comment]
> > If someone is forking, please let me know!
> 
> i [forked](https://github.com/typestack/routing-controllers/issues/900#issuecomment-1312529908) it. Feel free to use it in your projects.

Awesome, I've let the team know!
