### ISSUE TITLE
question: passport authentication callback

### ISSUE THREAD

**Issue by ghost** [typestack/routing-controllers#797]
Would the following code:

`
app.get('/auth/callback', passport.authenticate('oidc', {}));
`

Be equivalent to:
`
@Get('/auth/callback')
@UseBefore(passport.authenticate('oidc',{})
performCallback() {}
`

I'm trying to implement a callback middleware on a named route using controllers.

**Comment by angelxmoreno** [comment]
Why not make use of Routing-controllers' AuthChecker ?

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions/categories/q-a) and someone from the community may be able to help.
