### ISSUE TITLE
question:  Could you please push the 0.10.0-rc1 to npm ?

### ISSUE THREAD

**Issue by alexisvisco** [typestack/routing-controllers#798]
Hi :) 

Since query parameters with array are completely unusable in real world use case, could you please push to the npm registry the ` 0.10.0-rc1` tag so we can use a version of your library that works as intended ? 

Plus the readme is now also incorrect with the 0.9 versions.

**Comment by alexisvisco** [comment]
up

**Comment by talbSE** [comment]
this version add  the following support - https://github.com/typestack/routing-controllers/pull/677
which seems pretty important, any chance to publish a version or a fix ?

**Comment by tal130** [comment]
@jotamorais any plan on releasing this version?
The peer "peerDependencies" in version 0.9.0 contain security issues, so it's important to release this new version with the updated packages.

**Comment by attilaorosz** [comment]
Released
