### ISSUE TITLE
Making this specific plan is？

### ISSUE THREAD

**Issue by shinelp100** [typestack/routing-controllers#799]
https://github.com/typestack/routing-controllers/blob/cf1117dbb655220b544f86eb47d7b17392a4729f/src/index.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L220

**Comment by attilaorosz** [comment]
@shinelp100 Could you add more context to your question?

**Comment by angelxmoreno** [comment]
@shinelp100 your question isn't clear. Please close this if you resolved your issue or add more context
