### ISSUE TITLE
question: Global middleware before

### ISSUE THREAD

**Issue by OldStarchy** [typestack/routing-controllers#806]
**I was trying to...** create a middleware to preload the `context` with a `db` field and have it run before the routes / controllers

**The problem:**
I tried to use a middleware function

```typescript
import type { Middleware } from 'koa';
import Database from '../database/Database';

declare module 'koa' {
	export interface BaseContext {
		db: Database;
	}
}

export function databaseMiddleware(
	connectionString: string,
	dbName: string
): Middleware {
	const database = new Database(connectionString, dbName);

	return async function databaseMiddleare(ctx, next) {
		await database.connect();

		ctx.db = database;

		await next();
	};
}
```

```typescript
app.use(databaseMiddleware(process.env['DB_CONN_STRING'], process.env['DB_NAME']));
```

but this doesn't execute until after the controller's request handler runs, so I get an error because `ctx.db` is undefined.

I also tried making a class-based middleware

```typescript
import type { Context, Next } from 'koa';
import { KoaMiddlewareInterface, Middleware } from 'routing-controllers';
import Database from '../database/Database';

declare module 'koa' {
	export interface BaseContext {
		db: Database;
	}
}

@Middleware({ type: 'before' })
class DatabaseMiddleware implements KoaMiddlewareInterface {
	#database: Database;

	constructor(connectionString: string, dbName: string) {
		this.#database = new Database(connectionString, dbName);
	}

	async use(ctx: Context, next: Next) {
		await this.#database.connect();

		ctx.db = this.#database;

		await next();
	}
}

export default DatabaseMiddleware;
```

but I don't know how to implement this in `app`. If I pass it in via `createKoaServer` I don't know how to set the constructor parameters, and `app.use()` doesn't accept class objects.

```typescript
const app = createKoaServer({
	controllers: [
		HealthCheckController,
		...others,
	],
	// middlewares: [new DatabaseMiddleware(connectionString, dbName)], // Type 'DatabaseMiddleware' is not assignable to type 'string'.
	// middlewares: [DatabaseMiddleware], // runtime error due to params being `undefined`
});

// app.use(DatabaseMiddleware); // Error not assignalbe to parameter of type 'Middleware....
// app.use(new DatabaseMiddleware(connectionString, dbName)); // Error not assignalbe to parameter of type 'Middleware....
```

**Comment by OldStarchy** [comment]
For now, I'm using this

```typescript
(async () => {
	// stuff

	app.context.db = new Database(connectionString, dbName);
	await app.context.db.connect();

	app.listen(port);
})();
```

but thought I should use a middleware to provide access to the database as that's what `koa-session` does and I don't know any better. I've also been referencing [koa-mongo](https://github.com/nswbmw/koa-mongo/blob/master/index.js) which I _sorta_ copied but left out the `generic-pool` stuff because I don't think I need it.

**Comment by OldStarchy** [comment]
I also wanted to use [`koa-remove-trailing-slashes`](https://www.npmjs.com/package/koa-remove-trailing-slashes) but it seems to only run after the first request is already handled. I guess I'd have to convert it to a class-based middleware in order to add the `@Middleware({ type: 'before' })` decorator to it.

**Comment by attilaorosz** [comment]
@OldStarchy To be honest, create a new db connection on each request is a bit weird and not really efficient, but you could do this two ways. 
1. Create your own koa app, add your middleware and use useKoaServer after you added your own middleware.
2. Create the class based middleware and use environment variables for connection string or any other service that you can inject via the DI.

Let me know if this helps.

**Comment by OldStarchy** [comment]
Thanks, @attilaorosz, I got this working using `useKoaServer`.
I created just one DB connection and used the middleware to add it to the context for each request.
