### ISSUE TITLE
question: routing-controllers: How can I Had dynamic parameter in middleware call

### ISSUE THREAD

**Issue by mduvernon** [typestack/routing-controllers#808]
<div class="s-prose js-post-body" itemprop="text">
                
<p>I have followed the tutorial from:</p>
<ul>
<li><a href="https://github.com/typestack/routing-controllers#creating-your-own-express-middleware" rel="nofollow noreferrer">https://github.com/typestack/routing-controllers#creating-your-own-express-middleware</a></li>
</ul>
<p>But I do not find a way to inject dynamic parameters in @<span>UseBefore</span>/@<span>UseAfter</span> middleware call
Like this:</p>
<pre class="lang-js s-code-block"><code class="hljs language-javascript">@<span class="hljs-title class_">Get</span>(<span class="hljs-string">"/something/:id"</span>)
@<span class="hljs-title class_">UseBefore</span>(<span class="hljs-title function_">checkPermission</span>([<span class="hljs-string">'ModuleName.canRead'</span>,<span class="hljs-string">'ModuleName.canWrite'</span>]))
<span class="hljs-title function_">getOne</span>(<span class="hljs-params">@Param(<span class="hljs-string">"id"</span>) id: number</span>) {
    <span class="hljs-comment">// ...</span>
}
</code></pre>
<p>I can do it by using url parse and db request, but it would be more efficient doing it directly</p>
<p>Can someone gide me doing this?</p>
<p>I found this :</p>
<ul>
<li><a href="https://github.com/typestack/routing-controllers/issues/338#issuecomment-348169164" rel="nofollow noreferrer">https://github.com/typestack/routing-controllers/issues/338#issuecomment-348169164</a></li>
</ul>
<p>But I dont know how to handle data from the Context "Class" and "{req, resp, next}" like this</p>
<pre class="lang-js s-code-block"><code class="hljs language-javascript"><span class="hljs-keyword">function</span> <span class="hljs-title function_">loggingMiddleware</span>(<span class="hljs-params">request: any, response: any, next?: (err?: any) =&gt; any</span>): any {
  <span class="hljs-variable language_">console</span>.<span class="hljs-title function_">log</span>(<span class="hljs-string">'do something...'</span>);
  <span class="hljs-title function_">next</span>();
}
</code></pre>
</div>``

**Comment by skopz356** [comment]
@mduvernon Did find you a solution?

**Comment by mduvernon** [comment]
Nope

**Comment by skopz356** [comment]
@mduvernon i found out that Request object to which you have access in middleware. Has property params where are stored these parameters. Hope it helps

**Comment by SchenZoo** [comment]
You can always wrap it around function and pass anything you want:

`
function loggingMiddleware(options){
  return function(request, response, next) {
    console.log('do something using options...',options);
    next();
  }
}
`

**Comment by attilaorosz** [comment]
I believe @SchenZoo provided a proper solution. Feel free to reopen if it’s not working for you.
