### ISSUE TITLE
Excessive parameter assignment

### ISSUE THREAD

**Issue by ron-tayler** [typestack/routing-controllers#865]
https://github.com/typestack/routing-controllers/blob/f9cf7e3cc0b6b4c2110d6a121ec166dd2da0e892/src/metadata-builder/MetadataBuilder.ts#L82-L84

I'am from Russia. I use Google Translate.

The assignment of the `option` parameter on line 84 does not make sense.
In the `ControllerMetadata` constructor, this procedure has already been performed

**Comment by ron-tayler** [comment]
https://github.com/typestack/routing-controllers/blob/f9cf7e3cc0b6b4c2110d6a121ec166dd2da0e892/src/metadata/ControllerMetadata.ts#L67-L72

**Comment by attilaorosz** [comment]
Thats a good point. Would you create a pull request?
