### ISSUE TITLE
Can we pass generics as a class Type to @Body?

### ISSUE THREAD

**Issue by AbdulBari5** [typestack/routing-controllers#903]
Hello,
My senior is building a BaseController that implements the basic crud. While checking the request body we are passing a Class as a generic into BaseController in order to make it dynamic. Since the BaseController implements different controllers. Like RoleController, so RoleBodyData should be passed into BaseController as a generic for validation. But the problem is that @Body decorator doesn't respond to the generic. It is unable to get the Class somehow. We are stuck in the situation.
Your help is much appreciated.

Best Regards,
Abdul Bari

**Comment by attilaorosz** [comment]
@AbdulBari5 could you provide an example repo?

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions) and someone from the community may be able to help.
