### ISSUE TITLE
question: Can we customize the response body using auto validating action parameters?

### ISSUE THREAD

**Issue by RirUchida** [typestack/routing-controllers#905]
Hello,
I want to remove "stuck" and "errors" from the response body created by auto validating action parameters.
How to customize the response body created by auto validating action parameters?
Here is the auto-generated response body.
```
{
"name": "BadRequestError",
"message": "Invalid queries, check 'errors' property for more info.",
"stack": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"errors": [
  {"target": {"userId": 1111},"value": 1111,"property": "userId","children": [],"constraints": {"max": "userId must not be greater than 1000"}}
],
"paramName": ""
}
```
Thank you

**Comment by attilaorosz** [comment]
@RirUchida the stack property should only be added if your node env is not prod. Could you please check if setting it helps?

**Comment by RirUchida** [comment]
I was able to remove the stack property with this setting. Tahnk you.
```
const app = createExpressServer({
  development: false, 
});
```
