### ISSUE TITLE
Use of middlewares in certain routes of a service.

### ISSUE THREAD

**Issue by aashumundrawinzo** [typestack/routing-controllers#917]
**I was trying to...**
const app: express.Application = createExpressServer({
                routePrefix: '/api',
                controllers: [__dirname + "/controllers/**"]
            });

            app.listen(3000, function () {
                console.log('App is listening on port 3000!');
            });

            app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
            app.use('/v1/offer/coupon', RequestContextMiddleware);
            app.use('/v1/offer/ticket', RequestContextMiddleware);

**The problem:**
My middleware is RequestContextMiddleware and i need use this middleware in all the routes starting with /v1/offer/coupon/(*). Is there a way in routing controllers to achieve this??

I am using typescript with nodejs.

**Comment by jiang000jie** [comment]
just have a try like this:
```
app.use('/v1/offer/coupon/*', RequestContextMiddleware);
```

**Comment by attilaorosz** [comment]
Closing this as stale.

If the issue still persists, you may open a new Q&A in the [discussions tab](https://github.com/typestack/routing-controllers/discussions) and someone from the community may be able to help.
