### ISSUE TITLE
Inconsistent behavior of @QueryParam after upgrading to 0.10.0

### ISSUE THREAD

**Issue by lkangd** [typestack/routing-controllers#968]
### Description

Hey guys,

I trying to update the version of routing-controller from 0.7.7 to 0.10.0, and I found a breaking change about `@QueryParam`.

**Minimal code-snippet showcasing the problem**
 

I have an route like this:
```ts
// ...
  @Post('/base/query-array')
  async baseQueryArray(@QueryParam('tags') tags: string[]) {
    console.log(tags)
    // ...
  }
// ...
```

and then I request the server from a web client like this:
```ts
request({ url: '/base/query-array?tags=%5B%221%22%2C%222%22%2C%223%22%5D' })
```

### Actual behavior

Under version 0.7.7, the printed result is `[1, 2, 3]`, 

but in 0.10.0, the result is `['[1, 2, 3]']`.

and I found this pr: https://github.com/typestack/routing-controllers/pull/677,

It changed the original behavior of `normalizeParamValue`, I pretty sure this is a breaking change, but I cannot find any change log about this.

![image](https://user-images.githubusercontent.com/14136052/208865684-1be56637-f3d7-47c9-8836-41bfbb85fa98.png)

### Expected behavior

Provide an option for `@QueryParam` to handle this situation.

**Comment by attilaorosz** [comment]
@lkangd thanks for the report! It indeed looks like a bug, I’ll check it soon

**Comment by attilaorosz** [comment]
@lkangd I checked this a bit deeper and I think this is actually the correct behavior. Since you only provide a single value for the query param, you get a single item in an array as string (as you defined in the controller).
I think the previous behavior was incorrect and it was treated as a bug.

**Comment by lkangd** [comment]
> @lkangd I checked this a bit deeper and I think this is actually the correct behavior. Since you only provide a single value for the query param, you get a single item in an array as string (as you defined in the controller). I think the previous behavior was incorrect and it was treated as a bug.

Ok, looks like we relying on a wrong implementation of @QueryParam, if I want to upgrade to v.0.10.0, I have to fix the current code implementation. Thanks for your reply, I'll close this issue.
