### ISSUE TITLE
fix: Property has no initializer and is not definitely assigned in the constructor.ts(2564)

### ISSUE THREAD

**Issue by hackermondev** [typestack/routing-controllers#977]
### Description
I am trying to use the class-validator in my project to validate JSON body requests sent to the API server. I get the error: ``Property 'search' has no initializer and is not definitely assigned in the constructor.ts(2564)`` in with my code-snippet below. I've been trying to debug this for the last hour or so with no success. I've used class-validator and routing-controllers in the past with everything working but it doesn't work for me now.

**Minimal code-snippet showcasing the problem**
```ts
export class GetAllUsersRequest {
    @QueryParam("search")
    search: string;
    @QueryParam("skip")
    skip: number;
    @QueryParam("limit")
    limit: number;
}

/*
Errors:

Property 'search' has no initializer and is not definitely assigned in the constructor.ts(2564)
Property 'skip' has no initializer and is not definitely assigned in the constructor.ts(2564)
Property 'limit' has no initializer and is not definitely assigned in the constructor.ts(2564)
*/

```

**Comment by attilaorosz** [comment]
Hi, this is a typescript error. You either need to disable strict property initialization in your tsconfig or define properties in your class with either ! or ?.

search!: string; // to indicate this cannot be undefined
Or
search?: string; // to indicate this can be undefined.
