### ISSUE TITLE
fix: peer dependency version difference (class-validator)

### ISSUE THREAD

**Issue by anandpeethambarantp** [typestack/routing-controllers#978]
### Description
I was getting validation issue with the @QueryParams decorator even without passing any query parameters.

**Minimal code-snippet showcasing the problem**
The error goes like this. 
```
[
  ValidationError {
    target: GroupFilterModel {},
    value: undefined,
   property: undefined,
    children: [],
     constraints: {
     unknownValue: 'an unknown value was passed to the validate function'
   }
   }
 ]
```

### Expected behavior
There should not be any validation issue.

### Actual behavior
Getting validation issue with undefined property.

When I checked the routing-controllers package.json peerDependency version of class-validator is 0.13.2. But the latest version is 0.14.0. 
With the latest version I'm getting this error and when I did a downgrade to old 0.13.4, there is no error.

Thanks

**Comment by SishaarRao** [comment]
Related to https://github.com/typestack/routing-controllers/issues/990

**Comment by attilaorosz** [comment]
@anandpeethambarantp Could you retry this with the latest version?

**Comment by attilaorosz** [comment]
Closing as stale
