### ISSUE TITLE
question: How to redirect after action is completed.

### ISSUE THREAD

**Issue by sarathjasrin** [typestack/routing-controllers#984]
**I was trying to redirect after authenticating. So I'm using UseAfter.**
```
@Post('/users/login')
    @UseAfter(loginMiddleWare)
    async login(@Session() session: any, @Body() userData: UserLoginDto, @Req() req) {
        const res: unknown = await this.userService.login(userData, session);
        req.myRes = res;
        return res;
    }
```

I wrote a middleware to redirect.  

```
export function loginMiddleWare(request: any, response: any, next: (err?: any) => any) {
    const res: Res<User> = request.myRes;
    if (res.type === ResponseTypes.Success) {
        response.redirect('/');
    } next()
}
```

**The problem:**
Looks like the response is already sent. I couldn't redirect. It's throwing following error. 

`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

**Comment by attilaorosz** [comment]
Hello,

Please use the discussions tab for questions.

If you return the response object it will be sent to the client automatically. Please check the docs for a redirect action: https://github.com/typestack/routing-controllers#set-redirect

The other option is to set your redirect in your response object and simply return the response object.

**Comment by gayanhewa** [comment]
> Yes, we can use redirect but can't do conditional redirect.

I think this is because you are calling next right after the conditional. I think the nature of node attempts to execute the code after the conditional while the redirect instruction is getting processed. You could either try to add the next in an else block or inverse the condition.

```
export function loginMiddleWare(request: any, response: any, next: (err?: any) => any) {
    const res: Res<User> = request.myRes;
    if (res.type === ResponseTypes.Success) {
        response.redirect('/');
    } else {
      next()
   }
}
```

**Comment by attilaorosz** [comment]
I believe this has been answered, if you have further questions please reopen this.
